# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230701


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class VmwareBinaryDownloadInfo(object):
    """
    The VMware binary download.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new VmwareBinaryDownloadInfo object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param file_name:
            The value to assign to the file_name property of this VmwareBinaryDownloadInfo.
        :type file_name: str

        :param url:
            The value to assign to the url property of this VmwareBinaryDownloadInfo.
        :type url: str

        :param time_expires:
            The value to assign to the time_expires property of this VmwareBinaryDownloadInfo.
        :type time_expires: datetime

        """
        self.swagger_types = {
            'file_name': 'str',
            'url': 'str',
            'time_expires': 'datetime'
        }
        self.attribute_map = {
            'file_name': 'fileName',
            'url': 'url',
            'time_expires': 'timeExpires'
        }
        self._file_name = None
        self._url = None
        self._time_expires = None

    @property
    def file_name(self):
        """
        **[Required]** Gets the file_name of this VmwareBinaryDownloadInfo.
        The name of the VMware binary file.


        :return: The file_name of this VmwareBinaryDownloadInfo.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """
        Sets the file_name of this VmwareBinaryDownloadInfo.
        The name of the VMware binary file.


        :param file_name: The file_name of this VmwareBinaryDownloadInfo.
        :type: str
        """
        self._file_name = file_name

    @property
    def url(self):
        """
        **[Required]** Gets the url of this VmwareBinaryDownloadInfo.
        The URL to download the VMware binary.


        :return: The url of this VmwareBinaryDownloadInfo.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this VmwareBinaryDownloadInfo.
        The URL to download the VMware binary.


        :param url: The url of this VmwareBinaryDownloadInfo.
        :type: str
        """
        self._url = url

    @property
    def time_expires(self):
        """
        **[Required]** Gets the time_expires of this VmwareBinaryDownloadInfo.
        The expiration date for the URL, in the format defined by `RFC3339`__.
        After this date the URL will no longer be valid.

        Example: `2016-08-25T21:10:29.600Z`

        __ https://tools.ietf.org/html/rfc3339


        :return: The time_expires of this VmwareBinaryDownloadInfo.
        :rtype: datetime
        """
        return self._time_expires

    @time_expires.setter
    def time_expires(self, time_expires):
        """
        Sets the time_expires of this VmwareBinaryDownloadInfo.
        The expiration date for the URL, in the format defined by `RFC3339`__.
        After this date the URL will no longer be valid.

        Example: `2016-08-25T21:10:29.600Z`

        __ https://tools.ietf.org/html/rfc3339


        :param time_expires: The time_expires of this VmwareBinaryDownloadInfo.
        :type: datetime
        """
        self._time_expires = time_expires

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
