# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230518

from .clone_oracle_migration_settings import CloneOracleMigrationSettings
from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CloneOracleOnlineLogicalMigrationSettings(CloneOracleMigrationSettings):
    """
    Clone settings for an online logical Oracle migration.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new CloneOracleOnlineLogicalMigrationSettings object with values from keyword arguments. The default value of the :py:attr:`~oci.database_migration.models.CloneOracleOnlineLogicalMigrationSettings.migration_method` attribute
        of this class is ``ONLINE_LOGICAL`` and it should not be changed.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param migration_method:
            The value to assign to the migration_method property of this CloneOracleOnlineLogicalMigrationSettings.
            Allowed values for this property are: "ONLINE_LOGICAL", "OFFLINE_LOGICAL", "ONLINE_STANDBY"
        :type migration_method: str

        :param source_container_database_connection_id:
            The value to assign to the source_container_database_connection_id property of this CloneOracleOnlineLogicalMigrationSettings.
        :type source_container_database_connection_id: str

        """
        self.swagger_types = {
            'migration_method': 'str',
            'source_container_database_connection_id': 'str'
        }
        self.attribute_map = {
            'migration_method': 'migrationMethod',
            'source_container_database_connection_id': 'sourceContainerDatabaseConnectionId'
        }
        self._migration_method = None
        self._source_container_database_connection_id = None
        self._migration_method = 'ONLINE_LOGICAL'

    @property
    def source_container_database_connection_id(self):
        """
        Gets the source_container_database_connection_id of this CloneOracleOnlineLogicalMigrationSettings.
        The OCID of the resource being referenced.


        :return: The source_container_database_connection_id of this CloneOracleOnlineLogicalMigrationSettings.
        :rtype: str
        """
        return self._source_container_database_connection_id

    @source_container_database_connection_id.setter
    def source_container_database_connection_id(self, source_container_database_connection_id):
        """
        Sets the source_container_database_connection_id of this CloneOracleOnlineLogicalMigrationSettings.
        The OCID of the resource being referenced.


        :param source_container_database_connection_id: The source_container_database_connection_id of this CloneOracleOnlineLogicalMigrationSettings.
        :type: str
        """
        self._source_container_database_connection_id = source_container_database_connection_id

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
