# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230518


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class DataVerificationObjectStatusSummary(object):
    """
    Per-object status comparison line.
    """

    #: A constant which can be used with the database_combination property of a DataVerificationObjectStatusSummary.
    #: This constant has a value of "MYSQL"
    DATABASE_COMBINATION_MYSQL = "MYSQL"

    #: A constant which can be used with the database_combination property of a DataVerificationObjectStatusSummary.
    #: This constant has a value of "ORACLE"
    DATABASE_COMBINATION_ORACLE = "ORACLE"

    def __init__(self, **kwargs):
        """
        Initializes a new DataVerificationObjectStatusSummary object with values from keyword arguments. This class has the following subclasses and if you are using this class as input
        to a service operations then you should favor using a subclass over the base class:

        * :class:`~oci.database_migration.models.MySqlDataVerificationObjectStatusSummary`
        * :class:`~oci.database_migration.models.OracleDataVerificationObjectStatusSummary`

        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param database_combination:
            The value to assign to the database_combination property of this DataVerificationObjectStatusSummary.
            Allowed values for this property are: "MYSQL", "ORACLE", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type database_combination: str

        :param owner:
            The value to assign to the owner property of this DataVerificationObjectStatusSummary.
        :type owner: str

        :param object_name:
            The value to assign to the object_name property of this DataVerificationObjectStatusSummary.
        :type object_name: str

        :param status_in_source:
            The value to assign to the status_in_source property of this DataVerificationObjectStatusSummary.
        :type status_in_source: str

        :param status_in_target:
            The value to assign to the status_in_target property of this DataVerificationObjectStatusSummary.
        :type status_in_target: str

        """
        self.swagger_types = {
            'database_combination': 'str',
            'owner': 'str',
            'object_name': 'str',
            'status_in_source': 'str',
            'status_in_target': 'str'
        }
        self.attribute_map = {
            'database_combination': 'databaseCombination',
            'owner': 'owner',
            'object_name': 'objectName',
            'status_in_source': 'statusInSource',
            'status_in_target': 'statusInTarget'
        }
        self._database_combination = None
        self._owner = None
        self._object_name = None
        self._status_in_source = None
        self._status_in_target = None

    @staticmethod
    def get_subtype(object_dictionary):
        """
        Given the hash representation of a subtype of this class,
        use the info in the hash to return the class of the subtype.
        """
        type = object_dictionary['databaseCombination']

        if type == 'MYSQL':
            return 'MySqlDataVerificationObjectStatusSummary'

        if type == 'ORACLE':
            return 'OracleDataVerificationObjectStatusSummary'
        else:
            return 'DataVerificationObjectStatusSummary'

    @property
    def database_combination(self):
        """
        **[Required]** Gets the database_combination of this DataVerificationObjectStatusSummary.
        The combination of source and target databases participating in a migration.
        Example: ORACLE means the migration is meant for migrating Oracle source and target databases.

        Allowed values for this property are: "MYSQL", "ORACLE", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The database_combination of this DataVerificationObjectStatusSummary.
        :rtype: str
        """
        return self._database_combination

    @database_combination.setter
    def database_combination(self, database_combination):
        """
        Sets the database_combination of this DataVerificationObjectStatusSummary.
        The combination of source and target databases participating in a migration.
        Example: ORACLE means the migration is meant for migrating Oracle source and target databases.


        :param database_combination: The database_combination of this DataVerificationObjectStatusSummary.
        :type: str
        """
        allowed_values = ["MYSQL", "ORACLE"]
        if not value_allowed_none_or_none_sentinel(database_combination, allowed_values):
            database_combination = 'UNKNOWN_ENUM_VALUE'
        self._database_combination = database_combination

    @property
    def owner(self):
        """
        Gets the owner of this DataVerificationObjectStatusSummary.
        Schema/owner name.

        This field is omitted (null/empty depending on backend serialization) for database-wide object types
        that are not schema-scoped.

        Oracle non-schema-scoped object types: USER, ROLE, PROFILE, TABLESPACE, DATABASE_LINK, CONTROLFILE,
        DATAFILE, REDO_LOG, DIRECTORY, LIBRARY, CONTEXT.

        MySQL non-schema-scoped object types: USER, ROLE, SERVER, TABLESPACE, LOGFILE_GROUP.


        :return: The owner of this DataVerificationObjectStatusSummary.
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """
        Sets the owner of this DataVerificationObjectStatusSummary.
        Schema/owner name.

        This field is omitted (null/empty depending on backend serialization) for database-wide object types
        that are not schema-scoped.

        Oracle non-schema-scoped object types: USER, ROLE, PROFILE, TABLESPACE, DATABASE_LINK, CONTROLFILE,
        DATAFILE, REDO_LOG, DIRECTORY, LIBRARY, CONTEXT.

        MySQL non-schema-scoped object types: USER, ROLE, SERVER, TABLESPACE, LOGFILE_GROUP.


        :param owner: The owner of this DataVerificationObjectStatusSummary.
        :type: str
        """
        self._owner = owner

    @property
    def object_name(self):
        """
        **[Required]** Gets the object_name of this DataVerificationObjectStatusSummary.
        Database object name.


        :return: The object_name of this DataVerificationObjectStatusSummary.
        :rtype: str
        """
        return self._object_name

    @object_name.setter
    def object_name(self, object_name):
        """
        Sets the object_name of this DataVerificationObjectStatusSummary.
        Database object name.


        :param object_name: The object_name of this DataVerificationObjectStatusSummary.
        :type: str
        """
        self._object_name = object_name

    @property
    def status_in_source(self):
        """
        **[Required]** Gets the status_in_source of this DataVerificationObjectStatusSummary.
        Object status in source.


        :return: The status_in_source of this DataVerificationObjectStatusSummary.
        :rtype: str
        """
        return self._status_in_source

    @status_in_source.setter
    def status_in_source(self, status_in_source):
        """
        Sets the status_in_source of this DataVerificationObjectStatusSummary.
        Object status in source.


        :param status_in_source: The status_in_source of this DataVerificationObjectStatusSummary.
        :type: str
        """
        self._status_in_source = status_in_source

    @property
    def status_in_target(self):
        """
        **[Required]** Gets the status_in_target of this DataVerificationObjectStatusSummary.
        Object status in target.


        :return: The status_in_target of this DataVerificationObjectStatusSummary.
        :rtype: str
        """
        return self._status_in_target

    @status_in_target.setter
    def status_in_target(self, status_in_target):
        """
        Sets the status_in_target of this DataVerificationObjectStatusSummary.
        Object status in target.


        :param status_in_target: The status_in_target of this DataVerificationObjectStatusSummary.
        :type: str
        """
        self._status_in_target = status_in_target

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
