# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230518


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class DataVerificationObjectStatusCollection(object):
    """
    Results of an Object Status listing.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new DataVerificationObjectStatusCollection object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param items:
            The value to assign to the items property of this DataVerificationObjectStatusCollection.
        :type items: list[oci.database_migration.models.DataVerificationObjectStatusSummary]

        :param total_items:
            The value to assign to the total_items property of this DataVerificationObjectStatusCollection.
        :type total_items: int

        """
        self.swagger_types = {
            'items': 'list[DataVerificationObjectStatusSummary]',
            'total_items': 'int'
        }
        self.attribute_map = {
            'items': 'items',
            'total_items': 'totalItems'
        }
        self._items = None
        self._total_items = None

    @property
    def items(self):
        """
        **[Required]** Gets the items of this DataVerificationObjectStatusCollection.
        Items in collection.


        :return: The items of this DataVerificationObjectStatusCollection.
        :rtype: list[oci.database_migration.models.DataVerificationObjectStatusSummary]
        """
        return self._items

    @items.setter
    def items(self, items):
        """
        Sets the items of this DataVerificationObjectStatusCollection.
        Items in collection.


        :param items: The items of this DataVerificationObjectStatusCollection.
        :type: list[oci.database_migration.models.DataVerificationObjectStatusSummary]
        """
        self._items = items

    @property
    def total_items(self):
        """
        **[Required]** Gets the total_items of this DataVerificationObjectStatusCollection.
        Total number of items matching the request.


        :return: The total_items of this DataVerificationObjectStatusCollection.
        :rtype: int
        """
        return self._total_items

    @total_items.setter
    def total_items(self, total_items):
        """
        Sets the total_items of this DataVerificationObjectStatusCollection.
        Total number of items matching the request.


        :param total_items: The total_items of this DataVerificationObjectStatusCollection.
        :type: int
        """
        self._total_items = total_items

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
