# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230518

from .data_verification_object_type_count_summary import DataVerificationObjectTypeCountSummary
from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class MySqlDataVerificationObjectTypeCountSummary(DataVerificationObjectTypeCountSummary):
    """
    Object type count comparison summary line for MySQL migrations.
    """

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "TABLE"
    OBJECT_TYPE_TABLE = "TABLE"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "VIEW"
    OBJECT_TYPE_VIEW = "VIEW"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "INDEX"
    OBJECT_TYPE_INDEX = "INDEX"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "TRIGGER"
    OBJECT_TYPE_TRIGGER = "TRIGGER"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "PROCEDURE"
    OBJECT_TYPE_PROCEDURE = "PROCEDURE"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "FUNCTION"
    OBJECT_TYPE_FUNCTION = "FUNCTION"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "EVENT"
    OBJECT_TYPE_EVENT = "EVENT"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "DATABASE"
    OBJECT_TYPE_DATABASE = "DATABASE"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "SCHEMA"
    OBJECT_TYPE_SCHEMA = "SCHEMA"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "TABLESPACE"
    OBJECT_TYPE_TABLESPACE = "TABLESPACE"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "SERVER"
    OBJECT_TYPE_SERVER = "SERVER"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "LOGFILE_GROUP"
    OBJECT_TYPE_LOGFILE_GROUP = "LOGFILE_GROUP"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "USER"
    OBJECT_TYPE_USER = "USER"

    #: A constant which can be used with the object_type property of a MySqlDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "ROLE"
    OBJECT_TYPE_ROLE = "ROLE"

    def __init__(self, **kwargs):
        """
        Initializes a new MySqlDataVerificationObjectTypeCountSummary object with values from keyword arguments. The default value of the :py:attr:`~oci.database_migration.models.MySqlDataVerificationObjectTypeCountSummary.database_combination` attribute
        of this class is ``MYSQL`` and it should not be changed.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param database_combination:
            The value to assign to the database_combination property of this MySqlDataVerificationObjectTypeCountSummary.
            Allowed values for this property are: "MYSQL", "ORACLE", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type database_combination: str

        :param schema_name:
            The value to assign to the schema_name property of this MySqlDataVerificationObjectTypeCountSummary.
        :type schema_name: str

        :param source_object_count:
            The value to assign to the source_object_count property of this MySqlDataVerificationObjectTypeCountSummary.
        :type source_object_count: int

        :param target_object_count:
            The value to assign to the target_object_count property of this MySqlDataVerificationObjectTypeCountSummary.
        :type target_object_count: int

        :param delta_percent:
            The value to assign to the delta_percent property of this MySqlDataVerificationObjectTypeCountSummary.
        :type delta_percent: float

        :param object_type:
            The value to assign to the object_type property of this MySqlDataVerificationObjectTypeCountSummary.
            Allowed values for this property are: "TABLE", "VIEW", "INDEX", "TRIGGER", "PROCEDURE", "FUNCTION", "EVENT", "DATABASE", "SCHEMA", "TABLESPACE", "SERVER", "LOGFILE_GROUP", "USER", "ROLE", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type object_type: str

        :param source_invalid_count:
            The value to assign to the source_invalid_count property of this MySqlDataVerificationObjectTypeCountSummary.
        :type source_invalid_count: int

        :param target_invalid_count:
            The value to assign to the target_invalid_count property of this MySqlDataVerificationObjectTypeCountSummary.
        :type target_invalid_count: int

        """
        self.swagger_types = {
            'database_combination': 'str',
            'schema_name': 'str',
            'source_object_count': 'int',
            'target_object_count': 'int',
            'delta_percent': 'float',
            'object_type': 'str',
            'source_invalid_count': 'int',
            'target_invalid_count': 'int'
        }
        self.attribute_map = {
            'database_combination': 'databaseCombination',
            'schema_name': 'schemaName',
            'source_object_count': 'sourceObjectCount',
            'target_object_count': 'targetObjectCount',
            'delta_percent': 'deltaPercent',
            'object_type': 'objectType',
            'source_invalid_count': 'sourceInvalidCount',
            'target_invalid_count': 'targetInvalidCount'
        }
        self._database_combination = None
        self._schema_name = None
        self._source_object_count = None
        self._target_object_count = None
        self._delta_percent = None
        self._object_type = None
        self._source_invalid_count = None
        self._target_invalid_count = None
        self._database_combination = 'MYSQL'

    @property
    def object_type(self):
        """
        **[Required]** Gets the object_type of this MySqlDataVerificationObjectTypeCountSummary.
        MySQL database object type.

        Allowed values for this property are: "TABLE", "VIEW", "INDEX", "TRIGGER", "PROCEDURE", "FUNCTION", "EVENT", "DATABASE", "SCHEMA", "TABLESPACE", "SERVER", "LOGFILE_GROUP", "USER", "ROLE", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The object_type of this MySqlDataVerificationObjectTypeCountSummary.
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type):
        """
        Sets the object_type of this MySqlDataVerificationObjectTypeCountSummary.
        MySQL database object type.


        :param object_type: The object_type of this MySqlDataVerificationObjectTypeCountSummary.
        :type: str
        """
        allowed_values = ["TABLE", "VIEW", "INDEX", "TRIGGER", "PROCEDURE", "FUNCTION", "EVENT", "DATABASE", "SCHEMA", "TABLESPACE", "SERVER", "LOGFILE_GROUP", "USER", "ROLE"]
        if not value_allowed_none_or_none_sentinel(object_type, allowed_values):
            object_type = 'UNKNOWN_ENUM_VALUE'
        self._object_type = object_type

    @property
    def source_invalid_count(self):
        """
        **[Required]** Gets the source_invalid_count of this MySqlDataVerificationObjectTypeCountSummary.
        Number of invalid objects in source.


        :return: The source_invalid_count of this MySqlDataVerificationObjectTypeCountSummary.
        :rtype: int
        """
        return self._source_invalid_count

    @source_invalid_count.setter
    def source_invalid_count(self, source_invalid_count):
        """
        Sets the source_invalid_count of this MySqlDataVerificationObjectTypeCountSummary.
        Number of invalid objects in source.


        :param source_invalid_count: The source_invalid_count of this MySqlDataVerificationObjectTypeCountSummary.
        :type: int
        """
        self._source_invalid_count = source_invalid_count

    @property
    def target_invalid_count(self):
        """
        **[Required]** Gets the target_invalid_count of this MySqlDataVerificationObjectTypeCountSummary.
        Number of invalid objects in target.


        :return: The target_invalid_count of this MySqlDataVerificationObjectTypeCountSummary.
        :rtype: int
        """
        return self._target_invalid_count

    @target_invalid_count.setter
    def target_invalid_count(self, target_invalid_count):
        """
        Sets the target_invalid_count of this MySqlDataVerificationObjectTypeCountSummary.
        Number of invalid objects in target.


        :param target_invalid_count: The target_invalid_count of this MySqlDataVerificationObjectTypeCountSummary.
        :type: int
        """
        self._target_invalid_count = target_invalid_count

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
