# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230518

from .data_verification_object_type_count_summary import DataVerificationObjectTypeCountSummary
from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class OracleDataVerificationObjectTypeCountSummary(DataVerificationObjectTypeCountSummary):
    """
    Object type count comparison summary line for Oracle migrations.
    """

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "TABLE"
    OBJECT_TYPE_TABLE = "TABLE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "INDEX"
    OBJECT_TYPE_INDEX = "INDEX"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "VIEW"
    OBJECT_TYPE_VIEW = "VIEW"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "SEQUENCE"
    OBJECT_TYPE_SEQUENCE = "SEQUENCE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "SYNONYM"
    OBJECT_TYPE_SYNONYM = "SYNONYM"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "CLUSTER"
    OBJECT_TYPE_CLUSTER = "CLUSTER"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "PROCEDURE"
    OBJECT_TYPE_PROCEDURE = "PROCEDURE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "FUNCTION"
    OBJECT_TYPE_FUNCTION = "FUNCTION"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "PACKAGE"
    OBJECT_TYPE_PACKAGE = "PACKAGE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "PACKAGE_BODY"
    OBJECT_TYPE_PACKAGE_BODY = "PACKAGE_BODY"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "TRIGGER"
    OBJECT_TYPE_TRIGGER = "TRIGGER"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "USER"
    OBJECT_TYPE_USER = "USER"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "ROLE"
    OBJECT_TYPE_ROLE = "ROLE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "PROFILE"
    OBJECT_TYPE_PROFILE = "PROFILE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "MATERIALIZED_VIEW"
    OBJECT_TYPE_MATERIALIZED_VIEW = "MATERIALIZED_VIEW"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "TYPE"
    OBJECT_TYPE_TYPE = "TYPE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "TYPE_BODY"
    OBJECT_TYPE_TYPE_BODY = "TYPE_BODY"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "OPERATOR"
    OBJECT_TYPE_OPERATOR = "OPERATOR"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "LIBRARY"
    OBJECT_TYPE_LIBRARY = "LIBRARY"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "DIRECTORY"
    OBJECT_TYPE_DIRECTORY = "DIRECTORY"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "TABLESPACE"
    OBJECT_TYPE_TABLESPACE = "TABLESPACE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "DATABASE_LINK"
    OBJECT_TYPE_DATABASE_LINK = "DATABASE_LINK"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "CONTROLFILE"
    OBJECT_TYPE_CONTROLFILE = "CONTROLFILE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "DATAFILE"
    OBJECT_TYPE_DATAFILE = "DATAFILE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "REDO_LOG"
    OBJECT_TYPE_REDO_LOG = "REDO_LOG"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "JAVA_CLASS"
    OBJECT_TYPE_JAVA_CLASS = "JAVA_CLASS"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "JAVA_SOURCE"
    OBJECT_TYPE_JAVA_SOURCE = "JAVA_SOURCE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "JAVA_RESOURCE"
    OBJECT_TYPE_JAVA_RESOURCE = "JAVA_RESOURCE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "XML_SCHEMA"
    OBJECT_TYPE_XML_SCHEMA = "XML_SCHEMA"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "QUEUE"
    OBJECT_TYPE_QUEUE = "QUEUE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "QUEUE_TABLE"
    OBJECT_TYPE_QUEUE_TABLE = "QUEUE_TABLE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "DIMENSION"
    OBJECT_TYPE_DIMENSION = "DIMENSION"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectTypeCountSummary.
    #: This constant has a value of "CONTEXT"
    OBJECT_TYPE_CONTEXT = "CONTEXT"

    def __init__(self, **kwargs):
        """
        Initializes a new OracleDataVerificationObjectTypeCountSummary object with values from keyword arguments. The default value of the :py:attr:`~oci.database_migration.models.OracleDataVerificationObjectTypeCountSummary.database_combination` attribute
        of this class is ``ORACLE`` and it should not be changed.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param database_combination:
            The value to assign to the database_combination property of this OracleDataVerificationObjectTypeCountSummary.
            Allowed values for this property are: "MYSQL", "ORACLE", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type database_combination: str

        :param schema_name:
            The value to assign to the schema_name property of this OracleDataVerificationObjectTypeCountSummary.
        :type schema_name: str

        :param source_object_count:
            The value to assign to the source_object_count property of this OracleDataVerificationObjectTypeCountSummary.
        :type source_object_count: int

        :param target_object_count:
            The value to assign to the target_object_count property of this OracleDataVerificationObjectTypeCountSummary.
        :type target_object_count: int

        :param delta_percent:
            The value to assign to the delta_percent property of this OracleDataVerificationObjectTypeCountSummary.
        :type delta_percent: float

        :param object_type:
            The value to assign to the object_type property of this OracleDataVerificationObjectTypeCountSummary.
            Allowed values for this property are: "TABLE", "INDEX", "VIEW", "SEQUENCE", "SYNONYM", "CLUSTER", "PROCEDURE", "FUNCTION", "PACKAGE", "PACKAGE_BODY", "TRIGGER", "USER", "ROLE", "PROFILE", "MATERIALIZED_VIEW", "TYPE", "TYPE_BODY", "OPERATOR", "LIBRARY", "DIRECTORY", "TABLESPACE", "DATABASE_LINK", "CONTROLFILE", "DATAFILE", "REDO_LOG", "JAVA_CLASS", "JAVA_SOURCE", "JAVA_RESOURCE", "XML_SCHEMA", "QUEUE", "QUEUE_TABLE", "DIMENSION", "CONTEXT", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type object_type: str

        :param source_invalid_count:
            The value to assign to the source_invalid_count property of this OracleDataVerificationObjectTypeCountSummary.
        :type source_invalid_count: int

        :param target_invalid_count:
            The value to assign to the target_invalid_count property of this OracleDataVerificationObjectTypeCountSummary.
        :type target_invalid_count: int

        """
        self.swagger_types = {
            'database_combination': 'str',
            'schema_name': 'str',
            'source_object_count': 'int',
            'target_object_count': 'int',
            'delta_percent': 'float',
            'object_type': 'str',
            'source_invalid_count': 'int',
            'target_invalid_count': 'int'
        }
        self.attribute_map = {
            'database_combination': 'databaseCombination',
            'schema_name': 'schemaName',
            'source_object_count': 'sourceObjectCount',
            'target_object_count': 'targetObjectCount',
            'delta_percent': 'deltaPercent',
            'object_type': 'objectType',
            'source_invalid_count': 'sourceInvalidCount',
            'target_invalid_count': 'targetInvalidCount'
        }
        self._database_combination = None
        self._schema_name = None
        self._source_object_count = None
        self._target_object_count = None
        self._delta_percent = None
        self._object_type = None
        self._source_invalid_count = None
        self._target_invalid_count = None
        self._database_combination = 'ORACLE'

    @property
    def object_type(self):
        """
        **[Required]** Gets the object_type of this OracleDataVerificationObjectTypeCountSummary.
        Oracle database object type.

        Allowed values for this property are: "TABLE", "INDEX", "VIEW", "SEQUENCE", "SYNONYM", "CLUSTER", "PROCEDURE", "FUNCTION", "PACKAGE", "PACKAGE_BODY", "TRIGGER", "USER", "ROLE", "PROFILE", "MATERIALIZED_VIEW", "TYPE", "TYPE_BODY", "OPERATOR", "LIBRARY", "DIRECTORY", "TABLESPACE", "DATABASE_LINK", "CONTROLFILE", "DATAFILE", "REDO_LOG", "JAVA_CLASS", "JAVA_SOURCE", "JAVA_RESOURCE", "XML_SCHEMA", "QUEUE", "QUEUE_TABLE", "DIMENSION", "CONTEXT", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The object_type of this OracleDataVerificationObjectTypeCountSummary.
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type):
        """
        Sets the object_type of this OracleDataVerificationObjectTypeCountSummary.
        Oracle database object type.


        :param object_type: The object_type of this OracleDataVerificationObjectTypeCountSummary.
        :type: str
        """
        allowed_values = ["TABLE", "INDEX", "VIEW", "SEQUENCE", "SYNONYM", "CLUSTER", "PROCEDURE", "FUNCTION", "PACKAGE", "PACKAGE_BODY", "TRIGGER", "USER", "ROLE", "PROFILE", "MATERIALIZED_VIEW", "TYPE", "TYPE_BODY", "OPERATOR", "LIBRARY", "DIRECTORY", "TABLESPACE", "DATABASE_LINK", "CONTROLFILE", "DATAFILE", "REDO_LOG", "JAVA_CLASS", "JAVA_SOURCE", "JAVA_RESOURCE", "XML_SCHEMA", "QUEUE", "QUEUE_TABLE", "DIMENSION", "CONTEXT"]
        if not value_allowed_none_or_none_sentinel(object_type, allowed_values):
            object_type = 'UNKNOWN_ENUM_VALUE'
        self._object_type = object_type

    @property
    def source_invalid_count(self):
        """
        **[Required]** Gets the source_invalid_count of this OracleDataVerificationObjectTypeCountSummary.
        Number of invalid objects in source.


        :return: The source_invalid_count of this OracleDataVerificationObjectTypeCountSummary.
        :rtype: int
        """
        return self._source_invalid_count

    @source_invalid_count.setter
    def source_invalid_count(self, source_invalid_count):
        """
        Sets the source_invalid_count of this OracleDataVerificationObjectTypeCountSummary.
        Number of invalid objects in source.


        :param source_invalid_count: The source_invalid_count of this OracleDataVerificationObjectTypeCountSummary.
        :type: int
        """
        self._source_invalid_count = source_invalid_count

    @property
    def target_invalid_count(self):
        """
        **[Required]** Gets the target_invalid_count of this OracleDataVerificationObjectTypeCountSummary.
        Number of invalid objects in target.


        :return: The target_invalid_count of this OracleDataVerificationObjectTypeCountSummary.
        :rtype: int
        """
        return self._target_invalid_count

    @target_invalid_count.setter
    def target_invalid_count(self, target_invalid_count):
        """
        Sets the target_invalid_count of this OracleDataVerificationObjectTypeCountSummary.
        Number of invalid objects in target.


        :param target_invalid_count: The target_invalid_count of this OracleDataVerificationObjectTypeCountSummary.
        :type: int
        """
        self._target_invalid_count = target_invalid_count

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
