# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230518

from .data_verification_object_status_summary import DataVerificationObjectStatusSummary
from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class OracleDataVerificationObjectStatusSummary(DataVerificationObjectStatusSummary):
    """
    Per-object status comparison line for Oracle migrations.
    """

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "TABLE"
    OBJECT_TYPE_TABLE = "TABLE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "INDEX"
    OBJECT_TYPE_INDEX = "INDEX"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "VIEW"
    OBJECT_TYPE_VIEW = "VIEW"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "SEQUENCE"
    OBJECT_TYPE_SEQUENCE = "SEQUENCE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "SYNONYM"
    OBJECT_TYPE_SYNONYM = "SYNONYM"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "CLUSTER"
    OBJECT_TYPE_CLUSTER = "CLUSTER"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "PROCEDURE"
    OBJECT_TYPE_PROCEDURE = "PROCEDURE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "FUNCTION"
    OBJECT_TYPE_FUNCTION = "FUNCTION"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "PACKAGE"
    OBJECT_TYPE_PACKAGE = "PACKAGE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "PACKAGE_BODY"
    OBJECT_TYPE_PACKAGE_BODY = "PACKAGE_BODY"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "TRIGGER"
    OBJECT_TYPE_TRIGGER = "TRIGGER"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "USER"
    OBJECT_TYPE_USER = "USER"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "ROLE"
    OBJECT_TYPE_ROLE = "ROLE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "PROFILE"
    OBJECT_TYPE_PROFILE = "PROFILE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "MATERIALIZED_VIEW"
    OBJECT_TYPE_MATERIALIZED_VIEW = "MATERIALIZED_VIEW"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "TYPE"
    OBJECT_TYPE_TYPE = "TYPE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "TYPE_BODY"
    OBJECT_TYPE_TYPE_BODY = "TYPE_BODY"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "OPERATOR"
    OBJECT_TYPE_OPERATOR = "OPERATOR"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "LIBRARY"
    OBJECT_TYPE_LIBRARY = "LIBRARY"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "DIRECTORY"
    OBJECT_TYPE_DIRECTORY = "DIRECTORY"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "TABLESPACE"
    OBJECT_TYPE_TABLESPACE = "TABLESPACE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "DATABASE_LINK"
    OBJECT_TYPE_DATABASE_LINK = "DATABASE_LINK"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "CONTROLFILE"
    OBJECT_TYPE_CONTROLFILE = "CONTROLFILE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "DATAFILE"
    OBJECT_TYPE_DATAFILE = "DATAFILE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "REDO_LOG"
    OBJECT_TYPE_REDO_LOG = "REDO_LOG"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "JAVA_CLASS"
    OBJECT_TYPE_JAVA_CLASS = "JAVA_CLASS"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "JAVA_SOURCE"
    OBJECT_TYPE_JAVA_SOURCE = "JAVA_SOURCE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "JAVA_RESOURCE"
    OBJECT_TYPE_JAVA_RESOURCE = "JAVA_RESOURCE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "XML_SCHEMA"
    OBJECT_TYPE_XML_SCHEMA = "XML_SCHEMA"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "QUEUE"
    OBJECT_TYPE_QUEUE = "QUEUE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "QUEUE_TABLE"
    OBJECT_TYPE_QUEUE_TABLE = "QUEUE_TABLE"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "DIMENSION"
    OBJECT_TYPE_DIMENSION = "DIMENSION"

    #: A constant which can be used with the object_type property of a OracleDataVerificationObjectStatusSummary.
    #: This constant has a value of "CONTEXT"
    OBJECT_TYPE_CONTEXT = "CONTEXT"

    def __init__(self, **kwargs):
        """
        Initializes a new OracleDataVerificationObjectStatusSummary object with values from keyword arguments. The default value of the :py:attr:`~oci.database_migration.models.OracleDataVerificationObjectStatusSummary.database_combination` attribute
        of this class is ``ORACLE`` and it should not be changed.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param database_combination:
            The value to assign to the database_combination property of this OracleDataVerificationObjectStatusSummary.
            Allowed values for this property are: "MYSQL", "ORACLE", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type database_combination: str

        :param owner:
            The value to assign to the owner property of this OracleDataVerificationObjectStatusSummary.
        :type owner: str

        :param object_name:
            The value to assign to the object_name property of this OracleDataVerificationObjectStatusSummary.
        :type object_name: str

        :param status_in_source:
            The value to assign to the status_in_source property of this OracleDataVerificationObjectStatusSummary.
        :type status_in_source: str

        :param status_in_target:
            The value to assign to the status_in_target property of this OracleDataVerificationObjectStatusSummary.
        :type status_in_target: str

        :param object_type:
            The value to assign to the object_type property of this OracleDataVerificationObjectStatusSummary.
            Allowed values for this property are: "TABLE", "INDEX", "VIEW", "SEQUENCE", "SYNONYM", "CLUSTER", "PROCEDURE", "FUNCTION", "PACKAGE", "PACKAGE_BODY", "TRIGGER", "USER", "ROLE", "PROFILE", "MATERIALIZED_VIEW", "TYPE", "TYPE_BODY", "OPERATOR", "LIBRARY", "DIRECTORY", "TABLESPACE", "DATABASE_LINK", "CONTROLFILE", "DATAFILE", "REDO_LOG", "JAVA_CLASS", "JAVA_SOURCE", "JAVA_RESOURCE", "XML_SCHEMA", "QUEUE", "QUEUE_TABLE", "DIMENSION", "CONTEXT", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type object_type: str

        """
        self.swagger_types = {
            'database_combination': 'str',
            'owner': 'str',
            'object_name': 'str',
            'status_in_source': 'str',
            'status_in_target': 'str',
            'object_type': 'str'
        }
        self.attribute_map = {
            'database_combination': 'databaseCombination',
            'owner': 'owner',
            'object_name': 'objectName',
            'status_in_source': 'statusInSource',
            'status_in_target': 'statusInTarget',
            'object_type': 'objectType'
        }
        self._database_combination = None
        self._owner = None
        self._object_name = None
        self._status_in_source = None
        self._status_in_target = None
        self._object_type = None
        self._database_combination = 'ORACLE'

    @property
    def object_type(self):
        """
        **[Required]** Gets the object_type of this OracleDataVerificationObjectStatusSummary.
        Oracle database object type.

        Allowed values for this property are: "TABLE", "INDEX", "VIEW", "SEQUENCE", "SYNONYM", "CLUSTER", "PROCEDURE", "FUNCTION", "PACKAGE", "PACKAGE_BODY", "TRIGGER", "USER", "ROLE", "PROFILE", "MATERIALIZED_VIEW", "TYPE", "TYPE_BODY", "OPERATOR", "LIBRARY", "DIRECTORY", "TABLESPACE", "DATABASE_LINK", "CONTROLFILE", "DATAFILE", "REDO_LOG", "JAVA_CLASS", "JAVA_SOURCE", "JAVA_RESOURCE", "XML_SCHEMA", "QUEUE", "QUEUE_TABLE", "DIMENSION", "CONTEXT", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The object_type of this OracleDataVerificationObjectStatusSummary.
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type):
        """
        Sets the object_type of this OracleDataVerificationObjectStatusSummary.
        Oracle database object type.


        :param object_type: The object_type of this OracleDataVerificationObjectStatusSummary.
        :type: str
        """
        allowed_values = ["TABLE", "INDEX", "VIEW", "SEQUENCE", "SYNONYM", "CLUSTER", "PROCEDURE", "FUNCTION", "PACKAGE", "PACKAGE_BODY", "TRIGGER", "USER", "ROLE", "PROFILE", "MATERIALIZED_VIEW", "TYPE", "TYPE_BODY", "OPERATOR", "LIBRARY", "DIRECTORY", "TABLESPACE", "DATABASE_LINK", "CONTROLFILE", "DATAFILE", "REDO_LOG", "JAVA_CLASS", "JAVA_SOURCE", "JAVA_RESOURCE", "XML_SCHEMA", "QUEUE", "QUEUE_TABLE", "DIMENSION", "CONTEXT"]
        if not value_allowed_none_or_none_sentinel(object_type, allowed_values):
            object_type = 'UNKNOWN_ENUM_VALUE'
        self._object_type = object_type

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
