# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230518


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class OracleMigrationSettingsSummary(object):
    """
    Discriminator-only base Oracle migration summary settings.
    """

    #: A constant which can be used with the migration_method property of a OracleMigrationSettingsSummary.
    #: This constant has a value of "ONLINE_LOGICAL"
    MIGRATION_METHOD_ONLINE_LOGICAL = "ONLINE_LOGICAL"

    #: A constant which can be used with the migration_method property of a OracleMigrationSettingsSummary.
    #: This constant has a value of "OFFLINE_LOGICAL"
    MIGRATION_METHOD_OFFLINE_LOGICAL = "OFFLINE_LOGICAL"

    #: A constant which can be used with the migration_method property of a OracleMigrationSettingsSummary.
    #: This constant has a value of "ONLINE_STANDBY"
    MIGRATION_METHOD_ONLINE_STANDBY = "ONLINE_STANDBY"

    def __init__(self, **kwargs):
        """
        Initializes a new OracleMigrationSettingsSummary object with values from keyword arguments. This class has the following subclasses and if you are using this class as input
        to a service operations then you should favor using a subclass over the base class:

        * :class:`~oci.database_migration.models.OracleOfflineLogicalMigrationSettingsSummary`
        * :class:`~oci.database_migration.models.OracleOnlineStandbyMigrationSettingsSummary`
        * :class:`~oci.database_migration.models.OracleOnlineLogicalMigrationSettingsSummary`

        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param migration_method:
            The value to assign to the migration_method property of this OracleMigrationSettingsSummary.
            Allowed values for this property are: "ONLINE_LOGICAL", "OFFLINE_LOGICAL", "ONLINE_STANDBY", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type migration_method: str

        """
        self.swagger_types = {
            'migration_method': 'str'
        }
        self.attribute_map = {
            'migration_method': 'migrationMethod'
        }
        self._migration_method = None

    @staticmethod
    def get_subtype(object_dictionary):
        """
        Given the hash representation of a subtype of this class,
        use the info in the hash to return the class of the subtype.
        """
        type = object_dictionary['migrationMethod']

        if type == 'OFFLINE_LOGICAL':
            return 'OracleOfflineLogicalMigrationSettingsSummary'

        if type == 'ONLINE_STANDBY':
            return 'OracleOnlineStandbyMigrationSettingsSummary'

        if type == 'ONLINE_LOGICAL':
            return 'OracleOnlineLogicalMigrationSettingsSummary'
        else:
            return 'OracleMigrationSettingsSummary'

    @property
    def migration_method(self):
        """
        **[Required]** Gets the migration_method of this OracleMigrationSettingsSummary.
        The Oracle migration method. This value combines the migration type and method so it can be used as
        a discriminator while preserving the existing migration type field.

        Allowed values for this property are: "ONLINE_LOGICAL", "OFFLINE_LOGICAL", "ONLINE_STANDBY", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The migration_method of this OracleMigrationSettingsSummary.
        :rtype: str
        """
        return self._migration_method

    @migration_method.setter
    def migration_method(self, migration_method):
        """
        Sets the migration_method of this OracleMigrationSettingsSummary.
        The Oracle migration method. This value combines the migration type and method so it can be used as
        a discriminator while preserving the existing migration type field.


        :param migration_method: The migration_method of this OracleMigrationSettingsSummary.
        :type: str
        """
        allowed_values = ["ONLINE_LOGICAL", "OFFLINE_LOGICAL", "ONLINE_STANDBY"]
        if not value_allowed_none_or_none_sentinel(migration_method, allowed_values):
            migration_method = 'UNKNOWN_ENUM_VALUE'
        self._migration_method = migration_method

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
