# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20230518

from .update_oracle_migration_settings import UpdateOracleMigrationSettings
from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class UpdateOracleOfflineLogicalMigrationSettings(UpdateOracleMigrationSettings):
    """
    Update settings for an offline logical Oracle migration.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new UpdateOracleOfflineLogicalMigrationSettings object with values from keyword arguments. The default value of the :py:attr:`~oci.database_migration.models.UpdateOracleOfflineLogicalMigrationSettings.migration_method` attribute
        of this class is ``OFFLINE_LOGICAL`` and it should not be changed.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param migration_method:
            The value to assign to the migration_method property of this UpdateOracleOfflineLogicalMigrationSettings.
            Allowed values for this property are: "ONLINE_LOGICAL", "OFFLINE_LOGICAL", "ONLINE_STANDBY"
        :type migration_method: str

        :param data_transfer_medium_details:
            The value to assign to the data_transfer_medium_details property of this UpdateOracleOfflineLogicalMigrationSettings.
        :type data_transfer_medium_details: oci.database_migration.models.UpdateOracleDataTransferMediumDetails

        :param initial_load_settings:
            The value to assign to the initial_load_settings property of this UpdateOracleOfflineLogicalMigrationSettings.
        :type initial_load_settings: oci.database_migration.models.UpdateOracleInitialLoadSettings

        :param advisor_settings:
            The value to assign to the advisor_settings property of this UpdateOracleOfflineLogicalMigrationSettings.
        :type advisor_settings: oci.database_migration.models.UpdateOracleAdvisorSettings

        :param advanced_parameters:
            The value to assign to the advanced_parameters property of this UpdateOracleOfflineLogicalMigrationSettings.
        :type advanced_parameters: list[oci.database_migration.models.MigrationParameterDetails]

        """
        self.swagger_types = {
            'migration_method': 'str',
            'data_transfer_medium_details': 'UpdateOracleDataTransferMediumDetails',
            'initial_load_settings': 'UpdateOracleInitialLoadSettings',
            'advisor_settings': 'UpdateOracleAdvisorSettings',
            'advanced_parameters': 'list[MigrationParameterDetails]'
        }
        self.attribute_map = {
            'migration_method': 'migrationMethod',
            'data_transfer_medium_details': 'dataTransferMediumDetails',
            'initial_load_settings': 'initialLoadSettings',
            'advisor_settings': 'advisorSettings',
            'advanced_parameters': 'advancedParameters'
        }
        self._migration_method = None
        self._data_transfer_medium_details = None
        self._initial_load_settings = None
        self._advisor_settings = None
        self._advanced_parameters = None
        self._migration_method = 'OFFLINE_LOGICAL'

    @property
    def data_transfer_medium_details(self):
        """
        Gets the data_transfer_medium_details of this UpdateOracleOfflineLogicalMigrationSettings.

        :return: The data_transfer_medium_details of this UpdateOracleOfflineLogicalMigrationSettings.
        :rtype: oci.database_migration.models.UpdateOracleDataTransferMediumDetails
        """
        return self._data_transfer_medium_details

    @data_transfer_medium_details.setter
    def data_transfer_medium_details(self, data_transfer_medium_details):
        """
        Sets the data_transfer_medium_details of this UpdateOracleOfflineLogicalMigrationSettings.

        :param data_transfer_medium_details: The data_transfer_medium_details of this UpdateOracleOfflineLogicalMigrationSettings.
        :type: oci.database_migration.models.UpdateOracleDataTransferMediumDetails
        """
        self._data_transfer_medium_details = data_transfer_medium_details

    @property
    def initial_load_settings(self):
        """
        Gets the initial_load_settings of this UpdateOracleOfflineLogicalMigrationSettings.

        :return: The initial_load_settings of this UpdateOracleOfflineLogicalMigrationSettings.
        :rtype: oci.database_migration.models.UpdateOracleInitialLoadSettings
        """
        return self._initial_load_settings

    @initial_load_settings.setter
    def initial_load_settings(self, initial_load_settings):
        """
        Sets the initial_load_settings of this UpdateOracleOfflineLogicalMigrationSettings.

        :param initial_load_settings: The initial_load_settings of this UpdateOracleOfflineLogicalMigrationSettings.
        :type: oci.database_migration.models.UpdateOracleInitialLoadSettings
        """
        self._initial_load_settings = initial_load_settings

    @property
    def advisor_settings(self):
        """
        Gets the advisor_settings of this UpdateOracleOfflineLogicalMigrationSettings.

        :return: The advisor_settings of this UpdateOracleOfflineLogicalMigrationSettings.
        :rtype: oci.database_migration.models.UpdateOracleAdvisorSettings
        """
        return self._advisor_settings

    @advisor_settings.setter
    def advisor_settings(self, advisor_settings):
        """
        Sets the advisor_settings of this UpdateOracleOfflineLogicalMigrationSettings.

        :param advisor_settings: The advisor_settings of this UpdateOracleOfflineLogicalMigrationSettings.
        :type: oci.database_migration.models.UpdateOracleAdvisorSettings
        """
        self._advisor_settings = advisor_settings

    @property
    def advanced_parameters(self):
        """
        Gets the advanced_parameters of this UpdateOracleOfflineLogicalMigrationSettings.
        List of Migration Parameter objects.


        :return: The advanced_parameters of this UpdateOracleOfflineLogicalMigrationSettings.
        :rtype: list[oci.database_migration.models.MigrationParameterDetails]
        """
        return self._advanced_parameters

    @advanced_parameters.setter
    def advanced_parameters(self, advanced_parameters):
        """
        Sets the advanced_parameters of this UpdateOracleOfflineLogicalMigrationSettings.
        List of Migration Parameter objects.


        :param advanced_parameters: The advanced_parameters of this UpdateOracleOfflineLogicalMigrationSettings.
        :type: list[oci.database_migration.models.MigrationParameterDetails]
        """
        self._advanced_parameters = advanced_parameters

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
