# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20231130


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CreateRoutingProfileDetails(object):
    """
    The data to create a routing profile.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new CreateRoutingProfileDetails object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param display_name:
            The value to assign to the display_name property of this CreateRoutingProfileDetails.
        :type display_name: str

        :param description:
            The value to assign to the description property of this CreateRoutingProfileDetails.
        :type description: str

        :param compartment_id:
            The value to assign to the compartment_id property of this CreateRoutingProfileDetails.
        :type compartment_id: str

        :param region_routing_policy:
            The value to assign to the region_routing_policy property of this CreateRoutingProfileDetails.
        :type region_routing_policy: oci.generative_ai.models.RegionRoutingPolicy

        :param model_routing_policy:
            The value to assign to the model_routing_policy property of this CreateRoutingProfileDetails.
        :type model_routing_policy: oci.generative_ai.models.ModelRoutingPolicy

        :param freeform_tags:
            The value to assign to the freeform_tags property of this CreateRoutingProfileDetails.
        :type freeform_tags: dict(str, str)

        :param defined_tags:
            The value to assign to the defined_tags property of this CreateRoutingProfileDetails.
        :type defined_tags: dict(str, dict(str, object))

        """
        self.swagger_types = {
            'display_name': 'str',
            'description': 'str',
            'compartment_id': 'str',
            'region_routing_policy': 'RegionRoutingPolicy',
            'model_routing_policy': 'ModelRoutingPolicy',
            'freeform_tags': 'dict(str, str)',
            'defined_tags': 'dict(str, dict(str, object))'
        }
        self.attribute_map = {
            'display_name': 'displayName',
            'description': 'description',
            'compartment_id': 'compartmentId',
            'region_routing_policy': 'regionRoutingPolicy',
            'model_routing_policy': 'modelRoutingPolicy',
            'freeform_tags': 'freeformTags',
            'defined_tags': 'definedTags'
        }
        self._display_name = None
        self._description = None
        self._compartment_id = None
        self._region_routing_policy = None
        self._model_routing_policy = None
        self._freeform_tags = None
        self._defined_tags = None

    @property
    def display_name(self):
        """
        **[Required]** Gets the display_name of this CreateRoutingProfileDetails.
        A user-friendly name. Does not have to be unique, and it's changeable.


        :return: The display_name of this CreateRoutingProfileDetails.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """
        Sets the display_name of this CreateRoutingProfileDetails.
        A user-friendly name. Does not have to be unique, and it's changeable.


        :param display_name: The display_name of this CreateRoutingProfileDetails.
        :type: str
        """
        self._display_name = display_name

    @property
    def description(self):
        """
        Gets the description of this CreateRoutingProfileDetails.
        An optional description of the routing profile.


        :return: The description of this CreateRoutingProfileDetails.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this CreateRoutingProfileDetails.
        An optional description of the routing profile.


        :param description: The description of this CreateRoutingProfileDetails.
        :type: str
        """
        self._description = description

    @property
    def compartment_id(self):
        """
        **[Required]** Gets the compartment_id of this CreateRoutingProfileDetails.
        The OCID of the compartment in which to create the routing profile.


        :return: The compartment_id of this CreateRoutingProfileDetails.
        :rtype: str
        """
        return self._compartment_id

    @compartment_id.setter
    def compartment_id(self, compartment_id):
        """
        Sets the compartment_id of this CreateRoutingProfileDetails.
        The OCID of the compartment in which to create the routing profile.


        :param compartment_id: The compartment_id of this CreateRoutingProfileDetails.
        :type: str
        """
        self._compartment_id = compartment_id

    @property
    def region_routing_policy(self):
        """
        Gets the region_routing_policy of this CreateRoutingProfileDetails.

        :return: The region_routing_policy of this CreateRoutingProfileDetails.
        :rtype: oci.generative_ai.models.RegionRoutingPolicy
        """
        return self._region_routing_policy

    @region_routing_policy.setter
    def region_routing_policy(self, region_routing_policy):
        """
        Sets the region_routing_policy of this CreateRoutingProfileDetails.

        :param region_routing_policy: The region_routing_policy of this CreateRoutingProfileDetails.
        :type: oci.generative_ai.models.RegionRoutingPolicy
        """
        self._region_routing_policy = region_routing_policy

    @property
    def model_routing_policy(self):
        """
        Gets the model_routing_policy of this CreateRoutingProfileDetails.

        :return: The model_routing_policy of this CreateRoutingProfileDetails.
        :rtype: oci.generative_ai.models.ModelRoutingPolicy
        """
        return self._model_routing_policy

    @model_routing_policy.setter
    def model_routing_policy(self, model_routing_policy):
        """
        Sets the model_routing_policy of this CreateRoutingProfileDetails.

        :param model_routing_policy: The model_routing_policy of this CreateRoutingProfileDetails.
        :type: oci.generative_ai.models.ModelRoutingPolicy
        """
        self._model_routing_policy = model_routing_policy

    @property
    def freeform_tags(self):
        """
        Gets the freeform_tags of this CreateRoutingProfileDetails.
        Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
        For more information, see `Resource Tags`__.

        Example: `{\"Department\": \"Finance\"}`

        __ https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm


        :return: The freeform_tags of this CreateRoutingProfileDetails.
        :rtype: dict(str, str)
        """
        return self._freeform_tags

    @freeform_tags.setter
    def freeform_tags(self, freeform_tags):
        """
        Sets the freeform_tags of this CreateRoutingProfileDetails.
        Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
        For more information, see `Resource Tags`__.

        Example: `{\"Department\": \"Finance\"}`

        __ https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm


        :param freeform_tags: The freeform_tags of this CreateRoutingProfileDetails.
        :type: dict(str, str)
        """
        self._freeform_tags = freeform_tags

    @property
    def defined_tags(self):
        """
        Gets the defined_tags of this CreateRoutingProfileDetails.
        Defined tags for this resource. Each key is predefined and scoped to a namespace.
        For more information, see `Resource Tags`__.

        Example: `{\"Operations\": {\"CostCenter\": \"42\"}}`

        __ https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm


        :return: The defined_tags of this CreateRoutingProfileDetails.
        :rtype: dict(str, dict(str, object))
        """
        return self._defined_tags

    @defined_tags.setter
    def defined_tags(self, defined_tags):
        """
        Sets the defined_tags of this CreateRoutingProfileDetails.
        Defined tags for this resource. Each key is predefined and scoped to a namespace.
        For more information, see `Resource Tags`__.

        Example: `{\"Operations\": {\"CostCenter\": \"42\"}}`

        __ https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm


        :param defined_tags: The defined_tags of this CreateRoutingProfileDetails.
        :type: dict(str, dict(str, object))
        """
        self._defined_tags = defined_tags

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
