# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20231130


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class ModelDiscovery(object):
    """
    Metadata describing a specific model
    """

    #: A constant which can be used with the model_access property of a ModelDiscovery.
    #: This constant has a value of "HOSTED"
    MODEL_ACCESS_HOSTED = "HOSTED"

    #: A constant which can be used with the model_access property of a ModelDiscovery.
    #: This constant has a value of "PROXY"
    MODEL_ACCESS_PROXY = "PROXY"

    def __init__(self, **kwargs):
        """
        Initializes a new ModelDiscovery object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param model_id:
            The value to assign to the model_id property of this ModelDiscovery.
        :type model_id: str

        :param vendor:
            The value to assign to the vendor property of this ModelDiscovery.
        :type vendor: str

        :param capabilities:
            The value to assign to the capabilities property of this ModelDiscovery.
        :type capabilities: list[oci.generative_ai.models.ModelCapability]

        :param api_capability:
            The value to assign to the api_capability property of this ModelDiscovery.
        :type api_capability: list[str]

        :param modality_support:
            The value to assign to the modality_support property of this ModelDiscovery.
        :type modality_support: list[oci.generative_ai.models.ModelModalitySupport]

        :param model_access:
            The value to assign to the model_access property of this ModelDiscovery.
            Allowed values for this property are: "HOSTED", "PROXY", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type model_access: str

        :param parameters:
            The value to assign to the parameters property of this ModelDiscovery.
        :type parameters: list[oci.generative_ai.models.Parameter]

        :param availability:
            The value to assign to the availability property of this ModelDiscovery.
        :type availability: list[oci.generative_ai.models.Availability]

        """
        self.swagger_types = {
            'model_id': 'str',
            'vendor': 'str',
            'capabilities': 'list[ModelCapability]',
            'api_capability': 'list[str]',
            'modality_support': 'list[ModelModalitySupport]',
            'model_access': 'str',
            'parameters': 'list[Parameter]',
            'availability': 'list[Availability]'
        }
        self.attribute_map = {
            'model_id': 'modelId',
            'vendor': 'vendor',
            'capabilities': 'capabilities',
            'api_capability': 'apiCapability',
            'modality_support': 'modalitySupport',
            'model_access': 'modelAccess',
            'parameters': 'parameters',
            'availability': 'availability'
        }
        self._model_id = None
        self._vendor = None
        self._capabilities = None
        self._api_capability = None
        self._modality_support = None
        self._model_access = None
        self._parameters = None
        self._availability = None

    @property
    def model_id(self):
        """
        **[Required]** Gets the model_id of this ModelDiscovery.
        A unique identifier for the model


        :return: The model_id of this ModelDiscovery.
        :rtype: str
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id):
        """
        Sets the model_id of this ModelDiscovery.
        A unique identifier for the model


        :param model_id: The model_id of this ModelDiscovery.
        :type: str
        """
        self._model_id = model_id

    @property
    def vendor(self):
        """
        **[Required]** Gets the vendor of this ModelDiscovery.
        The vendor that offers the model.


        :return: The vendor of this ModelDiscovery.
        :rtype: str
        """
        return self._vendor

    @vendor.setter
    def vendor(self, vendor):
        """
        Sets the vendor of this ModelDiscovery.
        The vendor that offers the model.


        :param vendor: The vendor of this ModelDiscovery.
        :type: str
        """
        self._vendor = vendor

    @property
    def capabilities(self):
        """
        **[Required]** Gets the capabilities of this ModelDiscovery.
        Describes what this model can be used for.


        :return: The capabilities of this ModelDiscovery.
        :rtype: list[oci.generative_ai.models.ModelCapability]
        """
        return self._capabilities

    @capabilities.setter
    def capabilities(self, capabilities):
        """
        Sets the capabilities of this ModelDiscovery.
        Describes what this model can be used for.


        :param capabilities: The capabilities of this ModelDiscovery.
        :type: list[oci.generative_ai.models.ModelCapability]
        """
        self._capabilities = capabilities

    @property
    def api_capability(self):
        """
        Gets the api_capability of this ModelDiscovery.
        The specific API endpoints that this model supports. For example, a chat model may support OPENAI_V1_CHAT_COMPLETIONS and/or OPENAI_V1_RESPONSES. If empty, the model has not yet been annotated with API capabilities.


        :return: The api_capability of this ModelDiscovery.
        :rtype: list[str]
        """
        return self._api_capability

    @api_capability.setter
    def api_capability(self, api_capability):
        """
        Sets the api_capability of this ModelDiscovery.
        The specific API endpoints that this model supports. For example, a chat model may support OPENAI_V1_CHAT_COMPLETIONS and/or OPENAI_V1_RESPONSES. If empty, the model has not yet been annotated with API capabilities.


        :param api_capability: The api_capability of this ModelDiscovery.
        :type: list[str]
        """
        self._api_capability = api_capability

    @property
    def modality_support(self):
        """
        Gets the modality_support of this ModelDiscovery.
        The supported input-to-output modality transformations for this model. For example, a model can support
        TEXT to VIDEO or AUDIO to VIDEO.


        :return: The modality_support of this ModelDiscovery.
        :rtype: list[oci.generative_ai.models.ModelModalitySupport]
        """
        return self._modality_support

    @modality_support.setter
    def modality_support(self, modality_support):
        """
        Sets the modality_support of this ModelDiscovery.
        The supported input-to-output modality transformations for this model. For example, a model can support
        TEXT to VIDEO or AUDIO to VIDEO.


        :param modality_support: The modality_support of this ModelDiscovery.
        :type: list[oci.generative_ai.models.ModelModalitySupport]
        """
        self._modality_support = modality_support

    @property
    def model_access(self):
        """
        Gets the model_access of this ModelDiscovery.
        The access level required to use the model, which can be either HOSTED (the model is hosted by the provider and can be accessed via API calls) or PROXY (the model is not directly accessible and requires going through a proxy).

        Allowed values for this property are: "HOSTED", "PROXY", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The model_access of this ModelDiscovery.
        :rtype: str
        """
        return self._model_access

    @model_access.setter
    def model_access(self, model_access):
        """
        Sets the model_access of this ModelDiscovery.
        The access level required to use the model, which can be either HOSTED (the model is hosted by the provider and can be accessed via API calls) or PROXY (the model is not directly accessible and requires going through a proxy).


        :param model_access: The model_access of this ModelDiscovery.
        :type: str
        """
        allowed_values = ["HOSTED", "PROXY"]
        if not value_allowed_none_or_none_sentinel(model_access, allowed_values):
            model_access = 'UNKNOWN_ENUM_VALUE'
        self._model_access = model_access

    @property
    def parameters(self):
        """
        Gets the parameters of this ModelDiscovery.
        The list of configurable parameters supported by the model. For example, temperature and max_tokens for a text generation model.


        :return: The parameters of this ModelDiscovery.
        :rtype: list[oci.generative_ai.models.Parameter]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """
        Sets the parameters of this ModelDiscovery.
        The list of configurable parameters supported by the model. For example, temperature and max_tokens for a text generation model.


        :param parameters: The parameters of this ModelDiscovery.
        :type: list[oci.generative_ai.models.Parameter]
        """
        self._parameters = parameters

    @property
    def availability(self):
        """
        Gets the availability of this ModelDiscovery.
        The list of availability details for the model across different regions and deployment modes.


        :return: The availability of this ModelDiscovery.
        :rtype: list[oci.generative_ai.models.Availability]
        """
        return self._availability

    @availability.setter
    def availability(self, availability):
        """
        Sets the availability of this ModelDiscovery.
        The list of availability details for the model across different regions and deployment modes.


        :param availability: The availability of this ModelDiscovery.
        :type: list[oci.generative_ai.models.Availability]
        """
        self._availability = availability

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
