# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20231130


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class RegionRoutingPolicy(object):
    """
    The cross-region routing policy for the routing profile. If this policy is not specified, only the local region is allowed.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new RegionRoutingPolicy object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param allowed_regions:
            The value to assign to the allowed_regions property of this RegionRoutingPolicy.
        :type allowed_regions: list[str]

        """
        self.swagger_types = {
            'allowed_regions': 'list[str]'
        }
        self.attribute_map = {
            'allowed_regions': 'allowedRegions'
        }
        self._allowed_regions = None

    @property
    def allowed_regions(self):
        """
        Gets the allowed_regions of this RegionRoutingPolicy.
        The ordered list of regions that routing is allowed to reach. Each entry is a region identifier (for example, `us-chicago-1`).

        The order of entries is preserved. Duplicate entries are not allowed.


        :return: The allowed_regions of this RegionRoutingPolicy.
        :rtype: list[str]
        """
        return self._allowed_regions

    @allowed_regions.setter
    def allowed_regions(self, allowed_regions):
        """
        Sets the allowed_regions of this RegionRoutingPolicy.
        The ordered list of regions that routing is allowed to reach. Each entry is a region identifier (for example, `us-chicago-1`).

        The order of entries is preserved. Duplicate entries are not allowed.


        :param allowed_regions: The allowed_regions of this RegionRoutingPolicy.
        :type: list[str]
        """
        self._allowed_regions = allowed_regions

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
