# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20260101


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel, to_dict, redact_password_field  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CreateDistributedDatabaseCatalogDatabaseDetails(object):
    """
    Details for creating a distributed database catalog.
    """

    #: A constant which can be used with the source property of a CreateDistributedDatabaseCatalogDatabaseDetails.
    #: This constant has a value of "XS_EXISTING_CLUSTER"
    SOURCE_XS_EXISTING_CLUSTER = "XS_EXISTING_CLUSTER"

    #: A constant which can be used with the source property of a CreateDistributedDatabaseCatalogDatabaseDetails.
    #: This constant has a value of "XS_NEW_CLUSTER"
    SOURCE_XS_NEW_CLUSTER = "XS_NEW_CLUSTER"

    #: A constant which can be used with the source property of a CreateDistributedDatabaseCatalogDatabaseDetails.
    #: This constant has a value of "XS_NEW_VAULT_AND_CLUSTER"
    SOURCE_XS_NEW_VAULT_AND_CLUSTER = "XS_NEW_VAULT_AND_CLUSTER"

    #: A constant which can be used with the source property of a CreateDistributedDatabaseCatalogDatabaseDetails.
    #: This constant has a value of "XD_EXISTING_CLUSTER"
    SOURCE_XD_EXISTING_CLUSTER = "XD_EXISTING_CLUSTER"

    #: A constant which can be used with the source property of a CreateDistributedDatabaseCatalogDatabaseDetails.
    #: This constant has a value of "EXISTING_DB_HOME"
    SOURCE_EXISTING_DB_HOME = "EXISTING_DB_HOME"

    def __init__(self, **kwargs):
        """
        Initializes a new CreateDistributedDatabaseCatalogDatabaseDetails object with values from keyword arguments. This class has the following subclasses and if you are using this class as input
        to a service operations then you should favor using a subclass over the base class:

        * :class:`~oci.distributed_database.models.CreateDistributedDatabaseCatalogWithExadbXsNewVaultAndClusterDetails`
        * :class:`~oci.distributed_database.models.CreateDistributedDatabaseCatalogDatabaseWithDbHomeDetails`
        * :class:`~oci.distributed_database.models.CreateDistributedDatabaseCatalogDatabaseWithExadbXsDetails`
        * :class:`~oci.distributed_database.models.CreateDistributedDatabaseCatalogDatabaseWithExadbXdDetails`
        * :class:`~oci.distributed_database.models.CreateDistributedDatabaseCatalogWithExadbXsNewClusterDetails`

        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param source:
            The value to assign to the source property of this CreateDistributedDatabaseCatalogDatabaseDetails.
            Allowed values for this property are: "XS_EXISTING_CLUSTER", "XS_NEW_CLUSTER", "XS_NEW_VAULT_AND_CLUSTER", "XD_EXISTING_CLUSTER", "EXISTING_DB_HOME"
        :type source: str

        :param tde_wallet_password:
            The value to assign to the tde_wallet_password property of this CreateDistributedDatabaseCatalogDatabaseDetails.
        :type tde_wallet_password: str

        :param tde_wallet_password_secret_id:
            The value to assign to the tde_wallet_password_secret_id property of this CreateDistributedDatabaseCatalogDatabaseDetails.
        :type tde_wallet_password_secret_id: str

        :param tde_wallet_password_secret_version_number:
            The value to assign to the tde_wallet_password_secret_version_number property of this CreateDistributedDatabaseCatalogDatabaseDetails.
        :type tde_wallet_password_secret_version_number: int

        """
        self.swagger_types = {
            'source': 'str',
            'tde_wallet_password': 'str',
            'tde_wallet_password_secret_id': 'str',
            'tde_wallet_password_secret_version_number': 'int'
        }
        self.attribute_map = {
            'source': 'source',
            'tde_wallet_password': 'tdeWalletPassword',
            'tde_wallet_password_secret_id': 'tdeWalletPasswordSecretId',
            'tde_wallet_password_secret_version_number': 'tdeWalletPasswordSecretVersionNumber'
        }
        self._redacted_field_paths = [
            ['tde_wallet_password'],
        ]
        self._source = None
        self._tde_wallet_password = None
        self._tde_wallet_password_secret_id = None
        self._tde_wallet_password_secret_version_number = None

    @staticmethod
    def get_subtype(object_dictionary):
        """
        Given the hash representation of a subtype of this class,
        use the info in the hash to return the class of the subtype.
        """
        type = object_dictionary['source']

        if type == 'XS_NEW_VAULT_AND_CLUSTER':
            return 'CreateDistributedDatabaseCatalogWithExadbXsNewVaultAndClusterDetails'

        if type == 'EXISTING_DB_HOME':
            return 'CreateDistributedDatabaseCatalogDatabaseWithDbHomeDetails'

        if type == 'XS_EXISTING_CLUSTER':
            return 'CreateDistributedDatabaseCatalogDatabaseWithExadbXsDetails'

        if type == 'XD_EXISTING_CLUSTER':
            return 'CreateDistributedDatabaseCatalogDatabaseWithExadbXdDetails'

        if type == 'XS_NEW_CLUSTER':
            return 'CreateDistributedDatabaseCatalogWithExadbXsNewClusterDetails'
        else:
            return 'CreateDistributedDatabaseCatalogDatabaseDetails'

    @property
    def source(self):
        """
        **[Required]** Gets the source of this CreateDistributedDatabaseCatalogDatabaseDetails.
        The source of the Globally distributed database type.
        Use XS_EXISTING_CLUSTER for a database on Exascale Infrastructure that uses a pre-existing cluster.
        Use XS_NEW_CLUSTER for a database on Exascale Infrastructure that requires a new cluster created from scratch.
        Use XS_NEW_VAULT_AND_CLUSTER for a database on Exascale Infrastructure that requires a new vault and cluster created from scratch.
        Use XD_EXISTING_CLUSTER for a database on Dedicated Infrastructure that uses a pre-existing cluster.
        Use EXISTING_DB_HOME for a database on a pre-existing database home.

        Allowed values for this property are: "XS_EXISTING_CLUSTER", "XS_NEW_CLUSTER", "XS_NEW_VAULT_AND_CLUSTER", "XD_EXISTING_CLUSTER", "EXISTING_DB_HOME"


        :return: The source of this CreateDistributedDatabaseCatalogDatabaseDetails.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """
        Sets the source of this CreateDistributedDatabaseCatalogDatabaseDetails.
        The source of the Globally distributed database type.
        Use XS_EXISTING_CLUSTER for a database on Exascale Infrastructure that uses a pre-existing cluster.
        Use XS_NEW_CLUSTER for a database on Exascale Infrastructure that requires a new cluster created from scratch.
        Use XS_NEW_VAULT_AND_CLUSTER for a database on Exascale Infrastructure that requires a new vault and cluster created from scratch.
        Use XD_EXISTING_CLUSTER for a database on Dedicated Infrastructure that uses a pre-existing cluster.
        Use EXISTING_DB_HOME for a database on a pre-existing database home.


        :param source: The source of this CreateDistributedDatabaseCatalogDatabaseDetails.
        :type: str
        """
        allowed_values = ["XS_EXISTING_CLUSTER", "XS_NEW_CLUSTER", "XS_NEW_VAULT_AND_CLUSTER", "XD_EXISTING_CLUSTER", "EXISTING_DB_HOME"]
        if not value_allowed_none_or_none_sentinel(source, allowed_values):
            raise ValueError(
                f"Invalid value for `source`, must be None or one of {allowed_values}"
            )
        self._source = source

    @property
    def tde_wallet_password(self):
        """
        Gets the tde_wallet_password of this CreateDistributedDatabaseCatalogDatabaseDetails.
        The password to open the TDE wallet.
        The password must be 9 to 255 characters and contain at least two uppercase letters, two lowercase letters, two numeric characters, and two special characters.
        The allowed special characters are _, \\#, and -.


        :return: The tde_wallet_password of this CreateDistributedDatabaseCatalogDatabaseDetails.
        :rtype: str
        """
        return self._tde_wallet_password

    @tde_wallet_password.setter
    def tde_wallet_password(self, tde_wallet_password):
        """
        Sets the tde_wallet_password of this CreateDistributedDatabaseCatalogDatabaseDetails.
        The password to open the TDE wallet.
        The password must be 9 to 255 characters and contain at least two uppercase letters, two lowercase letters, two numeric characters, and two special characters.
        The allowed special characters are _, \\#, and -.


        :param tde_wallet_password: The tde_wallet_password of this CreateDistributedDatabaseCatalogDatabaseDetails.
        :type: str
        """
        self._tde_wallet_password = tde_wallet_password

    @property
    def tde_wallet_password_secret_id(self):
        """
        Gets the tde_wallet_password_secret_id of this CreateDistributedDatabaseCatalogDatabaseDetails.
        The `OCID`__ of the OCI vault secret. This cannot be used in conjunction with tdeWalletPassword.

        __ https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm


        :return: The tde_wallet_password_secret_id of this CreateDistributedDatabaseCatalogDatabaseDetails.
        :rtype: str
        """
        return self._tde_wallet_password_secret_id

    @tde_wallet_password_secret_id.setter
    def tde_wallet_password_secret_id(self, tde_wallet_password_secret_id):
        """
        Sets the tde_wallet_password_secret_id of this CreateDistributedDatabaseCatalogDatabaseDetails.
        The `OCID`__ of the OCI vault secret. This cannot be used in conjunction with tdeWalletPassword.

        __ https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm


        :param tde_wallet_password_secret_id: The tde_wallet_password_secret_id of this CreateDistributedDatabaseCatalogDatabaseDetails.
        :type: str
        """
        self._tde_wallet_password_secret_id = tde_wallet_password_secret_id

    @property
    def tde_wallet_password_secret_version_number(self):
        """
        Gets the tde_wallet_password_secret_version_number of this CreateDistributedDatabaseCatalogDatabaseDetails.
        The version of the vault secret. If no version is specified, the latest version will be used.


        :return: The tde_wallet_password_secret_version_number of this CreateDistributedDatabaseCatalogDatabaseDetails.
        :rtype: int
        """
        return self._tde_wallet_password_secret_version_number

    @tde_wallet_password_secret_version_number.setter
    def tde_wallet_password_secret_version_number(self, tde_wallet_password_secret_version_number):
        """
        Sets the tde_wallet_password_secret_version_number of this CreateDistributedDatabaseCatalogDatabaseDetails.
        The version of the vault secret. If no version is specified, the latest version will be used.


        :param tde_wallet_password_secret_version_number: The tde_wallet_password_secret_version_number of this CreateDistributedDatabaseCatalogDatabaseDetails.
        :type: int
        """
        self._tde_wallet_password_secret_version_number = tde_wallet_password_secret_version_number

    def __repr__(self):
        as_dict = to_dict(self)
        redact_password_field(as_dict, ['tde_wallet_password'])
        return formatted_flat_dict(as_dict)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
