# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20181201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CryptoAssessmentFindingSummary(object):
    """
    One crypto deviation finding for a specific assessment run.
    """

    #: A constant which can be used with the severity property of a CryptoAssessmentFindingSummary.
    #: This constant has a value of "CRITICAL"
    SEVERITY_CRITICAL = "CRITICAL"

    #: A constant which can be used with the severity property of a CryptoAssessmentFindingSummary.
    #: This constant has a value of "HIGH"
    SEVERITY_HIGH = "HIGH"

    #: A constant which can be used with the severity property of a CryptoAssessmentFindingSummary.
    #: This constant has a value of "MEDIUM"
    SEVERITY_MEDIUM = "MEDIUM"

    #: A constant which can be used with the severity property of a CryptoAssessmentFindingSummary.
    #: This constant has a value of "LOW"
    SEVERITY_LOW = "LOW"

    #: A constant which can be used with the status property of a CryptoAssessmentFindingSummary.
    #: This constant has a value of "PASS"
    STATUS_PASS = "PASS"

    #: A constant which can be used with the status property of a CryptoAssessmentFindingSummary.
    #: This constant has a value of "FAIL"
    STATUS_FAIL = "FAIL"

    #: A constant which can be used with the status property of a CryptoAssessmentFindingSummary.
    #: This constant has a value of "ERROR"
    STATUS_ERROR = "ERROR"

    #: A constant which can be used with the status property of a CryptoAssessmentFindingSummary.
    #: This constant has a value of "EVALUATE"
    STATUS_EVALUATE = "EVALUATE"

    #: A constant which can be used with the status property of a CryptoAssessmentFindingSummary.
    #: This constant has a value of "NOT_AVAILABLE"
    STATUS_NOT_AVAILABLE = "NOT_AVAILABLE"

    #: A constant which can be used with the status property of a CryptoAssessmentFindingSummary.
    #: This constant has a value of "NOT_APPLICABLE"
    STATUS_NOT_APPLICABLE = "NOT_APPLICABLE"

    #: A constant which can be used with the status property of a CryptoAssessmentFindingSummary.
    #: This constant has a value of "NOT_SUPPORTED"
    STATUS_NOT_SUPPORTED = "NOT_SUPPORTED"

    def __init__(self, **kwargs):
        """
        Initializes a new CryptoAssessmentFindingSummary object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param finding_key:
            The value to assign to the finding_key property of this CryptoAssessmentFindingSummary.
        :type finding_key: str

        :param title:
            The value to assign to the title property of this CryptoAssessmentFindingSummary.
        :type title: str

        :param category:
            The value to assign to the category property of this CryptoAssessmentFindingSummary.
        :type category: str

        :param priority:
            The value to assign to the priority property of this CryptoAssessmentFindingSummary.
        :type priority: int

        :param severity:
            The value to assign to the severity property of this CryptoAssessmentFindingSummary.
            Allowed values for this property are: "CRITICAL", "HIGH", "MEDIUM", "LOW", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type severity: str

        :param expected_value:
            The value to assign to the expected_value property of this CryptoAssessmentFindingSummary.
        :type expected_value: str

        :param observed_value:
            The value to assign to the observed_value property of this CryptoAssessmentFindingSummary.
        :type observed_value: list[str]

        :param recommended_value:
            The value to assign to the recommended_value property of this CryptoAssessmentFindingSummary.
        :type recommended_value: str

        :param status:
            The value to assign to the status property of this CryptoAssessmentFindingSummary.
            Allowed values for this property are: "PASS", "FAIL", "ERROR", "EVALUATE", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type status: str

        :param is_quantum_readiness_check:
            The value to assign to the is_quantum_readiness_check property of this CryptoAssessmentFindingSummary.
        :type is_quantum_readiness_check: bool

        :param summary:
            The value to assign to the summary property of this CryptoAssessmentFindingSummary.
        :type summary: str

        :param short_summary:
            The value to assign to the short_summary property of this CryptoAssessmentFindingSummary.
        :type short_summary: str

        :param url:
            The value to assign to the url property of this CryptoAssessmentFindingSummary.
        :type url: str

        :param remediation:
            The value to assign to the remediation property of this CryptoAssessmentFindingSummary.
        :type remediation: str

        :param short_remediation:
            The value to assign to the short_remediation property of this CryptoAssessmentFindingSummary.
        :type short_remediation: str

        :param compliance:
            The value to assign to the compliance property of this CryptoAssessmentFindingSummary.
        :type compliance: str

        """
        self.swagger_types = {
            'finding_key': 'str',
            'title': 'str',
            'category': 'str',
            'priority': 'int',
            'severity': 'str',
            'expected_value': 'str',
            'observed_value': 'list[str]',
            'recommended_value': 'str',
            'status': 'str',
            'is_quantum_readiness_check': 'bool',
            'summary': 'str',
            'short_summary': 'str',
            'url': 'str',
            'remediation': 'str',
            'short_remediation': 'str',
            'compliance': 'str'
        }
        self.attribute_map = {
            'finding_key': 'findingKey',
            'title': 'title',
            'category': 'category',
            'priority': 'priority',
            'severity': 'severity',
            'expected_value': 'expectedValue',
            'observed_value': 'observedValue',
            'recommended_value': 'recommendedValue',
            'status': 'status',
            'is_quantum_readiness_check': 'isQuantumReadinessCheck',
            'summary': 'summary',
            'short_summary': 'shortSummary',
            'url': 'url',
            'remediation': 'remediation',
            'short_remediation': 'shortRemediation',
            'compliance': 'compliance'
        }
        self._finding_key = None
        self._title = None
        self._category = None
        self._priority = None
        self._severity = None
        self._expected_value = None
        self._observed_value = None
        self._recommended_value = None
        self._status = None
        self._is_quantum_readiness_check = None
        self._summary = None
        self._short_summary = None
        self._url = None
        self._remediation = None
        self._short_remediation = None
        self._compliance = None

    @property
    def finding_key(self):
        """
        **[Required]** Gets the finding_key of this CryptoAssessmentFindingSummary.
        Unique key identifier for the finding.


        :return: The finding_key of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._finding_key

    @finding_key.setter
    def finding_key(self, finding_key):
        """
        Sets the finding_key of this CryptoAssessmentFindingSummary.
        Unique key identifier for the finding.


        :param finding_key: The finding_key of this CryptoAssessmentFindingSummary.
        :type: str
        """
        self._finding_key = finding_key

    @property
    def title(self):
        """
        **[Required]** Gets the title of this CryptoAssessmentFindingSummary.
        Human-readable title for the finding.


        :return: The title of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this CryptoAssessmentFindingSummary.
        Human-readable title for the finding.


        :param title: The title of this CryptoAssessmentFindingSummary.
        :type: str
        """
        self._title = title

    @property
    def category(self):
        """
        Gets the category of this CryptoAssessmentFindingSummary.
        Category value recorded for the finding.


        :return: The category of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """
        Sets the category of this CryptoAssessmentFindingSummary.
        Category value recorded for the finding.


        :param category: The category of this CryptoAssessmentFindingSummary.
        :type: str
        """
        self._category = category

    @property
    def priority(self):
        """
        Gets the priority of this CryptoAssessmentFindingSummary.
        Numeric priority of the finding. 1 is CRITICAL, 2 is HIGH, 3 is MEDIUM, and 4 is LOW.


        :return: The priority of this CryptoAssessmentFindingSummary.
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """
        Sets the priority of this CryptoAssessmentFindingSummary.
        Numeric priority of the finding. 1 is CRITICAL, 2 is HIGH, 3 is MEDIUM, and 4 is LOW.


        :param priority: The priority of this CryptoAssessmentFindingSummary.
        :type: int
        """
        self._priority = priority

    @property
    def severity(self):
        """
        Gets the severity of this CryptoAssessmentFindingSummary.
        Text severity derived from priority using the static mapping 1=CRITICAL, 2=HIGH, 3=MEDIUM, 4=LOW.

        Allowed values for this property are: "CRITICAL", "HIGH", "MEDIUM", "LOW", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The severity of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._severity

    @severity.setter
    def severity(self, severity):
        """
        Sets the severity of this CryptoAssessmentFindingSummary.
        Text severity derived from priority using the static mapping 1=CRITICAL, 2=HIGH, 3=MEDIUM, 4=LOW.


        :param severity: The severity of this CryptoAssessmentFindingSummary.
        :type: str
        """
        allowed_values = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]
        if not value_allowed_none_or_none_sentinel(severity, allowed_values):
            severity = 'UNKNOWN_ENUM_VALUE'
        self._severity = severity

    @property
    def expected_value(self):
        """
        Gets the expected_value of this CryptoAssessmentFindingSummary.
        Expected value recorded for the finding.


        :return: The expected_value of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._expected_value

    @expected_value.setter
    def expected_value(self, expected_value):
        """
        Sets the expected_value of this CryptoAssessmentFindingSummary.
        Expected value recorded for the finding.


        :param expected_value: The expected_value of this CryptoAssessmentFindingSummary.
        :type: str
        """
        self._expected_value = expected_value

    @property
    def observed_value(self):
        """
        Gets the observed_value of this CryptoAssessmentFindingSummary.
        Observed values recorded for the finding.


        :return: The observed_value of this CryptoAssessmentFindingSummary.
        :rtype: list[str]
        """
        return self._observed_value

    @observed_value.setter
    def observed_value(self, observed_value):
        """
        Sets the observed_value of this CryptoAssessmentFindingSummary.
        Observed values recorded for the finding.


        :param observed_value: The observed_value of this CryptoAssessmentFindingSummary.
        :type: list[str]
        """
        self._observed_value = observed_value

    @property
    def recommended_value(self):
        """
        Gets the recommended_value of this CryptoAssessmentFindingSummary.
        Recommended value recorded for the finding.


        :return: The recommended_value of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._recommended_value

    @recommended_value.setter
    def recommended_value(self, recommended_value):
        """
        Sets the recommended_value of this CryptoAssessmentFindingSummary.
        Recommended value recorded for the finding.


        :param recommended_value: The recommended_value of this CryptoAssessmentFindingSummary.
        :type: str
        """
        self._recommended_value = recommended_value

    @property
    def status(self):
        """
        **[Required]** Gets the status of this CryptoAssessmentFindingSummary.
        Status recorded for the finding.

        Allowed values for this property are: "PASS", "FAIL", "ERROR", "EVALUATE", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The status of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this CryptoAssessmentFindingSummary.
        Status recorded for the finding.


        :param status: The status of this CryptoAssessmentFindingSummary.
        :type: str
        """
        allowed_values = ["PASS", "FAIL", "ERROR", "EVALUATE", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(status, allowed_values):
            status = 'UNKNOWN_ENUM_VALUE'
        self._status = status

    @property
    def is_quantum_readiness_check(self):
        """
        Gets the is_quantum_readiness_check of this CryptoAssessmentFindingSummary.
        Indicates whether this finding is part of quantum-readiness checks.


        :return: The is_quantum_readiness_check of this CryptoAssessmentFindingSummary.
        :rtype: bool
        """
        return self._is_quantum_readiness_check

    @is_quantum_readiness_check.setter
    def is_quantum_readiness_check(self, is_quantum_readiness_check):
        """
        Sets the is_quantum_readiness_check of this CryptoAssessmentFindingSummary.
        Indicates whether this finding is part of quantum-readiness checks.


        :param is_quantum_readiness_check: The is_quantum_readiness_check of this CryptoAssessmentFindingSummary.
        :type: bool
        """
        self._is_quantum_readiness_check = is_quantum_readiness_check

    @property
    def summary(self):
        """
        Gets the summary of this CryptoAssessmentFindingSummary.
        Summary recorded for the finding.


        :return: The summary of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary):
        """
        Sets the summary of this CryptoAssessmentFindingSummary.
        Summary recorded for the finding.


        :param summary: The summary of this CryptoAssessmentFindingSummary.
        :type: str
        """
        self._summary = summary

    @property
    def short_summary(self):
        """
        Gets the short_summary of this CryptoAssessmentFindingSummary.
        Short summary of the finding.


        :return: The short_summary of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._short_summary

    @short_summary.setter
    def short_summary(self, short_summary):
        """
        Sets the short_summary of this CryptoAssessmentFindingSummary.
        Short summary of the finding.


        :param short_summary: The short_summary of this CryptoAssessmentFindingSummary.
        :type: str
        """
        self._short_summary = short_summary

    @property
    def url(self):
        """
        Gets the url of this CryptoAssessmentFindingSummary.
        URL recorded for the finding.


        :return: The url of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this CryptoAssessmentFindingSummary.
        URL recorded for the finding.


        :param url: The url of this CryptoAssessmentFindingSummary.
        :type: str
        """
        self._url = url

    @property
    def remediation(self):
        """
        Gets the remediation of this CryptoAssessmentFindingSummary.
        Remediation text recorded for the finding.


        :return: The remediation of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._remediation

    @remediation.setter
    def remediation(self, remediation):
        """
        Sets the remediation of this CryptoAssessmentFindingSummary.
        Remediation text recorded for the finding.


        :param remediation: The remediation of this CryptoAssessmentFindingSummary.
        :type: str
        """
        self._remediation = remediation

    @property
    def short_remediation(self):
        """
        Gets the short_remediation of this CryptoAssessmentFindingSummary.
        Short remediation for the finding.


        :return: The short_remediation of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._short_remediation

    @short_remediation.setter
    def short_remediation(self, short_remediation):
        """
        Sets the short_remediation of this CryptoAssessmentFindingSummary.
        Short remediation for the finding.


        :param short_remediation: The short_remediation of this CryptoAssessmentFindingSummary.
        :type: str
        """
        self._short_remediation = short_remediation

    @property
    def compliance(self):
        """
        Gets the compliance of this CryptoAssessmentFindingSummary.
        Compliance mapping recorded for the finding.


        :return: The compliance of this CryptoAssessmentFindingSummary.
        :rtype: str
        """
        return self._compliance

    @compliance.setter
    def compliance(self, compliance):
        """
        Sets the compliance of this CryptoAssessmentFindingSummary.
        Compliance mapping recorded for the finding.


        :param compliance: The compliance of this CryptoAssessmentFindingSummary.
        :type: str
        """
        self._compliance = compliance

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
