# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20181201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CryptoAssessmentCbomItemSummary(object):
    """
    One CBOM item representing a cryptographic component or configuration.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new CryptoAssessmentCbomItemSummary object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param component_type:
            The value to assign to the component_type property of this CryptoAssessmentCbomItemSummary.
        :type component_type: str

        :param feature:
            The value to assign to the feature property of this CryptoAssessmentCbomItemSummary.
        :type feature: str

        :param protocol:
            The value to assign to the protocol property of this CryptoAssessmentCbomItemSummary.
        :type protocol: str

        :param algorithm:
            The value to assign to the algorithm property of this CryptoAssessmentCbomItemSummary.
        :type algorithm: str

        :param format:
            The value to assign to the format property of this CryptoAssessmentCbomItemSummary.
        :type format: str

        :param key_size:
            The value to assign to the key_size property of this CryptoAssessmentCbomItemSummary.
        :type key_size: str

        :param configuration_location:
            The value to assign to the configuration_location property of this CryptoAssessmentCbomItemSummary.
        :type configuration_location: list[str]

        :param compliance_driver:
            The value to assign to the compliance_driver property of this CryptoAssessmentCbomItemSummary.
        :type compliance_driver: str

        """
        self.swagger_types = {
            'component_type': 'str',
            'feature': 'str',
            'protocol': 'str',
            'algorithm': 'str',
            'format': 'str',
            'key_size': 'str',
            'configuration_location': 'list[str]',
            'compliance_driver': 'str'
        }
        self.attribute_map = {
            'component_type': 'componentType',
            'feature': 'feature',
            'protocol': 'protocol',
            'algorithm': 'algorithm',
            'format': 'format',
            'key_size': 'keySize',
            'configuration_location': 'configurationLocation',
            'compliance_driver': 'complianceDriver'
        }
        self._component_type = None
        self._feature = None
        self._protocol = None
        self._algorithm = None
        self._format = None
        self._key_size = None
        self._configuration_location = None
        self._compliance_driver = None

    @property
    def component_type(self):
        """
        **[Required]** Gets the component_type of this CryptoAssessmentCbomItemSummary.
        Type of component represented in the CBOM item.


        :return: The component_type of this CryptoAssessmentCbomItemSummary.
        :rtype: str
        """
        return self._component_type

    @component_type.setter
    def component_type(self, component_type):
        """
        Sets the component_type of this CryptoAssessmentCbomItemSummary.
        Type of component represented in the CBOM item.


        :param component_type: The component_type of this CryptoAssessmentCbomItemSummary.
        :type: str
        """
        self._component_type = component_type

    @property
    def feature(self):
        """
        **[Required]** Gets the feature of this CryptoAssessmentCbomItemSummary.
        Feature name represented by the CBOM item.


        :return: The feature of this CryptoAssessmentCbomItemSummary.
        :rtype: str
        """
        return self._feature

    @feature.setter
    def feature(self, feature):
        """
        Sets the feature of this CryptoAssessmentCbomItemSummary.
        Feature name represented by the CBOM item.


        :param feature: The feature of this CryptoAssessmentCbomItemSummary.
        :type: str
        """
        self._feature = feature

    @property
    def protocol(self):
        """
        Gets the protocol of this CryptoAssessmentCbomItemSummary.
        Protocol used by the cryptographic feature.


        :return: The protocol of this CryptoAssessmentCbomItemSummary.
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """
        Sets the protocol of this CryptoAssessmentCbomItemSummary.
        Protocol used by the cryptographic feature.


        :param protocol: The protocol of this CryptoAssessmentCbomItemSummary.
        :type: str
        """
        self._protocol = protocol

    @property
    def algorithm(self):
        """
        Gets the algorithm of this CryptoAssessmentCbomItemSummary.
        Cryptographic algorithm or integrity/checksum value observed for the feature.


        :return: The algorithm of this CryptoAssessmentCbomItemSummary.
        :rtype: str
        """
        return self._algorithm

    @algorithm.setter
    def algorithm(self, algorithm):
        """
        Sets the algorithm of this CryptoAssessmentCbomItemSummary.
        Cryptographic algorithm or integrity/checksum value observed for the feature.


        :param algorithm: The algorithm of this CryptoAssessmentCbomItemSummary.
        :type: str
        """
        self._algorithm = algorithm

    @property
    def format(self):
        """
        Gets the format of this CryptoAssessmentCbomItemSummary.
        Cryptographic format used by the feature.


        :return: The format of this CryptoAssessmentCbomItemSummary.
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """
        Sets the format of this CryptoAssessmentCbomItemSummary.
        Cryptographic format used by the feature.


        :param format: The format of this CryptoAssessmentCbomItemSummary.
        :type: str
        """
        self._format = format

    @property
    def key_size(self):
        """
        Gets the key_size of this CryptoAssessmentCbomItemSummary.
        Observed key size for the feature.


        :return: The key_size of this CryptoAssessmentCbomItemSummary.
        :rtype: str
        """
        return self._key_size

    @key_size.setter
    def key_size(self, key_size):
        """
        Sets the key_size of this CryptoAssessmentCbomItemSummary.
        Observed key size for the feature.


        :param key_size: The key_size of this CryptoAssessmentCbomItemSummary.
        :type: str
        """
        self._key_size = key_size

    @property
    def configuration_location(self):
        """
        **[Required]** Gets the configuration_location of this CryptoAssessmentCbomItemSummary.
        Locations where this item is configured or stored.


        :return: The configuration_location of this CryptoAssessmentCbomItemSummary.
        :rtype: list[str]
        """
        return self._configuration_location

    @configuration_location.setter
    def configuration_location(self, configuration_location):
        """
        Sets the configuration_location of this CryptoAssessmentCbomItemSummary.
        Locations where this item is configured or stored.


        :param configuration_location: The configuration_location of this CryptoAssessmentCbomItemSummary.
        :type: list[str]
        """
        self._configuration_location = configuration_location

    @property
    def compliance_driver(self):
        """
        **[Required]** Gets the compliance_driver of this CryptoAssessmentCbomItemSummary.
        Static compliance standards applicable to the feature.


        :return: The compliance_driver of this CryptoAssessmentCbomItemSummary.
        :rtype: str
        """
        return self._compliance_driver

    @compliance_driver.setter
    def compliance_driver(self, compliance_driver):
        """
        Sets the compliance_driver of this CryptoAssessmentCbomItemSummary.
        Static compliance standards applicable to the feature.


        :param compliance_driver: The compliance_driver of this CryptoAssessmentCbomItemSummary.
        :type: str
        """
        self._compliance_driver = compliance_driver

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
