# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20181201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CryptoAssessmentCertificateSummary(object):
    """
    Summary of one certificate discovered across targets in a compartment.
    """

    #: A constant which can be used with the certificate_type property of a CryptoAssessmentCertificateSummary.
    #: This constant has a value of "SERVER"
    CERTIFICATE_TYPE_SERVER = "SERVER"

    #: A constant which can be used with the certificate_type property of a CryptoAssessmentCertificateSummary.
    #: This constant has a value of "USER"
    CERTIFICATE_TYPE_USER = "USER"

    #: A constant which can be used with the certificate_type property of a CryptoAssessmentCertificateSummary.
    #: This constant has a value of "TRUSTED"
    CERTIFICATE_TYPE_TRUSTED = "TRUSTED"

    #: A constant which can be used with the status property of a CryptoAssessmentCertificateSummary.
    #: This constant has a value of "VALID"
    STATUS_VALID = "VALID"

    #: A constant which can be used with the status property of a CryptoAssessmentCertificateSummary.
    #: This constant has a value of "EXPIRING_SOON"
    STATUS_EXPIRING_SOON = "EXPIRING_SOON"

    #: A constant which can be used with the status property of a CryptoAssessmentCertificateSummary.
    #: This constant has a value of "EXPIRED"
    STATUS_EXPIRED = "EXPIRED"

    #: A constant which can be used with the status property of a CryptoAssessmentCertificateSummary.
    #: This constant has a value of "INVALID"
    STATUS_INVALID = "INVALID"

    #: A constant which can be used with the status property of a CryptoAssessmentCertificateSummary.
    #: This constant has a value of "IN_USE"
    STATUS_IN_USE = "IN_USE"

    def __init__(self, **kwargs):
        """
        Initializes a new CryptoAssessmentCertificateSummary object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param assessment_id:
            The value to assign to the assessment_id property of this CryptoAssessmentCertificateSummary.
        :type assessment_id: str

        :param time_last_assessed:
            The value to assign to the time_last_assessed property of this CryptoAssessmentCertificateSummary.
        :type time_last_assessed: datetime

        :param assessment_type:
            The value to assign to the assessment_type property of this CryptoAssessmentCertificateSummary.
        :type assessment_type: str

        :param compartment_id:
            The value to assign to the compartment_id property of this CryptoAssessmentCertificateSummary.
        :type compartment_id: str

        :param target_id:
            The value to assign to the target_id property of this CryptoAssessmentCertificateSummary.
        :type target_id: str

        :param wallet_location:
            The value to assign to the wallet_location property of this CryptoAssessmentCertificateSummary.
        :type wallet_location: str

        :param certificate_type:
            The value to assign to the certificate_type property of this CryptoAssessmentCertificateSummary.
            Allowed values for this property are: "SERVER", "USER", "TRUSTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type certificate_type: str

        :param subject:
            The value to assign to the subject property of this CryptoAssessmentCertificateSummary.
        :type subject: str

        :param issuer:
            The value to assign to the issuer property of this CryptoAssessmentCertificateSummary.
        :type issuer: str

        :param status:
            The value to assign to the status property of this CryptoAssessmentCertificateSummary.
            Allowed values for this property are: "VALID", "EXPIRING_SOON", "EXPIRED", "INVALID", "IN_USE", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type status: str

        :param serial_number:
            The value to assign to the serial_number property of this CryptoAssessmentCertificateSummary.
        :type serial_number: str

        :param age:
            The value to assign to the age property of this CryptoAssessmentCertificateSummary.
        :type age: int

        :param time_valid_from:
            The value to assign to the time_valid_from property of this CryptoAssessmentCertificateSummary.
        :type time_valid_from: datetime

        :param time_valid_until:
            The value to assign to the time_valid_until property of this CryptoAssessmentCertificateSummary.
        :type time_valid_until: datetime

        :param expiry_bucket:
            The value to assign to the expiry_bucket property of this CryptoAssessmentCertificateSummary.
        :type expiry_bucket: str

        :param days_to_expiry:
            The value to assign to the days_to_expiry property of this CryptoAssessmentCertificateSummary.
        :type days_to_expiry: int

        :param public_key_type:
            The value to assign to the public_key_type property of this CryptoAssessmentCertificateSummary.
        :type public_key_type: str

        :param signature_algorithm:
            The value to assign to the signature_algorithm property of this CryptoAssessmentCertificateSummary.
        :type signature_algorithm: str

        """
        self.swagger_types = {
            'assessment_id': 'str',
            'time_last_assessed': 'datetime',
            'assessment_type': 'str',
            'compartment_id': 'str',
            'target_id': 'str',
            'wallet_location': 'str',
            'certificate_type': 'str',
            'subject': 'str',
            'issuer': 'str',
            'status': 'str',
            'serial_number': 'str',
            'age': 'int',
            'time_valid_from': 'datetime',
            'time_valid_until': 'datetime',
            'expiry_bucket': 'str',
            'days_to_expiry': 'int',
            'public_key_type': 'str',
            'signature_algorithm': 'str'
        }
        self.attribute_map = {
            'assessment_id': 'assessmentId',
            'time_last_assessed': 'timeLastAssessed',
            'assessment_type': 'assessmentType',
            'compartment_id': 'compartmentId',
            'target_id': 'targetId',
            'wallet_location': 'walletLocation',
            'certificate_type': 'certificateType',
            'subject': 'subject',
            'issuer': 'issuer',
            'status': 'status',
            'serial_number': 'serialNumber',
            'age': 'age',
            'time_valid_from': 'timeValidFrom',
            'time_valid_until': 'timeValidUntil',
            'expiry_bucket': 'expiryBucket',
            'days_to_expiry': 'daysToExpiry',
            'public_key_type': 'publicKeyType',
            'signature_algorithm': 'signatureAlgorithm'
        }
        self._assessment_id = None
        self._time_last_assessed = None
        self._assessment_type = None
        self._compartment_id = None
        self._target_id = None
        self._wallet_location = None
        self._certificate_type = None
        self._subject = None
        self._issuer = None
        self._status = None
        self._serial_number = None
        self._age = None
        self._time_valid_from = None
        self._time_valid_until = None
        self._expiry_bucket = None
        self._days_to_expiry = None
        self._public_key_type = None
        self._signature_algorithm = None

    @property
    def assessment_id(self):
        """
        **[Required]** Gets the assessment_id of this CryptoAssessmentCertificateSummary.
        OCID of the crypto assessment that discovered the certificate.


        :return: The assessment_id of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._assessment_id

    @assessment_id.setter
    def assessment_id(self, assessment_id):
        """
        Sets the assessment_id of this CryptoAssessmentCertificateSummary.
        OCID of the crypto assessment that discovered the certificate.


        :param assessment_id: The assessment_id of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        self._assessment_id = assessment_id

    @property
    def time_last_assessed(self):
        """
        Gets the time_last_assessed of this CryptoAssessmentCertificateSummary.
        The date and time the associated crypto assessment was last assessed, in RFC3339 format.


        :return: The time_last_assessed of this CryptoAssessmentCertificateSummary.
        :rtype: datetime
        """
        return self._time_last_assessed

    @time_last_assessed.setter
    def time_last_assessed(self, time_last_assessed):
        """
        Sets the time_last_assessed of this CryptoAssessmentCertificateSummary.
        The date and time the associated crypto assessment was last assessed, in RFC3339 format.


        :param time_last_assessed: The time_last_assessed of this CryptoAssessmentCertificateSummary.
        :type: datetime
        """
        self._time_last_assessed = time_last_assessed

    @property
    def assessment_type(self):
        """
        **[Required]** Gets the assessment_type of this CryptoAssessmentCertificateSummary.
        Type of the crypto assessment that discovered the certificate.


        :return: The assessment_type of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._assessment_type

    @assessment_type.setter
    def assessment_type(self, assessment_type):
        """
        Sets the assessment_type of this CryptoAssessmentCertificateSummary.
        Type of the crypto assessment that discovered the certificate.


        :param assessment_type: The assessment_type of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        self._assessment_type = assessment_type

    @property
    def compartment_id(self):
        """
        **[Required]** Gets the compartment_id of this CryptoAssessmentCertificateSummary.
        OCID of the compartment that contains the certificate row.


        :return: The compartment_id of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._compartment_id

    @compartment_id.setter
    def compartment_id(self, compartment_id):
        """
        Sets the compartment_id of this CryptoAssessmentCertificateSummary.
        OCID of the compartment that contains the certificate row.


        :param compartment_id: The compartment_id of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        self._compartment_id = compartment_id

    @property
    def target_id(self):
        """
        **[Required]** Gets the target_id of this CryptoAssessmentCertificateSummary.
        OCID of the target database associated with the certificate.


        :return: The target_id of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id):
        """
        Sets the target_id of this CryptoAssessmentCertificateSummary.
        OCID of the target database associated with the certificate.


        :param target_id: The target_id of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        self._target_id = target_id

    @property
    def wallet_location(self):
        """
        Gets the wallet_location of this CryptoAssessmentCertificateSummary.
        Wallet location where the certificate was discovered, if available.


        :return: The wallet_location of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._wallet_location

    @wallet_location.setter
    def wallet_location(self, wallet_location):
        """
        Sets the wallet_location of this CryptoAssessmentCertificateSummary.
        Wallet location where the certificate was discovered, if available.


        :param wallet_location: The wallet_location of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        self._wallet_location = wallet_location

    @property
    def certificate_type(self):
        """
        **[Required]** Gets the certificate_type of this CryptoAssessmentCertificateSummary.
        Type of certificate.

        Allowed values for this property are: "SERVER", "USER", "TRUSTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The certificate_type of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._certificate_type

    @certificate_type.setter
    def certificate_type(self, certificate_type):
        """
        Sets the certificate_type of this CryptoAssessmentCertificateSummary.
        Type of certificate.


        :param certificate_type: The certificate_type of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        allowed_values = ["SERVER", "USER", "TRUSTED"]
        if not value_allowed_none_or_none_sentinel(certificate_type, allowed_values):
            certificate_type = 'UNKNOWN_ENUM_VALUE'
        self._certificate_type = certificate_type

    @property
    def subject(self):
        """
        **[Required]** Gets the subject of this CryptoAssessmentCertificateSummary.
        Subject of the certificate.


        :return: The subject of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """
        Sets the subject of this CryptoAssessmentCertificateSummary.
        Subject of the certificate.


        :param subject: The subject of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        self._subject = subject

    @property
    def issuer(self):
        """
        **[Required]** Gets the issuer of this CryptoAssessmentCertificateSummary.
        Issuer of the certificate.


        :return: The issuer of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._issuer

    @issuer.setter
    def issuer(self, issuer):
        """
        Sets the issuer of this CryptoAssessmentCertificateSummary.
        Issuer of the certificate.


        :param issuer: The issuer of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        self._issuer = issuer

    @property
    def status(self):
        """
        **[Required]** Gets the status of this CryptoAssessmentCertificateSummary.
        Certificate validity status.

        Allowed values for this property are: "VALID", "EXPIRING_SOON", "EXPIRED", "INVALID", "IN_USE", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The status of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this CryptoAssessmentCertificateSummary.
        Certificate validity status.


        :param status: The status of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        allowed_values = ["VALID", "EXPIRING_SOON", "EXPIRED", "INVALID", "IN_USE"]
        if not value_allowed_none_or_none_sentinel(status, allowed_values):
            status = 'UNKNOWN_ENUM_VALUE'
        self._status = status

    @property
    def serial_number(self):
        """
        **[Required]** Gets the serial_number of this CryptoAssessmentCertificateSummary.
        Certificate serial number.


        :return: The serial_number of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """
        Sets the serial_number of this CryptoAssessmentCertificateSummary.
        Certificate serial number.


        :param serial_number: The serial_number of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        self._serial_number = serial_number

    @property
    def age(self):
        """
        Gets the age of this CryptoAssessmentCertificateSummary.
        Age of the certificate in whole days, calculated from timeValidFrom using the current UTC date.


        :return: The age of this CryptoAssessmentCertificateSummary.
        :rtype: int
        """
        return self._age

    @age.setter
    def age(self, age):
        """
        Sets the age of this CryptoAssessmentCertificateSummary.
        Age of the certificate in whole days, calculated from timeValidFrom using the current UTC date.


        :param age: The age of this CryptoAssessmentCertificateSummary.
        :type: int
        """
        self._age = age

    @property
    def time_valid_from(self):
        """
        **[Required]** Gets the time_valid_from of this CryptoAssessmentCertificateSummary.
        Certificate validity start time in RFC3339 format.


        :return: The time_valid_from of this CryptoAssessmentCertificateSummary.
        :rtype: datetime
        """
        return self._time_valid_from

    @time_valid_from.setter
    def time_valid_from(self, time_valid_from):
        """
        Sets the time_valid_from of this CryptoAssessmentCertificateSummary.
        Certificate validity start time in RFC3339 format.


        :param time_valid_from: The time_valid_from of this CryptoAssessmentCertificateSummary.
        :type: datetime
        """
        self._time_valid_from = time_valid_from

    @property
    def time_valid_until(self):
        """
        **[Required]** Gets the time_valid_until of this CryptoAssessmentCertificateSummary.
        Certificate validity end time in RFC3339 format.


        :return: The time_valid_until of this CryptoAssessmentCertificateSummary.
        :rtype: datetime
        """
        return self._time_valid_until

    @time_valid_until.setter
    def time_valid_until(self, time_valid_until):
        """
        Sets the time_valid_until of this CryptoAssessmentCertificateSummary.
        Certificate validity end time in RFC3339 format.


        :param time_valid_until: The time_valid_until of this CryptoAssessmentCertificateSummary.
        :type: datetime
        """
        self._time_valid_until = time_valid_until

    @property
    def expiry_bucket(self):
        """
        Gets the expiry_bucket of this CryptoAssessmentCertificateSummary.
        Expiry bucket populated for the certificate when the assessment runs. Supported values are 0_15, 15_30, 30_60, 60_90, and 90_PLUS.


        :return: The expiry_bucket of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._expiry_bucket

    @expiry_bucket.setter
    def expiry_bucket(self, expiry_bucket):
        """
        Sets the expiry_bucket of this CryptoAssessmentCertificateSummary.
        Expiry bucket populated for the certificate when the assessment runs. Supported values are 0_15, 15_30, 30_60, 60_90, and 90_PLUS.


        :param expiry_bucket: The expiry_bucket of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        self._expiry_bucket = expiry_bucket

    @property
    def days_to_expiry(self):
        """
        Gets the days_to_expiry of this CryptoAssessmentCertificateSummary.
        Number of whole days until certificate expiration, calculated from timeValidUntil. Negative values indicate already expired certificates.


        :return: The days_to_expiry of this CryptoAssessmentCertificateSummary.
        :rtype: int
        """
        return self._days_to_expiry

    @days_to_expiry.setter
    def days_to_expiry(self, days_to_expiry):
        """
        Sets the days_to_expiry of this CryptoAssessmentCertificateSummary.
        Number of whole days until certificate expiration, calculated from timeValidUntil. Negative values indicate already expired certificates.


        :param days_to_expiry: The days_to_expiry of this CryptoAssessmentCertificateSummary.
        :type: int
        """
        self._days_to_expiry = days_to_expiry

    @property
    def public_key_type(self):
        """
        **[Required]** Gets the public_key_type of this CryptoAssessmentCertificateSummary.
        Public key type and size.


        :return: The public_key_type of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._public_key_type

    @public_key_type.setter
    def public_key_type(self, public_key_type):
        """
        Sets the public_key_type of this CryptoAssessmentCertificateSummary.
        Public key type and size.


        :param public_key_type: The public_key_type of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        self._public_key_type = public_key_type

    @property
    def signature_algorithm(self):
        """
        **[Required]** Gets the signature_algorithm of this CryptoAssessmentCertificateSummary.
        Signature algorithm used by the certificate.


        :return: The signature_algorithm of this CryptoAssessmentCertificateSummary.
        :rtype: str
        """
        return self._signature_algorithm

    @signature_algorithm.setter
    def signature_algorithm(self, signature_algorithm):
        """
        Sets the signature_algorithm of this CryptoAssessmentCertificateSummary.
        Signature algorithm used by the certificate.


        :param signature_algorithm: The signature_algorithm of this CryptoAssessmentCertificateSummary.
        :type: str
        """
        self._signature_algorithm = signature_algorithm

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
