# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20181201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CryptoTlsPosture(object):
    """
    TLS posture details.
    """

    #: A constant which can be used with the status property of a CryptoTlsPosture.
    #: This constant has a value of "ENABLED"
    STATUS_ENABLED = "ENABLED"

    #: A constant which can be used with the status property of a CryptoTlsPosture.
    #: This constant has a value of "DISABLED"
    STATUS_DISABLED = "DISABLED"

    #: A constant which can be used with the status property of a CryptoTlsPosture.
    #: This constant has a value of "NOT_CONFIGURED"
    STATUS_NOT_CONFIGURED = "NOT_CONFIGURED"

    #: A constant which can be used with the status property of a CryptoTlsPosture.
    #: This constant has a value of "NOT_AVAILABLE"
    STATUS_NOT_AVAILABLE = "NOT_AVAILABLE"

    #: A constant which can be used with the status property of a CryptoTlsPosture.
    #: This constant has a value of "NOT_APPLICABLE"
    STATUS_NOT_APPLICABLE = "NOT_APPLICABLE"

    #: A constant which can be used with the status property of a CryptoTlsPosture.
    #: This constant has a value of "NOT_SUPPORTED"
    STATUS_NOT_SUPPORTED = "NOT_SUPPORTED"

    #: A constant which can be used with the are_weak_cipher_suites_allowed property of a CryptoTlsPosture.
    #: This constant has a value of "TRUE"
    ARE_WEAK_CIPHER_SUITES_ALLOWED_TRUE = "TRUE"

    #: A constant which can be used with the are_weak_cipher_suites_allowed property of a CryptoTlsPosture.
    #: This constant has a value of "FALSE"
    ARE_WEAK_CIPHER_SUITES_ALLOWED_FALSE = "FALSE"

    #: A constant which can be used with the are_weak_cipher_suites_allowed property of a CryptoTlsPosture.
    #: This constant has a value of "NOT_SUPPORTED"
    ARE_WEAK_CIPHER_SUITES_ALLOWED_NOT_SUPPORTED = "NOT_SUPPORTED"

    #: A constant which can be used with the is_mtls_configured property of a CryptoTlsPosture.
    #: This constant has a value of "TRUE"
    IS_MTLS_CONFIGURED_TRUE = "TRUE"

    #: A constant which can be used with the is_mtls_configured property of a CryptoTlsPosture.
    #: This constant has a value of "FALSE"
    IS_MTLS_CONFIGURED_FALSE = "FALSE"

    #: A constant which can be used with the is_mtls_configured property of a CryptoTlsPosture.
    #: This constant has a value of "NOT_SUPPORTED"
    IS_MTLS_CONFIGURED_NOT_SUPPORTED = "NOT_SUPPORTED"

    #: A constant which can be used with the quantum_readiness property of a CryptoTlsPosture.
    #: This constant has a value of "RESISTANT"
    QUANTUM_READINESS_RESISTANT = "RESISTANT"

    #: A constant which can be used with the quantum_readiness property of a CryptoTlsPosture.
    #: This constant has a value of "NOT_RESISTANT"
    QUANTUM_READINESS_NOT_RESISTANT = "NOT_RESISTANT"

    #: A constant which can be used with the quantum_readiness property of a CryptoTlsPosture.
    #: This constant has a value of "NOT_AVAILABLE"
    QUANTUM_READINESS_NOT_AVAILABLE = "NOT_AVAILABLE"

    #: A constant which can be used with the quantum_readiness property of a CryptoTlsPosture.
    #: This constant has a value of "NOT_APPLICABLE"
    QUANTUM_READINESS_NOT_APPLICABLE = "NOT_APPLICABLE"

    #: A constant which can be used with the quantum_readiness property of a CryptoTlsPosture.
    #: This constant has a value of "NOT_SUPPORTED"
    QUANTUM_READINESS_NOT_SUPPORTED = "NOT_SUPPORTED"

    def __init__(self, **kwargs):
        """
        Initializes a new CryptoTlsPosture object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param status:
            The value to assign to the status property of this CryptoTlsPosture.
            Allowed values for this property are: "ENABLED", "DISABLED", "NOT_CONFIGURED", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type status: str

        :param versions:
            The value to assign to the versions property of this CryptoTlsPosture.
        :type versions: list[str]

        :param cipher_suites_configured:
            The value to assign to the cipher_suites_configured property of this CryptoTlsPosture.
        :type cipher_suites_configured: list[str]

        :param are_weak_cipher_suites_allowed:
            The value to assign to the are_weak_cipher_suites_allowed property of this CryptoTlsPosture.
            Allowed values for this property are: "TRUE", "FALSE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type are_weak_cipher_suites_allowed: str

        :param is_mtls_configured:
            The value to assign to the is_mtls_configured property of this CryptoTlsPosture.
            Allowed values for this property are: "TRUE", "FALSE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type is_mtls_configured: str

        :param revocation_mode:
            The value to assign to the revocation_mode property of this CryptoTlsPosture.
        :type revocation_mode: str

        :param fips_mode_configured:
            The value to assign to the fips_mode_configured property of this CryptoTlsPosture.
        :type fips_mode_configured: str

        :param wallet_location:
            The value to assign to the wallet_location property of this CryptoTlsPosture.
        :type wallet_location: str

        :param quantum_readiness:
            The value to assign to the quantum_readiness property of this CryptoTlsPosture.
            Allowed values for this property are: "RESISTANT", "NOT_RESISTANT", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type quantum_readiness: str

        """
        self.swagger_types = {
            'status': 'str',
            'versions': 'list[str]',
            'cipher_suites_configured': 'list[str]',
            'are_weak_cipher_suites_allowed': 'str',
            'is_mtls_configured': 'str',
            'revocation_mode': 'str',
            'fips_mode_configured': 'str',
            'wallet_location': 'str',
            'quantum_readiness': 'str'
        }
        self.attribute_map = {
            'status': 'status',
            'versions': 'versions',
            'cipher_suites_configured': 'cipherSuitesConfigured',
            'are_weak_cipher_suites_allowed': 'areWeakCipherSuitesAllowed',
            'is_mtls_configured': 'isMtlsConfigured',
            'revocation_mode': 'revocationMode',
            'fips_mode_configured': 'fipsModeConfigured',
            'wallet_location': 'walletLocation',
            'quantum_readiness': 'quantumReadiness'
        }
        self._status = None
        self._versions = None
        self._cipher_suites_configured = None
        self._are_weak_cipher_suites_allowed = None
        self._is_mtls_configured = None
        self._revocation_mode = None
        self._fips_mode_configured = None
        self._wallet_location = None
        self._quantum_readiness = None

    @property
    def status(self):
        """
        Gets the status of this CryptoTlsPosture.
        TLS enablement status.

        Allowed values for this property are: "ENABLED", "DISABLED", "NOT_CONFIGURED", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The status of this CryptoTlsPosture.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this CryptoTlsPosture.
        TLS enablement status.


        :param status: The status of this CryptoTlsPosture.
        :type: str
        """
        allowed_values = ["ENABLED", "DISABLED", "NOT_CONFIGURED", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(status, allowed_values):
            status = 'UNKNOWN_ENUM_VALUE'
        self._status = status

    @property
    def versions(self):
        """
        Gets the versions of this CryptoTlsPosture.
        TLS versions configured on target.


        :return: The versions of this CryptoTlsPosture.
        :rtype: list[str]
        """
        return self._versions

    @versions.setter
    def versions(self, versions):
        """
        Sets the versions of this CryptoTlsPosture.
        TLS versions configured on target.


        :param versions: The versions of this CryptoTlsPosture.
        :type: list[str]
        """
        self._versions = versions

    @property
    def cipher_suites_configured(self):
        """
        Gets the cipher_suites_configured of this CryptoTlsPosture.
        TLS cipher suites configured on target.


        :return: The cipher_suites_configured of this CryptoTlsPosture.
        :rtype: list[str]
        """
        return self._cipher_suites_configured

    @cipher_suites_configured.setter
    def cipher_suites_configured(self, cipher_suites_configured):
        """
        Sets the cipher_suites_configured of this CryptoTlsPosture.
        TLS cipher suites configured on target.


        :param cipher_suites_configured: The cipher_suites_configured of this CryptoTlsPosture.
        :type: list[str]
        """
        self._cipher_suites_configured = cipher_suites_configured

    @property
    def are_weak_cipher_suites_allowed(self):
        """
        Gets the are_weak_cipher_suites_allowed of this CryptoTlsPosture.
        Indicates if weak TLS cipher suites are allowed.

        Allowed values for this property are: "TRUE", "FALSE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The are_weak_cipher_suites_allowed of this CryptoTlsPosture.
        :rtype: str
        """
        return self._are_weak_cipher_suites_allowed

    @are_weak_cipher_suites_allowed.setter
    def are_weak_cipher_suites_allowed(self, are_weak_cipher_suites_allowed):
        """
        Sets the are_weak_cipher_suites_allowed of this CryptoTlsPosture.
        Indicates if weak TLS cipher suites are allowed.


        :param are_weak_cipher_suites_allowed: The are_weak_cipher_suites_allowed of this CryptoTlsPosture.
        :type: str
        """
        allowed_values = ["TRUE", "FALSE", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(are_weak_cipher_suites_allowed, allowed_values):
            are_weak_cipher_suites_allowed = 'UNKNOWN_ENUM_VALUE'
        self._are_weak_cipher_suites_allowed = are_weak_cipher_suites_allowed

    @property
    def is_mtls_configured(self):
        """
        Gets the is_mtls_configured of this CryptoTlsPosture.
        Whether TLS client authentication is configured.

        Allowed values for this property are: "TRUE", "FALSE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The is_mtls_configured of this CryptoTlsPosture.
        :rtype: str
        """
        return self._is_mtls_configured

    @is_mtls_configured.setter
    def is_mtls_configured(self, is_mtls_configured):
        """
        Sets the is_mtls_configured of this CryptoTlsPosture.
        Whether TLS client authentication is configured.


        :param is_mtls_configured: The is_mtls_configured of this CryptoTlsPosture.
        :type: str
        """
        allowed_values = ["TRUE", "FALSE", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(is_mtls_configured, allowed_values):
            is_mtls_configured = 'UNKNOWN_ENUM_VALUE'
        self._is_mtls_configured = is_mtls_configured

    @property
    def revocation_mode(self):
        """
        Gets the revocation_mode of this CryptoTlsPosture.
        Certificate revocation checking mode.


        :return: The revocation_mode of this CryptoTlsPosture.
        :rtype: str
        """
        return self._revocation_mode

    @revocation_mode.setter
    def revocation_mode(self, revocation_mode):
        """
        Sets the revocation_mode of this CryptoTlsPosture.
        Certificate revocation checking mode.


        :param revocation_mode: The revocation_mode of this CryptoTlsPosture.
        :type: str
        """
        self._revocation_mode = revocation_mode

    @property
    def fips_mode_configured(self):
        """
        Gets the fips_mode_configured of this CryptoTlsPosture.
        FIPS mode configured for TLS when the target uses legacy per-feature FIPS configuration.


        :return: The fips_mode_configured of this CryptoTlsPosture.
        :rtype: str
        """
        return self._fips_mode_configured

    @fips_mode_configured.setter
    def fips_mode_configured(self, fips_mode_configured):
        """
        Sets the fips_mode_configured of this CryptoTlsPosture.
        FIPS mode configured for TLS when the target uses legacy per-feature FIPS configuration.


        :param fips_mode_configured: The fips_mode_configured of this CryptoTlsPosture.
        :type: str
        """
        self._fips_mode_configured = fips_mode_configured

    @property
    def wallet_location(self):
        """
        Gets the wallet_location of this CryptoTlsPosture.
        TLS wallet location observed on target.


        :return: The wallet_location of this CryptoTlsPosture.
        :rtype: str
        """
        return self._wallet_location

    @wallet_location.setter
    def wallet_location(self, wallet_location):
        """
        Sets the wallet_location of this CryptoTlsPosture.
        TLS wallet location observed on target.


        :param wallet_location: The wallet_location of this CryptoTlsPosture.
        :type: str
        """
        self._wallet_location = wallet_location

    @property
    def quantum_readiness(self):
        """
        Gets the quantum_readiness of this CryptoTlsPosture.
        Quantum-readiness classification for TLS posture.

        Allowed values for this property are: "RESISTANT", "NOT_RESISTANT", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The quantum_readiness of this CryptoTlsPosture.
        :rtype: str
        """
        return self._quantum_readiness

    @quantum_readiness.setter
    def quantum_readiness(self, quantum_readiness):
        """
        Sets the quantum_readiness of this CryptoTlsPosture.
        Quantum-readiness classification for TLS posture.


        :param quantum_readiness: The quantum_readiness of this CryptoTlsPosture.
        :type: str
        """
        allowed_values = ["RESISTANT", "NOT_RESISTANT", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(quantum_readiness, allowed_values):
            quantum_readiness = 'UNKNOWN_ENUM_VALUE'
        self._quantum_readiness = quantum_readiness

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
