# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20181201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CryptoSqlnetParameterValue(object):
    """
    SQLNET parameter value payload.
    """

    #: A constant which can be used with the type property of a CryptoSqlnetParameterValue.
    #: This constant has a value of "TEXT"
    TYPE_TEXT = "TEXT"

    #: A constant which can be used with the type property of a CryptoSqlnetParameterValue.
    #: This constant has a value of "BOOLEAN"
    TYPE_BOOLEAN = "BOOLEAN"

    #: A constant which can be used with the type property of a CryptoSqlnetParameterValue.
    #: This constant has a value of "LIST"
    TYPE_LIST = "LIST"

    def __init__(self, **kwargs):
        """
        Initializes a new CryptoSqlnetParameterValue object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param type:
            The value to assign to the type property of this CryptoSqlnetParameterValue.
            Allowed values for this property are: "TEXT", "BOOLEAN", "LIST", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type type: str

        :param value:
            The value to assign to the value property of this CryptoSqlnetParameterValue.
        :type value: object

        """
        self.swagger_types = {
            'type': 'str',
            'value': 'object'
        }
        self.attribute_map = {
            'type': 'type',
            'value': 'value'
        }
        self._type = None
        self._value = None

    @property
    def type(self):
        """
        **[Required]** Gets the type of this CryptoSqlnetParameterValue.
        Value type of the SQLNET parameter.

        Allowed values for this property are: "TEXT", "BOOLEAN", "LIST", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The type of this CryptoSqlnetParameterValue.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this CryptoSqlnetParameterValue.
        Value type of the SQLNET parameter.


        :param type: The type of this CryptoSqlnetParameterValue.
        :type: str
        """
        allowed_values = ["TEXT", "BOOLEAN", "LIST"]
        if not value_allowed_none_or_none_sentinel(type, allowed_values):
            type = 'UNKNOWN_ENUM_VALUE'
        self._type = type

    @property
    def value(self):
        """
        **[Required]** Gets the value of this CryptoSqlnetParameterValue.
        Parsed SQLNET parameter value. TEXT returns a string, BOOLEAN returns a boolean, and LIST returns an array of strings.


        :return: The value of this CryptoSqlnetParameterValue.
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this CryptoSqlnetParameterValue.
        Parsed SQLNET parameter value. TEXT returns a string, BOOLEAN returns a boolean, and LIST returns an array of strings.


        :param value: The value of this CryptoSqlnetParameterValue.
        :type: object
        """
        self._value = value

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
