# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20181201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CryptoAssessmentBackupSetSummary(object):
    """
    Summary of one backup set observed for a crypto assessment.
    """

    #: A constant which can be used with the backup_type property of a CryptoAssessmentBackupSetSummary.
    #: This constant has a value of "DATAFILE"
    BACKUP_TYPE_DATAFILE = "DATAFILE"

    #: A constant which can be used with the backup_type property of a CryptoAssessmentBackupSetSummary.
    #: This constant has a value of "ARCHIVED"
    BACKUP_TYPE_ARCHIVED = "ARCHIVED"

    #: A constant which can be used with the backup_type property of a CryptoAssessmentBackupSetSummary.
    #: This constant has a value of "INCREMENTAL"
    BACKUP_TYPE_INCREMENTAL = "INCREMENTAL"

    #: A constant which can be used with the backup_type property of a CryptoAssessmentBackupSetSummary.
    #: This constant has a value of "NOT_SUPPORTED"
    BACKUP_TYPE_NOT_SUPPORTED = "NOT_SUPPORTED"

    #: A constant which can be used with the status property of a CryptoAssessmentBackupSetSummary.
    #: This constant has a value of "AVAILABLE"
    STATUS_AVAILABLE = "AVAILABLE"

    #: A constant which can be used with the status property of a CryptoAssessmentBackupSetSummary.
    #: This constant has a value of "EXPIRED"
    STATUS_EXPIRED = "EXPIRED"

    #: A constant which can be used with the status property of a CryptoAssessmentBackupSetSummary.
    #: This constant has a value of "DELETED"
    STATUS_DELETED = "DELETED"

    #: A constant which can be used with the status property of a CryptoAssessmentBackupSetSummary.
    #: This constant has a value of "NOT_SUPPORTED"
    STATUS_NOT_SUPPORTED = "NOT_SUPPORTED"

    def __init__(self, **kwargs):
        """
        Initializes a new CryptoAssessmentBackupSetSummary object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param assessment_id:
            The value to assign to the assessment_id property of this CryptoAssessmentBackupSetSummary.
        :type assessment_id: str

        :param time_last_assessed:
            The value to assign to the time_last_assessed property of this CryptoAssessmentBackupSetSummary.
        :type time_last_assessed: datetime

        :param target_id:
            The value to assign to the target_id property of this CryptoAssessmentBackupSetSummary.
        :type target_id: str

        :param backup_set_key:
            The value to assign to the backup_set_key property of this CryptoAssessmentBackupSetSummary.
        :type backup_set_key: str

        :param set_stamp:
            The value to assign to the set_stamp property of this CryptoAssessmentBackupSetSummary.
        :type set_stamp: str

        :param backup_type:
            The value to assign to the backup_type property of this CryptoAssessmentBackupSetSummary.
            Allowed values for this property are: "DATAFILE", "ARCHIVED", "INCREMENTAL", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type backup_type: str

        :param status:
            The value to assign to the status property of this CryptoAssessmentBackupSetSummary.
            Allowed values for this property are: "AVAILABLE", "EXPIRED", "DELETED", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type status: str

        :param backup_pieces:
            The value to assign to the backup_pieces property of this CryptoAssessmentBackupSetSummary.
        :type backup_pieces: int

        :param is_encrypted:
            The value to assign to the is_encrypted property of this CryptoAssessmentBackupSetSummary.
        :type is_encrypted: bool

        :param algorithm_observed:
            The value to assign to the algorithm_observed property of this CryptoAssessmentBackupSetSummary.
        :type algorithm_observed: str

        :param cipher_mode_observed:
            The value to assign to the cipher_mode_observed property of this CryptoAssessmentBackupSetSummary.
        :type cipher_mode_observed: str

        :param is_compressed:
            The value to assign to the is_compressed property of this CryptoAssessmentBackupSetSummary.
        :type is_compressed: bool

        :param time_created:
            The value to assign to the time_created property of this CryptoAssessmentBackupSetSummary.
        :type time_created: datetime

        :param size_in_gbs:
            The value to assign to the size_in_gbs property of this CryptoAssessmentBackupSetSummary.
        :type size_in_gbs: float

        """
        self.swagger_types = {
            'assessment_id': 'str',
            'time_last_assessed': 'datetime',
            'target_id': 'str',
            'backup_set_key': 'str',
            'set_stamp': 'str',
            'backup_type': 'str',
            'status': 'str',
            'backup_pieces': 'int',
            'is_encrypted': 'bool',
            'algorithm_observed': 'str',
            'cipher_mode_observed': 'str',
            'is_compressed': 'bool',
            'time_created': 'datetime',
            'size_in_gbs': 'float'
        }
        self.attribute_map = {
            'assessment_id': 'assessmentId',
            'time_last_assessed': 'timeLastAssessed',
            'target_id': 'targetId',
            'backup_set_key': 'backupSetKey',
            'set_stamp': 'setStamp',
            'backup_type': 'backupType',
            'status': 'status',
            'backup_pieces': 'backupPieces',
            'is_encrypted': 'isEncrypted',
            'algorithm_observed': 'algorithmObserved',
            'cipher_mode_observed': 'cipherModeObserved',
            'is_compressed': 'isCompressed',
            'time_created': 'timeCreated',
            'size_in_gbs': 'sizeInGBs'
        }
        self._assessment_id = None
        self._time_last_assessed = None
        self._target_id = None
        self._backup_set_key = None
        self._set_stamp = None
        self._backup_type = None
        self._status = None
        self._backup_pieces = None
        self._is_encrypted = None
        self._algorithm_observed = None
        self._cipher_mode_observed = None
        self._is_compressed = None
        self._time_created = None
        self._size_in_gbs = None

    @property
    def assessment_id(self):
        """
        **[Required]** Gets the assessment_id of this CryptoAssessmentBackupSetSummary.
        OCID of the crypto assessment that discovered the backup set.


        :return: The assessment_id of this CryptoAssessmentBackupSetSummary.
        :rtype: str
        """
        return self._assessment_id

    @assessment_id.setter
    def assessment_id(self, assessment_id):
        """
        Sets the assessment_id of this CryptoAssessmentBackupSetSummary.
        OCID of the crypto assessment that discovered the backup set.


        :param assessment_id: The assessment_id of this CryptoAssessmentBackupSetSummary.
        :type: str
        """
        self._assessment_id = assessment_id

    @property
    def time_last_assessed(self):
        """
        Gets the time_last_assessed of this CryptoAssessmentBackupSetSummary.
        The date and time the associated crypto assessment was last assessed, in RFC3339 format.


        :return: The time_last_assessed of this CryptoAssessmentBackupSetSummary.
        :rtype: datetime
        """
        return self._time_last_assessed

    @time_last_assessed.setter
    def time_last_assessed(self, time_last_assessed):
        """
        Sets the time_last_assessed of this CryptoAssessmentBackupSetSummary.
        The date and time the associated crypto assessment was last assessed, in RFC3339 format.


        :param time_last_assessed: The time_last_assessed of this CryptoAssessmentBackupSetSummary.
        :type: datetime
        """
        self._time_last_assessed = time_last_assessed

    @property
    def target_id(self):
        """
        **[Required]** Gets the target_id of this CryptoAssessmentBackupSetSummary.
        OCID of the target database associated with the backup set.


        :return: The target_id of this CryptoAssessmentBackupSetSummary.
        :rtype: str
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id):
        """
        Sets the target_id of this CryptoAssessmentBackupSetSummary.
        OCID of the target database associated with the backup set.


        :param target_id: The target_id of this CryptoAssessmentBackupSetSummary.
        :type: str
        """
        self._target_id = target_id

    @property
    def backup_set_key(self):
        """
        **[Required]** Gets the backup_set_key of this CryptoAssessmentBackupSetSummary.
        Backup set key.


        :return: The backup_set_key of this CryptoAssessmentBackupSetSummary.
        :rtype: str
        """
        return self._backup_set_key

    @backup_set_key.setter
    def backup_set_key(self, backup_set_key):
        """
        Sets the backup_set_key of this CryptoAssessmentBackupSetSummary.
        Backup set key.


        :param backup_set_key: The backup_set_key of this CryptoAssessmentBackupSetSummary.
        :type: str
        """
        self._backup_set_key = backup_set_key

    @property
    def set_stamp(self):
        """
        **[Required]** Gets the set_stamp of this CryptoAssessmentBackupSetSummary.
        Backup set stamp.


        :return: The set_stamp of this CryptoAssessmentBackupSetSummary.
        :rtype: str
        """
        return self._set_stamp

    @set_stamp.setter
    def set_stamp(self, set_stamp):
        """
        Sets the set_stamp of this CryptoAssessmentBackupSetSummary.
        Backup set stamp.


        :param set_stamp: The set_stamp of this CryptoAssessmentBackupSetSummary.
        :type: str
        """
        self._set_stamp = set_stamp

    @property
    def backup_type(self):
        """
        **[Required]** Gets the backup_type of this CryptoAssessmentBackupSetSummary.
        Backup type observed for the set.

        Allowed values for this property are: "DATAFILE", "ARCHIVED", "INCREMENTAL", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The backup_type of this CryptoAssessmentBackupSetSummary.
        :rtype: str
        """
        return self._backup_type

    @backup_type.setter
    def backup_type(self, backup_type):
        """
        Sets the backup_type of this CryptoAssessmentBackupSetSummary.
        Backup type observed for the set.


        :param backup_type: The backup_type of this CryptoAssessmentBackupSetSummary.
        :type: str
        """
        allowed_values = ["DATAFILE", "ARCHIVED", "INCREMENTAL", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(backup_type, allowed_values):
            backup_type = 'UNKNOWN_ENUM_VALUE'
        self._backup_type = backup_type

    @property
    def status(self):
        """
        **[Required]** Gets the status of this CryptoAssessmentBackupSetSummary.
        Current status of the backup set.

        Allowed values for this property are: "AVAILABLE", "EXPIRED", "DELETED", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The status of this CryptoAssessmentBackupSetSummary.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this CryptoAssessmentBackupSetSummary.
        Current status of the backup set.


        :param status: The status of this CryptoAssessmentBackupSetSummary.
        :type: str
        """
        allowed_values = ["AVAILABLE", "EXPIRED", "DELETED", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(status, allowed_values):
            status = 'UNKNOWN_ENUM_VALUE'
        self._status = status

    @property
    def backup_pieces(self):
        """
        **[Required]** Gets the backup_pieces of this CryptoAssessmentBackupSetSummary.
        Number of backup pieces in the set.


        :return: The backup_pieces of this CryptoAssessmentBackupSetSummary.
        :rtype: int
        """
        return self._backup_pieces

    @backup_pieces.setter
    def backup_pieces(self, backup_pieces):
        """
        Sets the backup_pieces of this CryptoAssessmentBackupSetSummary.
        Number of backup pieces in the set.


        :param backup_pieces: The backup_pieces of this CryptoAssessmentBackupSetSummary.
        :type: int
        """
        self._backup_pieces = backup_pieces

    @property
    def is_encrypted(self):
        """
        **[Required]** Gets the is_encrypted of this CryptoAssessmentBackupSetSummary.
        Indicates whether the backup set is encrypted.


        :return: The is_encrypted of this CryptoAssessmentBackupSetSummary.
        :rtype: bool
        """
        return self._is_encrypted

    @is_encrypted.setter
    def is_encrypted(self, is_encrypted):
        """
        Sets the is_encrypted of this CryptoAssessmentBackupSetSummary.
        Indicates whether the backup set is encrypted.


        :param is_encrypted: The is_encrypted of this CryptoAssessmentBackupSetSummary.
        :type: bool
        """
        self._is_encrypted = is_encrypted

    @property
    def algorithm_observed(self):
        """
        Gets the algorithm_observed of this CryptoAssessmentBackupSetSummary.
        Encryption algorithm observed for the backup set when encryption is enabled.


        :return: The algorithm_observed of this CryptoAssessmentBackupSetSummary.
        :rtype: str
        """
        return self._algorithm_observed

    @algorithm_observed.setter
    def algorithm_observed(self, algorithm_observed):
        """
        Sets the algorithm_observed of this CryptoAssessmentBackupSetSummary.
        Encryption algorithm observed for the backup set when encryption is enabled.


        :param algorithm_observed: The algorithm_observed of this CryptoAssessmentBackupSetSummary.
        :type: str
        """
        self._algorithm_observed = algorithm_observed

    @property
    def cipher_mode_observed(self):
        """
        Gets the cipher_mode_observed of this CryptoAssessmentBackupSetSummary.
        Cipher mode observed for the backup set when encryption is enabled.


        :return: The cipher_mode_observed of this CryptoAssessmentBackupSetSummary.
        :rtype: str
        """
        return self._cipher_mode_observed

    @cipher_mode_observed.setter
    def cipher_mode_observed(self, cipher_mode_observed):
        """
        Sets the cipher_mode_observed of this CryptoAssessmentBackupSetSummary.
        Cipher mode observed for the backup set when encryption is enabled.


        :param cipher_mode_observed: The cipher_mode_observed of this CryptoAssessmentBackupSetSummary.
        :type: str
        """
        self._cipher_mode_observed = cipher_mode_observed

    @property
    def is_compressed(self):
        """
        Gets the is_compressed of this CryptoAssessmentBackupSetSummary.
        Indicates whether the backup set is compressed.


        :return: The is_compressed of this CryptoAssessmentBackupSetSummary.
        :rtype: bool
        """
        return self._is_compressed

    @is_compressed.setter
    def is_compressed(self, is_compressed):
        """
        Sets the is_compressed of this CryptoAssessmentBackupSetSummary.
        Indicates whether the backup set is compressed.


        :param is_compressed: The is_compressed of this CryptoAssessmentBackupSetSummary.
        :type: bool
        """
        self._is_compressed = is_compressed

    @property
    def time_created(self):
        """
        Gets the time_created of this CryptoAssessmentBackupSetSummary.
        Backup set creation time in RFC3339 format.


        :return: The time_created of this CryptoAssessmentBackupSetSummary.
        :rtype: datetime
        """
        return self._time_created

    @time_created.setter
    def time_created(self, time_created):
        """
        Sets the time_created of this CryptoAssessmentBackupSetSummary.
        Backup set creation time in RFC3339 format.


        :param time_created: The time_created of this CryptoAssessmentBackupSetSummary.
        :type: datetime
        """
        self._time_created = time_created

    @property
    def size_in_gbs(self):
        """
        **[Required]** Gets the size_in_gbs of this CryptoAssessmentBackupSetSummary.
        Backup set size in gigabytes.


        :return: The size_in_gbs of this CryptoAssessmentBackupSetSummary.
        :rtype: float
        """
        return self._size_in_gbs

    @size_in_gbs.setter
    def size_in_gbs(self, size_in_gbs):
        """
        Sets the size_in_gbs of this CryptoAssessmentBackupSetSummary.
        Backup set size in gigabytes.


        :param size_in_gbs: The size_in_gbs of this CryptoAssessmentBackupSetSummary.
        :type: float
        """
        self._size_in_gbs = size_in_gbs

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
