# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20181201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CryptoSqlnetParameter(object):
    """
    One SQLNET parameter and its evaluated quantum readiness.
    """

    #: A constant which can be used with the quantum_readiness property of a CryptoSqlnetParameter.
    #: This constant has a value of "RESISTANT"
    QUANTUM_READINESS_RESISTANT = "RESISTANT"

    #: A constant which can be used with the quantum_readiness property of a CryptoSqlnetParameter.
    #: This constant has a value of "NOT_RESISTANT"
    QUANTUM_READINESS_NOT_RESISTANT = "NOT_RESISTANT"

    #: A constant which can be used with the quantum_readiness property of a CryptoSqlnetParameter.
    #: This constant has a value of "NOT_AVAILABLE"
    QUANTUM_READINESS_NOT_AVAILABLE = "NOT_AVAILABLE"

    #: A constant which can be used with the quantum_readiness property of a CryptoSqlnetParameter.
    #: This constant has a value of "NOT_APPLICABLE"
    QUANTUM_READINESS_NOT_APPLICABLE = "NOT_APPLICABLE"

    #: A constant which can be used with the quantum_readiness property of a CryptoSqlnetParameter.
    #: This constant has a value of "NOT_SUPPORTED"
    QUANTUM_READINESS_NOT_SUPPORTED = "NOT_SUPPORTED"

    def __init__(self, **kwargs):
        """
        Initializes a new CryptoSqlnetParameter object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param name:
            The value to assign to the name property of this CryptoSqlnetParameter.
        :type name: str

        :param value:
            The value to assign to the value property of this CryptoSqlnetParameter.
        :type value: oci.data_safe.models.CryptoSqlnetParameterValue

        :param quantum_readiness:
            The value to assign to the quantum_readiness property of this CryptoSqlnetParameter.
            Allowed values for this property are: "RESISTANT", "NOT_RESISTANT", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type quantum_readiness: str

        """
        self.swagger_types = {
            'name': 'str',
            'value': 'CryptoSqlnetParameterValue',
            'quantum_readiness': 'str'
        }
        self.attribute_map = {
            'name': 'name',
            'value': 'value',
            'quantum_readiness': 'quantumReadiness'
        }
        self._name = None
        self._value = None
        self._quantum_readiness = None

    @property
    def name(self):
        """
        **[Required]** Gets the name of this CryptoSqlnetParameter.
        SQLNET parameter name.


        :return: The name of this CryptoSqlnetParameter.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CryptoSqlnetParameter.
        SQLNET parameter name.


        :param name: The name of this CryptoSqlnetParameter.
        :type: str
        """
        self._name = name

    @property
    def value(self):
        """
        **[Required]** Gets the value of this CryptoSqlnetParameter.

        :return: The value of this CryptoSqlnetParameter.
        :rtype: oci.data_safe.models.CryptoSqlnetParameterValue
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this CryptoSqlnetParameter.

        :param value: The value of this CryptoSqlnetParameter.
        :type: oci.data_safe.models.CryptoSqlnetParameterValue
        """
        self._value = value

    @property
    def quantum_readiness(self):
        """
        **[Required]** Gets the quantum_readiness of this CryptoSqlnetParameter.
        Quantum-readiness classification of this parameter.

        Allowed values for this property are: "RESISTANT", "NOT_RESISTANT", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The quantum_readiness of this CryptoSqlnetParameter.
        :rtype: str
        """
        return self._quantum_readiness

    @quantum_readiness.setter
    def quantum_readiness(self, quantum_readiness):
        """
        Sets the quantum_readiness of this CryptoSqlnetParameter.
        Quantum-readiness classification of this parameter.


        :param quantum_readiness: The quantum_readiness of this CryptoSqlnetParameter.
        :type: str
        """
        allowed_values = ["RESISTANT", "NOT_RESISTANT", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(quantum_readiness, allowed_values):
            quantum_readiness = 'UNKNOWN_ENUM_VALUE'
        self._quantum_readiness = quantum_readiness

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
