# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20181201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CryptoAssessmentTdeObjectSummary(object):
    """
    Summary of one TDE object encryption observation.
    """

    #: A constant which can be used with the quantum_readiness property of a CryptoAssessmentTdeObjectSummary.
    #: This constant has a value of "RESISTANT"
    QUANTUM_READINESS_RESISTANT = "RESISTANT"

    #: A constant which can be used with the quantum_readiness property of a CryptoAssessmentTdeObjectSummary.
    #: This constant has a value of "NOT_RESISTANT"
    QUANTUM_READINESS_NOT_RESISTANT = "NOT_RESISTANT"

    #: A constant which can be used with the quantum_readiness property of a CryptoAssessmentTdeObjectSummary.
    #: This constant has a value of "NOT_AVAILABLE"
    QUANTUM_READINESS_NOT_AVAILABLE = "NOT_AVAILABLE"

    #: A constant which can be used with the quantum_readiness property of a CryptoAssessmentTdeObjectSummary.
    #: This constant has a value of "NOT_APPLICABLE"
    QUANTUM_READINESS_NOT_APPLICABLE = "NOT_APPLICABLE"

    #: A constant which can be used with the quantum_readiness property of a CryptoAssessmentTdeObjectSummary.
    #: This constant has a value of "NOT_SUPPORTED"
    QUANTUM_READINESS_NOT_SUPPORTED = "NOT_SUPPORTED"

    def __init__(self, **kwargs):
        """
        Initializes a new CryptoAssessmentTdeObjectSummary object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param assessment_id:
            The value to assign to the assessment_id property of this CryptoAssessmentTdeObjectSummary.
        :type assessment_id: str

        :param time_last_assessed:
            The value to assign to the time_last_assessed property of this CryptoAssessmentTdeObjectSummary.
        :type time_last_assessed: datetime

        :param target_id:
            The value to assign to the target_id property of this CryptoAssessmentTdeObjectSummary.
        :type target_id: str

        :param tablespace_name:
            The value to assign to the tablespace_name property of this CryptoAssessmentTdeObjectSummary.
        :type tablespace_name: str

        :param schema_name:
            The value to assign to the schema_name property of this CryptoAssessmentTdeObjectSummary.
        :type schema_name: str

        :param table_name:
            The value to assign to the table_name property of this CryptoAssessmentTdeObjectSummary.
        :type table_name: str

        :param column_name:
            The value to assign to the column_name property of this CryptoAssessmentTdeObjectSummary.
        :type column_name: str

        :param encryption_observed:
            The value to assign to the encryption_observed property of this CryptoAssessmentTdeObjectSummary.
        :type encryption_observed: str

        :param mode_observed:
            The value to assign to the mode_observed property of this CryptoAssessmentTdeObjectSummary.
        :type mode_observed: str

        :param size_in_gbs:
            The value to assign to the size_in_gbs property of this CryptoAssessmentTdeObjectSummary.
        :type size_in_gbs: float

        :param quantum_readiness:
            The value to assign to the quantum_readiness property of this CryptoAssessmentTdeObjectSummary.
            Allowed values for this property are: "RESISTANT", "NOT_RESISTANT", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type quantum_readiness: str

        """
        self.swagger_types = {
            'assessment_id': 'str',
            'time_last_assessed': 'datetime',
            'target_id': 'str',
            'tablespace_name': 'str',
            'schema_name': 'str',
            'table_name': 'str',
            'column_name': 'str',
            'encryption_observed': 'str',
            'mode_observed': 'str',
            'size_in_gbs': 'float',
            'quantum_readiness': 'str'
        }
        self.attribute_map = {
            'assessment_id': 'assessmentId',
            'time_last_assessed': 'timeLastAssessed',
            'target_id': 'targetId',
            'tablespace_name': 'tablespaceName',
            'schema_name': 'schemaName',
            'table_name': 'tableName',
            'column_name': 'columnName',
            'encryption_observed': 'encryptionObserved',
            'mode_observed': 'modeObserved',
            'size_in_gbs': 'sizeInGBs',
            'quantum_readiness': 'quantumReadiness'
        }
        self._assessment_id = None
        self._time_last_assessed = None
        self._target_id = None
        self._tablespace_name = None
        self._schema_name = None
        self._table_name = None
        self._column_name = None
        self._encryption_observed = None
        self._mode_observed = None
        self._size_in_gbs = None
        self._quantum_readiness = None

    @property
    def assessment_id(self):
        """
        **[Required]** Gets the assessment_id of this CryptoAssessmentTdeObjectSummary.
        OCID of the crypto assessment that discovered the TDE object.


        :return: The assessment_id of this CryptoAssessmentTdeObjectSummary.
        :rtype: str
        """
        return self._assessment_id

    @assessment_id.setter
    def assessment_id(self, assessment_id):
        """
        Sets the assessment_id of this CryptoAssessmentTdeObjectSummary.
        OCID of the crypto assessment that discovered the TDE object.


        :param assessment_id: The assessment_id of this CryptoAssessmentTdeObjectSummary.
        :type: str
        """
        self._assessment_id = assessment_id

    @property
    def time_last_assessed(self):
        """
        Gets the time_last_assessed of this CryptoAssessmentTdeObjectSummary.
        The date and time the associated crypto assessment was last assessed, in RFC3339 format.


        :return: The time_last_assessed of this CryptoAssessmentTdeObjectSummary.
        :rtype: datetime
        """
        return self._time_last_assessed

    @time_last_assessed.setter
    def time_last_assessed(self, time_last_assessed):
        """
        Sets the time_last_assessed of this CryptoAssessmentTdeObjectSummary.
        The date and time the associated crypto assessment was last assessed, in RFC3339 format.


        :param time_last_assessed: The time_last_assessed of this CryptoAssessmentTdeObjectSummary.
        :type: datetime
        """
        self._time_last_assessed = time_last_assessed

    @property
    def target_id(self):
        """
        **[Required]** Gets the target_id of this CryptoAssessmentTdeObjectSummary.
        OCID of the target database associated with the TDE object.


        :return: The target_id of this CryptoAssessmentTdeObjectSummary.
        :rtype: str
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id):
        """
        Sets the target_id of this CryptoAssessmentTdeObjectSummary.
        OCID of the target database associated with the TDE object.


        :param target_id: The target_id of this CryptoAssessmentTdeObjectSummary.
        :type: str
        """
        self._target_id = target_id

    @property
    def tablespace_name(self):
        """
        Gets the tablespace_name of this CryptoAssessmentTdeObjectSummary.
        Name of the tablespace. This field is returned when objectType is TABLESPACE.


        :return: The tablespace_name of this CryptoAssessmentTdeObjectSummary.
        :rtype: str
        """
        return self._tablespace_name

    @tablespace_name.setter
    def tablespace_name(self, tablespace_name):
        """
        Sets the tablespace_name of this CryptoAssessmentTdeObjectSummary.
        Name of the tablespace. This field is returned when objectType is TABLESPACE.


        :param tablespace_name: The tablespace_name of this CryptoAssessmentTdeObjectSummary.
        :type: str
        """
        self._tablespace_name = tablespace_name

    @property
    def schema_name(self):
        """
        Gets the schema_name of this CryptoAssessmentTdeObjectSummary.
        Name of the schema containing the encrypted column. This field is returned when objectType is COLUMN.


        :return: The schema_name of this CryptoAssessmentTdeObjectSummary.
        :rtype: str
        """
        return self._schema_name

    @schema_name.setter
    def schema_name(self, schema_name):
        """
        Sets the schema_name of this CryptoAssessmentTdeObjectSummary.
        Name of the schema containing the encrypted column. This field is returned when objectType is COLUMN.


        :param schema_name: The schema_name of this CryptoAssessmentTdeObjectSummary.
        :type: str
        """
        self._schema_name = schema_name

    @property
    def table_name(self):
        """
        Gets the table_name of this CryptoAssessmentTdeObjectSummary.
        Name of the table containing the encrypted column. This field is returned when objectType is COLUMN.


        :return: The table_name of this CryptoAssessmentTdeObjectSummary.
        :rtype: str
        """
        return self._table_name

    @table_name.setter
    def table_name(self, table_name):
        """
        Sets the table_name of this CryptoAssessmentTdeObjectSummary.
        Name of the table containing the encrypted column. This field is returned when objectType is COLUMN.


        :param table_name: The table_name of this CryptoAssessmentTdeObjectSummary.
        :type: str
        """
        self._table_name = table_name

    @property
    def column_name(self):
        """
        Gets the column_name of this CryptoAssessmentTdeObjectSummary.
        Name of the encrypted column. This field is returned when objectType is COLUMN.


        :return: The column_name of this CryptoAssessmentTdeObjectSummary.
        :rtype: str
        """
        return self._column_name

    @column_name.setter
    def column_name(self, column_name):
        """
        Sets the column_name of this CryptoAssessmentTdeObjectSummary.
        Name of the encrypted column. This field is returned when objectType is COLUMN.


        :param column_name: The column_name of this CryptoAssessmentTdeObjectSummary.
        :type: str
        """
        self._column_name = column_name

    @property
    def encryption_observed(self):
        """
        **[Required]** Gets the encryption_observed of this CryptoAssessmentTdeObjectSummary.
        Encryption algorithm observed for the TDE object.


        :return: The encryption_observed of this CryptoAssessmentTdeObjectSummary.
        :rtype: str
        """
        return self._encryption_observed

    @encryption_observed.setter
    def encryption_observed(self, encryption_observed):
        """
        Sets the encryption_observed of this CryptoAssessmentTdeObjectSummary.
        Encryption algorithm observed for the TDE object.


        :param encryption_observed: The encryption_observed of this CryptoAssessmentTdeObjectSummary.
        :type: str
        """
        self._encryption_observed = encryption_observed

    @property
    def mode_observed(self):
        """
        Gets the mode_observed of this CryptoAssessmentTdeObjectSummary.
        Encryption mode observed for the tablespace. This field is returned when objectType is TABLESPACE.


        :return: The mode_observed of this CryptoAssessmentTdeObjectSummary.
        :rtype: str
        """
        return self._mode_observed

    @mode_observed.setter
    def mode_observed(self, mode_observed):
        """
        Sets the mode_observed of this CryptoAssessmentTdeObjectSummary.
        Encryption mode observed for the tablespace. This field is returned when objectType is TABLESPACE.


        :param mode_observed: The mode_observed of this CryptoAssessmentTdeObjectSummary.
        :type: str
        """
        self._mode_observed = mode_observed

    @property
    def size_in_gbs(self):
        """
        Gets the size_in_gbs of this CryptoAssessmentTdeObjectSummary.
        Tablespace size in gigabytes. This field is returned when objectType is TABLESPACE.


        :return: The size_in_gbs of this CryptoAssessmentTdeObjectSummary.
        :rtype: float
        """
        return self._size_in_gbs

    @size_in_gbs.setter
    def size_in_gbs(self, size_in_gbs):
        """
        Sets the size_in_gbs of this CryptoAssessmentTdeObjectSummary.
        Tablespace size in gigabytes. This field is returned when objectType is TABLESPACE.


        :param size_in_gbs: The size_in_gbs of this CryptoAssessmentTdeObjectSummary.
        :type: float
        """
        self._size_in_gbs = size_in_gbs

    @property
    def quantum_readiness(self):
        """
        **[Required]** Gets the quantum_readiness of this CryptoAssessmentTdeObjectSummary.
        Quantum-readiness classification for the observed TDE object encryption.

        Allowed values for this property are: "RESISTANT", "NOT_RESISTANT", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The quantum_readiness of this CryptoAssessmentTdeObjectSummary.
        :rtype: str
        """
        return self._quantum_readiness

    @quantum_readiness.setter
    def quantum_readiness(self, quantum_readiness):
        """
        Sets the quantum_readiness of this CryptoAssessmentTdeObjectSummary.
        Quantum-readiness classification for the observed TDE object encryption.


        :param quantum_readiness: The quantum_readiness of this CryptoAssessmentTdeObjectSummary.
        :type: str
        """
        allowed_values = ["RESISTANT", "NOT_RESISTANT", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(quantum_readiness, allowed_values):
            quantum_readiness = 'UNKNOWN_ENUM_VALUE'
        self._quantum_readiness = quantum_readiness

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
