# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20181201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CryptoPosture(object):
    """
    Cryptographic posture details captured by the assessment.
    """

    #: A constant which can be used with the fips_status property of a CryptoPosture.
    #: This constant has a value of "ENABLED"
    FIPS_STATUS_ENABLED = "ENABLED"

    #: A constant which can be used with the fips_status property of a CryptoPosture.
    #: This constant has a value of "DISABLED"
    FIPS_STATUS_DISABLED = "DISABLED"

    #: A constant which can be used with the fips_status property of a CryptoPosture.
    #: This constant has a value of "NOT_CONFIGURED"
    FIPS_STATUS_NOT_CONFIGURED = "NOT_CONFIGURED"

    #: A constant which can be used with the fips_status property of a CryptoPosture.
    #: This constant has a value of "NOT_AVAILABLE"
    FIPS_STATUS_NOT_AVAILABLE = "NOT_AVAILABLE"

    #: A constant which can be used with the fips_status property of a CryptoPosture.
    #: This constant has a value of "NOT_APPLICABLE"
    FIPS_STATUS_NOT_APPLICABLE = "NOT_APPLICABLE"

    #: A constant which can be used with the fips_status property of a CryptoPosture.
    #: This constant has a value of "NOT_SUPPORTED"
    FIPS_STATUS_NOT_SUPPORTED = "NOT_SUPPORTED"

    #: A constant which can be used with the fips_mode_configured property of a CryptoPosture.
    #: This constant has a value of "FIPS_140_2"
    FIPS_MODE_CONFIGURED_FIPS_140_2 = "FIPS_140_2"

    #: A constant which can be used with the fips_mode_configured property of a CryptoPosture.
    #: This constant has a value of "FIPS_140_3"
    FIPS_MODE_CONFIGURED_FIPS_140_3 = "FIPS_140_3"

    #: A constant which can be used with the fips_mode_configured property of a CryptoPosture.
    #: This constant has a value of "NOT_CONFIGURED"
    FIPS_MODE_CONFIGURED_NOT_CONFIGURED = "NOT_CONFIGURED"

    #: A constant which can be used with the fips_mode_configured property of a CryptoPosture.
    #: This constant has a value of "NOT_APPLICABLE"
    FIPS_MODE_CONFIGURED_NOT_APPLICABLE = "NOT_APPLICABLE"

    #: A constant which can be used with the fips_mode_configured property of a CryptoPosture.
    #: This constant has a value of "NOT_SUPPORTED"
    FIPS_MODE_CONFIGURED_NOT_SUPPORTED = "NOT_SUPPORTED"

    def __init__(self, **kwargs):
        """
        Initializes a new CryptoPosture object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param tls:
            The value to assign to the tls property of this CryptoPosture.
        :type tls: oci.data_safe.models.CryptoTlsPosture

        :param nne:
            The value to assign to the nne property of this CryptoPosture.
        :type nne: oci.data_safe.models.CryptoNnePosture

        :param tde:
            The value to assign to the tde property of this CryptoPosture.
        :type tde: oci.data_safe.models.CryptoTdePosture

        :param network_encryption:
            The value to assign to the network_encryption property of this CryptoPosture.
        :type network_encryption: list[str]

        :param fips_status:
            The value to assign to the fips_status property of this CryptoPosture.
            Allowed values for this property are: "ENABLED", "DISABLED", "NOT_CONFIGURED", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type fips_status: str

        :param fips_mode_configured:
            The value to assign to the fips_mode_configured property of this CryptoPosture.
            Allowed values for this property are: "FIPS_140_2", "FIPS_140_3", "NOT_CONFIGURED", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type fips_mode_configured: str

        :param backup_status:
            The value to assign to the backup_status property of this CryptoPosture.
        :type backup_status: str

        :param encrypted_backup_pieces_count:
            The value to assign to the encrypted_backup_pieces_count property of this CryptoPosture.
        :type encrypted_backup_pieces_count: int

        :param unencrypted_backup_pieces_count:
            The value to assign to the unencrypted_backup_pieces_count property of this CryptoPosture.
        :type unencrypted_backup_pieces_count: int

        """
        self.swagger_types = {
            'tls': 'CryptoTlsPosture',
            'nne': 'CryptoNnePosture',
            'tde': 'CryptoTdePosture',
            'network_encryption': 'list[str]',
            'fips_status': 'str',
            'fips_mode_configured': 'str',
            'backup_status': 'str',
            'encrypted_backup_pieces_count': 'int',
            'unencrypted_backup_pieces_count': 'int'
        }
        self.attribute_map = {
            'tls': 'tls',
            'nne': 'nne',
            'tde': 'tde',
            'network_encryption': 'networkEncryption',
            'fips_status': 'fipsStatus',
            'fips_mode_configured': 'fipsModeConfigured',
            'backup_status': 'backupStatus',
            'encrypted_backup_pieces_count': 'encryptedBackupPiecesCount',
            'unencrypted_backup_pieces_count': 'unencryptedBackupPiecesCount'
        }
        self._tls = None
        self._nne = None
        self._tde = None
        self._network_encryption = None
        self._fips_status = None
        self._fips_mode_configured = None
        self._backup_status = None
        self._encrypted_backup_pieces_count = None
        self._unencrypted_backup_pieces_count = None

    @property
    def tls(self):
        """
        Gets the tls of this CryptoPosture.

        :return: The tls of this CryptoPosture.
        :rtype: oci.data_safe.models.CryptoTlsPosture
        """
        return self._tls

    @tls.setter
    def tls(self, tls):
        """
        Sets the tls of this CryptoPosture.

        :param tls: The tls of this CryptoPosture.
        :type: oci.data_safe.models.CryptoTlsPosture
        """
        self._tls = tls

    @property
    def nne(self):
        """
        Gets the nne of this CryptoPosture.

        :return: The nne of this CryptoPosture.
        :rtype: oci.data_safe.models.CryptoNnePosture
        """
        return self._nne

    @nne.setter
    def nne(self, nne):
        """
        Sets the nne of this CryptoPosture.

        :param nne: The nne of this CryptoPosture.
        :type: oci.data_safe.models.CryptoNnePosture
        """
        self._nne = nne

    @property
    def tde(self):
        """
        Gets the tde of this CryptoPosture.

        :return: The tde of this CryptoPosture.
        :rtype: oci.data_safe.models.CryptoTdePosture
        """
        return self._tde

    @tde.setter
    def tde(self, tde):
        """
        Sets the tde of this CryptoPosture.

        :param tde: The tde of this CryptoPosture.
        :type: oci.data_safe.models.CryptoTdePosture
        """
        self._tde = tde

    @property
    def network_encryption(self):
        """
        Gets the network_encryption of this CryptoPosture.
        Network encryption details.


        :return: The network_encryption of this CryptoPosture.
        :rtype: list[str]
        """
        return self._network_encryption

    @network_encryption.setter
    def network_encryption(self, network_encryption):
        """
        Sets the network_encryption of this CryptoPosture.
        Network encryption details.


        :param network_encryption: The network_encryption of this CryptoPosture.
        :type: list[str]
        """
        self._network_encryption = network_encryption

    @property
    def fips_status(self):
        """
        Gets the fips_status of this CryptoPosture.
        Overall FIPS status for the assessment when the target uses common FIPS configuration.

        Allowed values for this property are: "ENABLED", "DISABLED", "NOT_CONFIGURED", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The fips_status of this CryptoPosture.
        :rtype: str
        """
        return self._fips_status

    @fips_status.setter
    def fips_status(self, fips_status):
        """
        Sets the fips_status of this CryptoPosture.
        Overall FIPS status for the assessment when the target uses common FIPS configuration.


        :param fips_status: The fips_status of this CryptoPosture.
        :type: str
        """
        allowed_values = ["ENABLED", "DISABLED", "NOT_CONFIGURED", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(fips_status, allowed_values):
            fips_status = 'UNKNOWN_ENUM_VALUE'
        self._fips_status = fips_status

    @property
    def fips_mode_configured(self):
        """
        Gets the fips_mode_configured of this CryptoPosture.
        Common FIPS mode configured for the assessment when the target uses common FIPS configuration.

        Allowed values for this property are: "FIPS_140_2", "FIPS_140_3", "NOT_CONFIGURED", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The fips_mode_configured of this CryptoPosture.
        :rtype: str
        """
        return self._fips_mode_configured

    @fips_mode_configured.setter
    def fips_mode_configured(self, fips_mode_configured):
        """
        Sets the fips_mode_configured of this CryptoPosture.
        Common FIPS mode configured for the assessment when the target uses common FIPS configuration.


        :param fips_mode_configured: The fips_mode_configured of this CryptoPosture.
        :type: str
        """
        allowed_values = ["FIPS_140_2", "FIPS_140_3", "NOT_CONFIGURED", "NOT_APPLICABLE", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(fips_mode_configured, allowed_values):
            fips_mode_configured = 'UNKNOWN_ENUM_VALUE'
        self._fips_mode_configured = fips_mode_configured

    @property
    def backup_status(self):
        """
        Gets the backup_status of this CryptoPosture.
        Backup encryption status observed for the assessment.


        :return: The backup_status of this CryptoPosture.
        :rtype: str
        """
        return self._backup_status

    @backup_status.setter
    def backup_status(self, backup_status):
        """
        Sets the backup_status of this CryptoPosture.
        Backup encryption status observed for the assessment.


        :param backup_status: The backup_status of this CryptoPosture.
        :type: str
        """
        self._backup_status = backup_status

    @property
    def encrypted_backup_pieces_count(self):
        """
        Gets the encrypted_backup_pieces_count of this CryptoPosture.
        Number of encrypted backup pieces.


        :return: The encrypted_backup_pieces_count of this CryptoPosture.
        :rtype: int
        """
        return self._encrypted_backup_pieces_count

    @encrypted_backup_pieces_count.setter
    def encrypted_backup_pieces_count(self, encrypted_backup_pieces_count):
        """
        Sets the encrypted_backup_pieces_count of this CryptoPosture.
        Number of encrypted backup pieces.


        :param encrypted_backup_pieces_count: The encrypted_backup_pieces_count of this CryptoPosture.
        :type: int
        """
        self._encrypted_backup_pieces_count = encrypted_backup_pieces_count

    @property
    def unencrypted_backup_pieces_count(self):
        """
        Gets the unencrypted_backup_pieces_count of this CryptoPosture.
        Number of unencrypted backup pieces.


        :return: The unencrypted_backup_pieces_count of this CryptoPosture.
        :rtype: int
        """
        return self._unencrypted_backup_pieces_count

    @unencrypted_backup_pieces_count.setter
    def unencrypted_backup_pieces_count(self, unencrypted_backup_pieces_count):
        """
        Sets the unencrypted_backup_pieces_count of this CryptoPosture.
        Number of unencrypted backup pieces.


        :param unencrypted_backup_pieces_count: The unencrypted_backup_pieces_count of this CryptoPosture.
        :type: int
        """
        self._unencrypted_backup_pieces_count = unencrypted_backup_pieces_count

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
