# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20181201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CryptoNnePosture(object):
    """
    Native network encryption posture details.
    """

    #: A constant which can be used with the status property of a CryptoNnePosture.
    #: This constant has a value of "ENABLED"
    STATUS_ENABLED = "ENABLED"

    #: A constant which can be used with the status property of a CryptoNnePosture.
    #: This constant has a value of "DISABLED"
    STATUS_DISABLED = "DISABLED"

    #: A constant which can be used with the status property of a CryptoNnePosture.
    #: This constant has a value of "NOT_CONFIGURED"
    STATUS_NOT_CONFIGURED = "NOT_CONFIGURED"

    #: A constant which can be used with the status property of a CryptoNnePosture.
    #: This constant has a value of "NOT_AVAILABLE"
    STATUS_NOT_AVAILABLE = "NOT_AVAILABLE"

    #: A constant which can be used with the status property of a CryptoNnePosture.
    #: This constant has a value of "NOT_APPLICABLE"
    STATUS_NOT_APPLICABLE = "NOT_APPLICABLE"

    #: A constant which can be used with the status property of a CryptoNnePosture.
    #: This constant has a value of "NOT_SUPPORTED"
    STATUS_NOT_SUPPORTED = "NOT_SUPPORTED"

    #: A constant which can be used with the are_weak_options_allowed property of a CryptoNnePosture.
    #: This constant has a value of "TRUE"
    ARE_WEAK_OPTIONS_ALLOWED_TRUE = "TRUE"

    #: A constant which can be used with the are_weak_options_allowed property of a CryptoNnePosture.
    #: This constant has a value of "FALSE"
    ARE_WEAK_OPTIONS_ALLOWED_FALSE = "FALSE"

    #: A constant which can be used with the are_weak_options_allowed property of a CryptoNnePosture.
    #: This constant has a value of "NOT_SUPPORTED"
    ARE_WEAK_OPTIONS_ALLOWED_NOT_SUPPORTED = "NOT_SUPPORTED"

    #: A constant which can be used with the server_encryption property of a CryptoNnePosture.
    #: This constant has a value of "REQUIRED"
    SERVER_ENCRYPTION_REQUIRED = "REQUIRED"

    #: A constant which can be used with the server_encryption property of a CryptoNnePosture.
    #: This constant has a value of "REQUESTED"
    SERVER_ENCRYPTION_REQUESTED = "REQUESTED"

    #: A constant which can be used with the server_encryption property of a CryptoNnePosture.
    #: This constant has a value of "ACCEPTED"
    SERVER_ENCRYPTION_ACCEPTED = "ACCEPTED"

    #: A constant which can be used with the server_encryption property of a CryptoNnePosture.
    #: This constant has a value of "REJECTED"
    SERVER_ENCRYPTION_REJECTED = "REJECTED"

    #: A constant which can be used with the server_encryption property of a CryptoNnePosture.
    #: This constant has a value of "NOT_SUPPORTED"
    SERVER_ENCRYPTION_NOT_SUPPORTED = "NOT_SUPPORTED"

    #: A constant which can be used with the quantum_readiness property of a CryptoNnePosture.
    #: This constant has a value of "RESISTANT"
    QUANTUM_READINESS_RESISTANT = "RESISTANT"

    #: A constant which can be used with the quantum_readiness property of a CryptoNnePosture.
    #: This constant has a value of "NOT_RESISTANT"
    QUANTUM_READINESS_NOT_RESISTANT = "NOT_RESISTANT"

    #: A constant which can be used with the quantum_readiness property of a CryptoNnePosture.
    #: This constant has a value of "NOT_AVAILABLE"
    QUANTUM_READINESS_NOT_AVAILABLE = "NOT_AVAILABLE"

    #: A constant which can be used with the quantum_readiness property of a CryptoNnePosture.
    #: This constant has a value of "NOT_APPLICABLE"
    QUANTUM_READINESS_NOT_APPLICABLE = "NOT_APPLICABLE"

    #: A constant which can be used with the quantum_readiness property of a CryptoNnePosture.
    #: This constant has a value of "NOT_SUPPORTED"
    QUANTUM_READINESS_NOT_SUPPORTED = "NOT_SUPPORTED"

    def __init__(self, **kwargs):
        """
        Initializes a new CryptoNnePosture object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param status:
            The value to assign to the status property of this CryptoNnePosture.
            Allowed values for this property are: "ENABLED", "DISABLED", "NOT_CONFIGURED", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type status: str

        :param are_weak_options_allowed:
            The value to assign to the are_weak_options_allowed property of this CryptoNnePosture.
            Allowed values for this property are: "TRUE", "FALSE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type are_weak_options_allowed: str

        :param encryption_configured:
            The value to assign to the encryption_configured property of this CryptoNnePosture.
        :type encryption_configured: list[str]

        :param integrity:
            The value to assign to the integrity property of this CryptoNnePosture.
        :type integrity: list[str]

        :param server_encryption:
            The value to assign to the server_encryption property of this CryptoNnePosture.
            Allowed values for this property are: "REQUIRED", "REQUESTED", "ACCEPTED", "REJECTED", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type server_encryption: str

        :param server_integrity:
            The value to assign to the server_integrity property of this CryptoNnePosture.
        :type server_integrity: list[str]

        :param key_exchange:
            The value to assign to the key_exchange property of this CryptoNnePosture.
        :type key_exchange: str

        :param quantum_readiness:
            The value to assign to the quantum_readiness property of this CryptoNnePosture.
            Allowed values for this property are: "RESISTANT", "NOT_RESISTANT", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type quantum_readiness: str

        :param fips_mode_configured:
            The value to assign to the fips_mode_configured property of this CryptoNnePosture.
        :type fips_mode_configured: str

        """
        self.swagger_types = {
            'status': 'str',
            'are_weak_options_allowed': 'str',
            'encryption_configured': 'list[str]',
            'integrity': 'list[str]',
            'server_encryption': 'str',
            'server_integrity': 'list[str]',
            'key_exchange': 'str',
            'quantum_readiness': 'str',
            'fips_mode_configured': 'str'
        }
        self.attribute_map = {
            'status': 'status',
            'are_weak_options_allowed': 'areWeakOptionsAllowed',
            'encryption_configured': 'encryptionConfigured',
            'integrity': 'integrity',
            'server_encryption': 'serverEncryption',
            'server_integrity': 'serverIntegrity',
            'key_exchange': 'keyExchange',
            'quantum_readiness': 'quantumReadiness',
            'fips_mode_configured': 'fipsModeConfigured'
        }
        self._status = None
        self._are_weak_options_allowed = None
        self._encryption_configured = None
        self._integrity = None
        self._server_encryption = None
        self._server_integrity = None
        self._key_exchange = None
        self._quantum_readiness = None
        self._fips_mode_configured = None

    @property
    def status(self):
        """
        Gets the status of this CryptoNnePosture.
        NNE enablement status.

        Allowed values for this property are: "ENABLED", "DISABLED", "NOT_CONFIGURED", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The status of this CryptoNnePosture.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this CryptoNnePosture.
        NNE enablement status.


        :param status: The status of this CryptoNnePosture.
        :type: str
        """
        allowed_values = ["ENABLED", "DISABLED", "NOT_CONFIGURED", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(status, allowed_values):
            status = 'UNKNOWN_ENUM_VALUE'
        self._status = status

    @property
    def are_weak_options_allowed(self):
        """
        Gets the are_weak_options_allowed of this CryptoNnePosture.
        Indicates if weak NNE options are allowed.

        Allowed values for this property are: "TRUE", "FALSE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The are_weak_options_allowed of this CryptoNnePosture.
        :rtype: str
        """
        return self._are_weak_options_allowed

    @are_weak_options_allowed.setter
    def are_weak_options_allowed(self, are_weak_options_allowed):
        """
        Sets the are_weak_options_allowed of this CryptoNnePosture.
        Indicates if weak NNE options are allowed.


        :param are_weak_options_allowed: The are_weak_options_allowed of this CryptoNnePosture.
        :type: str
        """
        allowed_values = ["TRUE", "FALSE", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(are_weak_options_allowed, allowed_values):
            are_weak_options_allowed = 'UNKNOWN_ENUM_VALUE'
        self._are_weak_options_allowed = are_weak_options_allowed

    @property
    def encryption_configured(self):
        """
        Gets the encryption_configured of this CryptoNnePosture.
        Configured network encryption algorithm.


        :return: The encryption_configured of this CryptoNnePosture.
        :rtype: list[str]
        """
        return self._encryption_configured

    @encryption_configured.setter
    def encryption_configured(self, encryption_configured):
        """
        Sets the encryption_configured of this CryptoNnePosture.
        Configured network encryption algorithm.


        :param encryption_configured: The encryption_configured of this CryptoNnePosture.
        :type: list[str]
        """
        self._encryption_configured = encryption_configured

    @property
    def integrity(self):
        """
        Gets the integrity of this CryptoNnePosture.
        NNE integrity algorithm(s).


        :return: The integrity of this CryptoNnePosture.
        :rtype: list[str]
        """
        return self._integrity

    @integrity.setter
    def integrity(self, integrity):
        """
        Sets the integrity of this CryptoNnePosture.
        NNE integrity algorithm(s).


        :param integrity: The integrity of this CryptoNnePosture.
        :type: list[str]
        """
        self._integrity = integrity

    @property
    def server_encryption(self):
        """
        Gets the server_encryption of this CryptoNnePosture.
        Observed server-side encryption requirement.

        Allowed values for this property are: "REQUIRED", "REQUESTED", "ACCEPTED", "REJECTED", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The server_encryption of this CryptoNnePosture.
        :rtype: str
        """
        return self._server_encryption

    @server_encryption.setter
    def server_encryption(self, server_encryption):
        """
        Sets the server_encryption of this CryptoNnePosture.
        Observed server-side encryption requirement.


        :param server_encryption: The server_encryption of this CryptoNnePosture.
        :type: str
        """
        allowed_values = ["REQUIRED", "REQUESTED", "ACCEPTED", "REJECTED", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(server_encryption, allowed_values):
            server_encryption = 'UNKNOWN_ENUM_VALUE'
        self._server_encryption = server_encryption

    @property
    def server_integrity(self):
        """
        Gets the server_integrity of this CryptoNnePosture.
        NNE server integrity algorithm(s).


        :return: The server_integrity of this CryptoNnePosture.
        :rtype: list[str]
        """
        return self._server_integrity

    @server_integrity.setter
    def server_integrity(self, server_integrity):
        """
        Sets the server_integrity of this CryptoNnePosture.
        NNE server integrity algorithm(s).


        :param server_integrity: The server_integrity of this CryptoNnePosture.
        :type: list[str]
        """
        self._server_integrity = server_integrity

    @property
    def key_exchange(self):
        """
        Gets the key_exchange of this CryptoNnePosture.
        Observed NNE key exchange setting.


        :return: The key_exchange of this CryptoNnePosture.
        :rtype: str
        """
        return self._key_exchange

    @key_exchange.setter
    def key_exchange(self, key_exchange):
        """
        Sets the key_exchange of this CryptoNnePosture.
        Observed NNE key exchange setting.


        :param key_exchange: The key_exchange of this CryptoNnePosture.
        :type: str
        """
        self._key_exchange = key_exchange

    @property
    def quantum_readiness(self):
        """
        Gets the quantum_readiness of this CryptoNnePosture.
        Quantum-readiness classification for NNE posture.

        Allowed values for this property are: "RESISTANT", "NOT_RESISTANT", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The quantum_readiness of this CryptoNnePosture.
        :rtype: str
        """
        return self._quantum_readiness

    @quantum_readiness.setter
    def quantum_readiness(self, quantum_readiness):
        """
        Sets the quantum_readiness of this CryptoNnePosture.
        Quantum-readiness classification for NNE posture.


        :param quantum_readiness: The quantum_readiness of this CryptoNnePosture.
        :type: str
        """
        allowed_values = ["RESISTANT", "NOT_RESISTANT", "NOT_AVAILABLE", "NOT_APPLICABLE", "NOT_SUPPORTED"]
        if not value_allowed_none_or_none_sentinel(quantum_readiness, allowed_values):
            quantum_readiness = 'UNKNOWN_ENUM_VALUE'
        self._quantum_readiness = quantum_readiness

    @property
    def fips_mode_configured(self):
        """
        Gets the fips_mode_configured of this CryptoNnePosture.
        FIPS mode configured for NNE when the target uses legacy per-feature FIPS configuration.


        :return: The fips_mode_configured of this CryptoNnePosture.
        :rtype: str
        """
        return self._fips_mode_configured

    @fips_mode_configured.setter
    def fips_mode_configured(self, fips_mode_configured):
        """
        Sets the fips_mode_configured of this CryptoNnePosture.
        FIPS mode configured for NNE when the target uses legacy per-feature FIPS configuration.


        :param fips_mode_configured: The fips_mode_configured of this CryptoNnePosture.
        :type: str
        """
        self._fips_mode_configured = fips_mode_configured

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
