# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20181201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CryptoAssessmentFindingCategorySummary(object):
    """
    Aggregate finding counts for one crypto finding category.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new CryptoAssessmentFindingCategorySummary object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param pass_checks:
            The value to assign to the pass_checks property of this CryptoAssessmentFindingCategorySummary.
        :type pass_checks: int

        :param findings:
            The value to assign to the findings property of this CryptoAssessmentFindingCategorySummary.
        :type findings: int

        :param total_checks:
            The value to assign to the total_checks property of this CryptoAssessmentFindingCategorySummary.
        :type total_checks: int

        """
        self.swagger_types = {
            'pass_checks': 'int',
            'findings': 'int',
            'total_checks': 'int'
        }
        self.attribute_map = {
            'pass_checks': 'passChecks',
            'findings': 'findings',
            'total_checks': 'totalChecks'
        }
        self._pass_checks = None
        self._findings = None
        self._total_checks = None

    @property
    def pass_checks(self):
        """
        **[Required]** Gets the pass_checks of this CryptoAssessmentFindingCategorySummary.
        Findings with PASS status.


        :return: The pass_checks of this CryptoAssessmentFindingCategorySummary.
        :rtype: int
        """
        return self._pass_checks

    @pass_checks.setter
    def pass_checks(self, pass_checks):
        """
        Sets the pass_checks of this CryptoAssessmentFindingCategorySummary.
        Findings with PASS status.


        :param pass_checks: The pass_checks of this CryptoAssessmentFindingCategorySummary.
        :type: int
        """
        self._pass_checks = pass_checks

    @property
    def findings(self):
        """
        **[Required]** Gets the findings of this CryptoAssessmentFindingCategorySummary.
        Findings with FAIL or EVALUATE status.


        :return: The findings of this CryptoAssessmentFindingCategorySummary.
        :rtype: int
        """
        return self._findings

    @findings.setter
    def findings(self, findings):
        """
        Sets the findings of this CryptoAssessmentFindingCategorySummary.
        Findings with FAIL or EVALUATE status.


        :param findings: The findings of this CryptoAssessmentFindingCategorySummary.
        :type: int
        """
        self._findings = findings

    @property
    def total_checks(self):
        """
        **[Required]** Gets the total_checks of this CryptoAssessmentFindingCategorySummary.
        Total findings across all statuses in this category.


        :return: The total_checks of this CryptoAssessmentFindingCategorySummary.
        :rtype: int
        """
        return self._total_checks

    @total_checks.setter
    def total_checks(self, total_checks):
        """
        Sets the total_checks of this CryptoAssessmentFindingCategorySummary.
        Total findings across all statuses in this category.


        :param total_checks: The total_checks of this CryptoAssessmentFindingCategorySummary.
        :type: int
        """
        self._total_checks = total_checks

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
