# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20260325

from __future__ import absolute_import

from .application import Application
from .application_logging_config import ApplicationLoggingConfig
from .application_summary import ApplicationSummary
from .application_trace_config import ApplicationTraceConfig
from .archive_function_source_details import ArchiveFunctionSourceDetails
from .archive_source_details import ArchiveSourceDetails
from .change_application_compartment_details import ChangeApplicationCompartmentDetails
from .config_details import ConfigDetails
from .constant_provisioned_concurrency_config import ConstantProvisionedConcurrencyConfig
from .container_image_function_source_details import ContainerImageFunctionSourceDetails
from .create_application_details import CreateApplicationDetails
from .create_archive_function_source_details import CreateArchiveFunctionSourceDetails
from .create_archive_source_details import CreateArchiveSourceDetails
from .create_container_image_function_source_details import CreateContainerImageFunctionSourceDetails
from .create_direct_archive_source_details import CreateDirectArchiveSourceDetails
from .create_function_details import CreateFunctionDetails
from .create_function_source_details import CreateFunctionSourceDetails
from .create_function_update_runtime_config import CreateFunctionUpdateRuntimeConfig
from .create_manual_runtime_config import CreateManualRuntimeConfig
from .create_object_storage_archive_source_details import CreateObjectStorageArchiveSourceDetails
from .create_pre_built_function_source_details import CreatePreBuiltFunctionSourceDetails
from .create_runtime_config import CreateRuntimeConfig
from .direct_archive_source_details import DirectArchiveSourceDetails
from .failure_destination_details import FailureDestinationDetails
from .function import Function
from .function_provisioned_concurrency_config import FunctionProvisionedConcurrencyConfig
from .function_source_details import FunctionSourceDetails
from .function_summary import FunctionSummary
from .function_trace_config import FunctionTraceConfig
from .function_update_runtime_config import FunctionUpdateRuntimeConfig
from .functions_runtime import FunctionsRuntime
from .functions_runtime_collection import FunctionsRuntimeCollection
from .functions_runtime_summary import FunctionsRuntimeSummary
from .functions_runtime_version import FunctionsRuntimeVersion
from .functions_runtime_version_collection import FunctionsRuntimeVersionCollection
from .functions_runtime_version_summary import FunctionsRuntimeVersionSummary
from .image_policy_config import ImagePolicyConfig
from .key_details import KeyDetails
from .manual_runtime_config import ManualRuntimeConfig
from .none_failure_destination_details import NoneFailureDestinationDetails
from .none_provisioned_concurrency_config import NoneProvisionedConcurrencyConfig
from .none_success_destination_details import NoneSuccessDestinationDetails
from .notification_failure_destination_details import NotificationFailureDestinationDetails
from .notification_success_destination_details import NotificationSuccessDestinationDetails
from .object_storage_archive_source_details import ObjectStorageArchiveSourceDetails
from .pbf_listing import PbfListing
from .pbf_listing_summary import PbfListingSummary
from .pbf_listing_version import PbfListingVersion
from .pbf_listing_version_summary import PbfListingVersionSummary
from .pbf_listing_versions_collection import PbfListingVersionsCollection
from .pbf_listings_collection import PbfListingsCollection
from .policy_details import PolicyDetails
from .pre_built_function_source_details import PreBuiltFunctionSourceDetails
from .publisher_details import PublisherDetails
from .queue_failure_destination_details import QueueFailureDestinationDetails
from .queue_success_destination_details import QueueSuccessDestinationDetails
from .requirement_details import RequirementDetails
from .runtime_config import RuntimeConfig
from .stream_failure_destination_details import StreamFailureDestinationDetails
from .stream_success_destination_details import StreamSuccessDestinationDetails
from .success_destination_details import SuccessDestinationDetails
from .trigger import Trigger
from .trigger_summary import TriggerSummary
from .triggers_collection import TriggersCollection
from .update_application_details import UpdateApplicationDetails
from .update_archive_function_source_details import UpdateArchiveFunctionSourceDetails
from .update_archive_source_details import UpdateArchiveSourceDetails
from .update_container_image_function_source_details import UpdateContainerImageFunctionSourceDetails
from .update_direct_archive_source_details import UpdateDirectArchiveSourceDetails
from .update_function_details import UpdateFunctionDetails
from .update_function_source_details import UpdateFunctionSourceDetails
from .update_function_update_runtime_config import UpdateFunctionUpdateRuntimeConfig
from .update_manual_runtime_config import UpdateManualRuntimeConfig
from .update_object_storage_archive_source_details import UpdateObjectStorageArchiveSourceDetails
from .update_runtime_config import UpdateRuntimeConfig
from .work_request import WorkRequest
from .work_request_error import WorkRequestError
from .work_request_error_collection import WorkRequestErrorCollection
from .work_request_log_entry import WorkRequestLogEntry
from .work_request_log_entry_collection import WorkRequestLogEntryCollection
from .work_request_resource import WorkRequestResource
from .work_request_summary import WorkRequestSummary
from .work_request_summary_collection import WorkRequestSummaryCollection

# Maps type names to classes for functions services.
functions_type_mapping = {
    "Application": Application,
    "ApplicationLoggingConfig": ApplicationLoggingConfig,
    "ApplicationSummary": ApplicationSummary,
    "ApplicationTraceConfig": ApplicationTraceConfig,
    "ArchiveFunctionSourceDetails": ArchiveFunctionSourceDetails,
    "ArchiveSourceDetails": ArchiveSourceDetails,
    "ChangeApplicationCompartmentDetails": ChangeApplicationCompartmentDetails,
    "ConfigDetails": ConfigDetails,
    "ConstantProvisionedConcurrencyConfig": ConstantProvisionedConcurrencyConfig,
    "ContainerImageFunctionSourceDetails": ContainerImageFunctionSourceDetails,
    "CreateApplicationDetails": CreateApplicationDetails,
    "CreateArchiveFunctionSourceDetails": CreateArchiveFunctionSourceDetails,
    "CreateArchiveSourceDetails": CreateArchiveSourceDetails,
    "CreateContainerImageFunctionSourceDetails": CreateContainerImageFunctionSourceDetails,
    "CreateDirectArchiveSourceDetails": CreateDirectArchiveSourceDetails,
    "CreateFunctionDetails": CreateFunctionDetails,
    "CreateFunctionSourceDetails": CreateFunctionSourceDetails,
    "CreateFunctionUpdateRuntimeConfig": CreateFunctionUpdateRuntimeConfig,
    "CreateManualRuntimeConfig": CreateManualRuntimeConfig,
    "CreateObjectStorageArchiveSourceDetails": CreateObjectStorageArchiveSourceDetails,
    "CreatePreBuiltFunctionSourceDetails": CreatePreBuiltFunctionSourceDetails,
    "CreateRuntimeConfig": CreateRuntimeConfig,
    "DirectArchiveSourceDetails": DirectArchiveSourceDetails,
    "FailureDestinationDetails": FailureDestinationDetails,
    "Function": Function,
    "FunctionProvisionedConcurrencyConfig": FunctionProvisionedConcurrencyConfig,
    "FunctionSourceDetails": FunctionSourceDetails,
    "FunctionSummary": FunctionSummary,
    "FunctionTraceConfig": FunctionTraceConfig,
    "FunctionUpdateRuntimeConfig": FunctionUpdateRuntimeConfig,
    "FunctionsRuntime": FunctionsRuntime,
    "FunctionsRuntimeCollection": FunctionsRuntimeCollection,
    "FunctionsRuntimeSummary": FunctionsRuntimeSummary,
    "FunctionsRuntimeVersion": FunctionsRuntimeVersion,
    "FunctionsRuntimeVersionCollection": FunctionsRuntimeVersionCollection,
    "FunctionsRuntimeVersionSummary": FunctionsRuntimeVersionSummary,
    "ImagePolicyConfig": ImagePolicyConfig,
    "KeyDetails": KeyDetails,
    "ManualRuntimeConfig": ManualRuntimeConfig,
    "NoneFailureDestinationDetails": NoneFailureDestinationDetails,
    "NoneProvisionedConcurrencyConfig": NoneProvisionedConcurrencyConfig,
    "NoneSuccessDestinationDetails": NoneSuccessDestinationDetails,
    "NotificationFailureDestinationDetails": NotificationFailureDestinationDetails,
    "NotificationSuccessDestinationDetails": NotificationSuccessDestinationDetails,
    "ObjectStorageArchiveSourceDetails": ObjectStorageArchiveSourceDetails,
    "PbfListing": PbfListing,
    "PbfListingSummary": PbfListingSummary,
    "PbfListingVersion": PbfListingVersion,
    "PbfListingVersionSummary": PbfListingVersionSummary,
    "PbfListingVersionsCollection": PbfListingVersionsCollection,
    "PbfListingsCollection": PbfListingsCollection,
    "PolicyDetails": PolicyDetails,
    "PreBuiltFunctionSourceDetails": PreBuiltFunctionSourceDetails,
    "PublisherDetails": PublisherDetails,
    "QueueFailureDestinationDetails": QueueFailureDestinationDetails,
    "QueueSuccessDestinationDetails": QueueSuccessDestinationDetails,
    "RequirementDetails": RequirementDetails,
    "RuntimeConfig": RuntimeConfig,
    "StreamFailureDestinationDetails": StreamFailureDestinationDetails,
    "StreamSuccessDestinationDetails": StreamSuccessDestinationDetails,
    "SuccessDestinationDetails": SuccessDestinationDetails,
    "Trigger": Trigger,
    "TriggerSummary": TriggerSummary,
    "TriggersCollection": TriggersCollection,
    "UpdateApplicationDetails": UpdateApplicationDetails,
    "UpdateArchiveFunctionSourceDetails": UpdateArchiveFunctionSourceDetails,
    "UpdateArchiveSourceDetails": UpdateArchiveSourceDetails,
    "UpdateContainerImageFunctionSourceDetails": UpdateContainerImageFunctionSourceDetails,
    "UpdateDirectArchiveSourceDetails": UpdateDirectArchiveSourceDetails,
    "UpdateFunctionDetails": UpdateFunctionDetails,
    "UpdateFunctionSourceDetails": UpdateFunctionSourceDetails,
    "UpdateFunctionUpdateRuntimeConfig": UpdateFunctionUpdateRuntimeConfig,
    "UpdateManualRuntimeConfig": UpdateManualRuntimeConfig,
    "UpdateObjectStorageArchiveSourceDetails": UpdateObjectStorageArchiveSourceDetails,
    "UpdateRuntimeConfig": UpdateRuntimeConfig,
    "WorkRequest": WorkRequest,
    "WorkRequestError": WorkRequestError,
    "WorkRequestErrorCollection": WorkRequestErrorCollection,
    "WorkRequestLogEntry": WorkRequestLogEntry,
    "WorkRequestLogEntryCollection": WorkRequestLogEntryCollection,
    "WorkRequestResource": WorkRequestResource,
    "WorkRequestSummary": WorkRequestSummary,
    "WorkRequestSummaryCollection": WorkRequestSummaryCollection
}
