# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20260325

from .function_source_details import FunctionSourceDetails
from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class ContainerImageFunctionSourceDetails(FunctionSourceDetails):
    """
    Source details of a container image based function.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new ContainerImageFunctionSourceDetails object with values from keyword arguments. The default value of the :py:attr:`~oci.functions.models.ContainerImageFunctionSourceDetails.source_type` attribute
        of this class is ``CONTAINER_IMAGE`` and it should not be changed.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param source_type:
            The value to assign to the source_type property of this ContainerImageFunctionSourceDetails.
            Allowed values for this property are: "PRE_BUILT_FUNCTIONS", "ARCHIVE", "CONTAINER_IMAGE"
        :type source_type: str

        :param image:
            The value to assign to the image property of this ContainerImageFunctionSourceDetails.
        :type image: str

        :param image_digest:
            The value to assign to the image_digest property of this ContainerImageFunctionSourceDetails.
        :type image_digest: str

        """
        self.swagger_types = {
            'source_type': 'str',
            'image': 'str',
            'image_digest': 'str'
        }
        self.attribute_map = {
            'source_type': 'sourceType',
            'image': 'image',
            'image_digest': 'imageDigest'
        }
        self._source_type = None
        self._image = None
        self._image_digest = None
        self._source_type = 'CONTAINER_IMAGE'

    @property
    def image(self):
        """
        Gets the image of this ContainerImageFunctionSourceDetails.
        The qualified name of the Docker image to use in the function, including the image tag.
        The image should be in the OCI Registry that is in the same region as the function itself.
        Example: `phx.ocir.io/ten/functions/function:0.0.1`


        :return: The image of this ContainerImageFunctionSourceDetails.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """
        Sets the image of this ContainerImageFunctionSourceDetails.
        The qualified name of the Docker image to use in the function, including the image tag.
        The image should be in the OCI Registry that is in the same region as the function itself.
        Example: `phx.ocir.io/ten/functions/function:0.0.1`


        :param image: The image of this ContainerImageFunctionSourceDetails.
        :type: str
        """
        self._image = image

    @property
    def image_digest(self):
        """
        Gets the image_digest of this ContainerImageFunctionSourceDetails.
        The image digest for the version of the image that will be pulled when invoking this function.
        If no value is specified, the digest currently associated with the image in the OCI Registry will be used.
        Example: `sha256:ca0eeb6fb05351dfc8759c20733c91def84cb8007aa89a5bf606bc8b315b9fc7`


        :return: The image_digest of this ContainerImageFunctionSourceDetails.
        :rtype: str
        """
        return self._image_digest

    @image_digest.setter
    def image_digest(self, image_digest):
        """
        Sets the image_digest of this ContainerImageFunctionSourceDetails.
        The image digest for the version of the image that will be pulled when invoking this function.
        If no value is specified, the digest currently associated with the image in the OCI Registry will be used.
        Example: `sha256:ca0eeb6fb05351dfc8759c20733c91def84cb8007aa89a5bf606bc8b315b9fc7`


        :param image_digest: The image_digest of this ContainerImageFunctionSourceDetails.
        :type: str
        """
        self._image_digest = image_digest

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
