# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20260325

from .update_function_source_details import UpdateFunctionSourceDetails
from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class UpdateArchiveFunctionSourceDetails(UpdateFunctionSourceDetails):
    """
    Source details for updating an archive\u2011based function.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new UpdateArchiveFunctionSourceDetails object with values from keyword arguments. The default value of the :py:attr:`~oci.functions.models.UpdateArchiveFunctionSourceDetails.source_type` attribute
        of this class is ``ARCHIVE`` and it should not be changed.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param source_type:
            The value to assign to the source_type property of this UpdateArchiveFunctionSourceDetails.
            Allowed values for this property are: "ARCHIVE", "CONTAINER_IMAGE"
        :type source_type: str

        :param archive_source_details:
            The value to assign to the archive_source_details property of this UpdateArchiveFunctionSourceDetails.
        :type archive_source_details: oci.functions.models.UpdateArchiveSourceDetails

        :param handler:
            The value to assign to the handler property of this UpdateArchiveFunctionSourceDetails.
        :type handler: str

        :param runtime_config:
            The value to assign to the runtime_config property of this UpdateArchiveFunctionSourceDetails.
        :type runtime_config: oci.functions.models.UpdateRuntimeConfig

        """
        self.swagger_types = {
            'source_type': 'str',
            'archive_source_details': 'UpdateArchiveSourceDetails',
            'handler': 'str',
            'runtime_config': 'UpdateRuntimeConfig'
        }
        self.attribute_map = {
            'source_type': 'sourceType',
            'archive_source_details': 'archiveSourceDetails',
            'handler': 'handler',
            'runtime_config': 'runtimeConfig'
        }
        self._source_type = None
        self._archive_source_details = None
        self._handler = None
        self._runtime_config = None
        self._source_type = 'ARCHIVE'

    @property
    def archive_source_details(self):
        """
        Gets the archive_source_details of this UpdateArchiveFunctionSourceDetails.

        :return: The archive_source_details of this UpdateArchiveFunctionSourceDetails.
        :rtype: oci.functions.models.UpdateArchiveSourceDetails
        """
        return self._archive_source_details

    @archive_source_details.setter
    def archive_source_details(self, archive_source_details):
        """
        Sets the archive_source_details of this UpdateArchiveFunctionSourceDetails.

        :param archive_source_details: The archive_source_details of this UpdateArchiveFunctionSourceDetails.
        :type: oci.functions.models.UpdateArchiveSourceDetails
        """
        self._archive_source_details = archive_source_details

    @property
    def handler(self):
        """
        Gets the handler of this UpdateArchiveFunctionSourceDetails.
        The function handler that is executed when the function is invoked. The value of this field depends on the runtime used


        :return: The handler of this UpdateArchiveFunctionSourceDetails.
        :rtype: str
        """
        return self._handler

    @handler.setter
    def handler(self, handler):
        """
        Sets the handler of this UpdateArchiveFunctionSourceDetails.
        The function handler that is executed when the function is invoked. The value of this field depends on the runtime used


        :param handler: The handler of this UpdateArchiveFunctionSourceDetails.
        :type: str
        """
        self._handler = handler

    @property
    def runtime_config(self):
        """
        Gets the runtime_config of this UpdateArchiveFunctionSourceDetails.

        :return: The runtime_config of this UpdateArchiveFunctionSourceDetails.
        :rtype: oci.functions.models.UpdateRuntimeConfig
        """
        return self._runtime_config

    @runtime_config.setter
    def runtime_config(self, runtime_config):
        """
        Sets the runtime_config of this UpdateArchiveFunctionSourceDetails.

        :param runtime_config: The runtime_config of this UpdateArchiveFunctionSourceDetails.
        :type: oci.functions.models.UpdateRuntimeConfig
        """
        self._runtime_config = runtime_config

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
