# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20260325


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class UpdateRuntimeConfig(object):
    """
    FunctionsRuntime configuration used to update a function.
    """

    #: A constant which can be used with the runtime_config_type property of a UpdateRuntimeConfig.
    #: This constant has a value of "FUNCTION_UPDATE"
    RUNTIME_CONFIG_TYPE_FUNCTION_UPDATE = "FUNCTION_UPDATE"

    #: A constant which can be used with the runtime_config_type property of a UpdateRuntimeConfig.
    #: This constant has a value of "MANUAL"
    RUNTIME_CONFIG_TYPE_MANUAL = "MANUAL"

    def __init__(self, **kwargs):
        """
        Initializes a new UpdateRuntimeConfig object with values from keyword arguments. This class has the following subclasses and if you are using this class as input
        to a service operations then you should favor using a subclass over the base class:

        * :class:`~oci.functions.models.UpdateManualRuntimeConfig`
        * :class:`~oci.functions.models.UpdateFunctionUpdateRuntimeConfig`

        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param runtime_config_type:
            The value to assign to the runtime_config_type property of this UpdateRuntimeConfig.
            Allowed values for this property are: "FUNCTION_UPDATE", "MANUAL"
        :type runtime_config_type: str

        """
        self.swagger_types = {
            'runtime_config_type': 'str'
        }
        self.attribute_map = {
            'runtime_config_type': 'runtimeConfigType'
        }
        self._runtime_config_type = None

    @staticmethod
    def get_subtype(object_dictionary):
        """
        Given the hash representation of a subtype of this class,
        use the info in the hash to return the class of the subtype.
        """
        type = object_dictionary['runtimeConfigType']

        if type == 'MANUAL':
            return 'UpdateManualRuntimeConfig'

        if type == 'FUNCTION_UPDATE':
            return 'UpdateFunctionUpdateRuntimeConfig'
        else:
            return 'UpdateRuntimeConfig'

    @property
    def runtime_config_type(self):
        """
        **[Required]** Gets the runtime_config_type of this UpdateRuntimeConfig.
        Type of the FunctionsRuntime Config. Possible values: FUNCTION_UPDATE and MANUAL.

        Allowed values for this property are: "FUNCTION_UPDATE", "MANUAL"


        :return: The runtime_config_type of this UpdateRuntimeConfig.
        :rtype: str
        """
        return self._runtime_config_type

    @runtime_config_type.setter
    def runtime_config_type(self, runtime_config_type):
        """
        Sets the runtime_config_type of this UpdateRuntimeConfig.
        Type of the FunctionsRuntime Config. Possible values: FUNCTION_UPDATE and MANUAL.


        :param runtime_config_type: The runtime_config_type of this UpdateRuntimeConfig.
        :type: str
        """
        allowed_values = ["FUNCTION_UPDATE", "MANUAL"]
        if not value_allowed_none_or_none_sentinel(runtime_config_type, allowed_values):
            raise ValueError(
                f"Invalid value for `runtime_config_type`, must be None or one of {allowed_values}"
            )
        self._runtime_config_type = runtime_config_type

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
