# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20260325

from .update_runtime_config import UpdateRuntimeConfig
from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class UpdateManualRuntimeConfig(UpdateRuntimeConfig):
    """
    FunctionsRuntime configuration for updating a function with 'MANUAL' Runtime Update strategy.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new UpdateManualRuntimeConfig object with values from keyword arguments. The default value of the :py:attr:`~oci.functions.models.UpdateManualRuntimeConfig.runtime_config_type` attribute
        of this class is ``MANUAL`` and it should not be changed.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param runtime_config_type:
            The value to assign to the runtime_config_type property of this UpdateManualRuntimeConfig.
            Allowed values for this property are: "FUNCTION_UPDATE", "MANUAL"
        :type runtime_config_type: str

        :param functions_runtime_name:
            The value to assign to the functions_runtime_name property of this UpdateManualRuntimeConfig.
        :type functions_runtime_name: str

        :param functions_runtime_version_id:
            The value to assign to the functions_runtime_version_id property of this UpdateManualRuntimeConfig.
        :type functions_runtime_version_id: str

        """
        self.swagger_types = {
            'runtime_config_type': 'str',
            'functions_runtime_name': 'str',
            'functions_runtime_version_id': 'str'
        }
        self.attribute_map = {
            'runtime_config_type': 'runtimeConfigType',
            'functions_runtime_name': 'functionsRuntimeName',
            'functions_runtime_version_id': 'functionsRuntimeVersionId'
        }
        self._runtime_config_type = None
        self._functions_runtime_name = None
        self._functions_runtime_version_id = None
        self._runtime_config_type = 'MANUAL'

    @property
    def functions_runtime_name(self):
        """
        Gets the functions_runtime_name of this UpdateManualRuntimeConfig.
        The name of the FunctionsRuntime this function is to be associated with.


        :return: The functions_runtime_name of this UpdateManualRuntimeConfig.
        :rtype: str
        """
        return self._functions_runtime_name

    @functions_runtime_name.setter
    def functions_runtime_name(self, functions_runtime_name):
        """
        Sets the functions_runtime_name of this UpdateManualRuntimeConfig.
        The name of the FunctionsRuntime this function is to be associated with.


        :param functions_runtime_name: The functions_runtime_name of this UpdateManualRuntimeConfig.
        :type: str
        """
        self._functions_runtime_name = functions_runtime_name

    @property
    def functions_runtime_version_id(self):
        """
        **[Required]** Gets the functions_runtime_version_id of this UpdateManualRuntimeConfig.
        The OCID of the FunctionsRuntimeVersion to use for the Function in manual mode.


        :return: The functions_runtime_version_id of this UpdateManualRuntimeConfig.
        :rtype: str
        """
        return self._functions_runtime_version_id

    @functions_runtime_version_id.setter
    def functions_runtime_version_id(self, functions_runtime_version_id):
        """
        Sets the functions_runtime_version_id of this UpdateManualRuntimeConfig.
        The OCID of the FunctionsRuntimeVersion to use for the Function in manual mode.


        :param functions_runtime_version_id: The functions_runtime_version_id of this UpdateManualRuntimeConfig.
        :type: str
        """
        self._functions_runtime_version_id = functions_runtime_version_id

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
