# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20241201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class AdminPublisherSku(object):
    """
    Sku details for private offers
    """

    def __init__(self, **kwargs):
        """
        Initializes a new AdminPublisherSku object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param product_code:
            The value to assign to the product_code property of this AdminPublisherSku.
        :type product_code: str

        :param description:
            The value to assign to the description property of this AdminPublisherSku.
        :type description: str

        :param meter:
            The value to assign to the meter property of this AdminPublisherSku.
        :type meter: str

        :param rates:
            The value to assign to the rates property of this AdminPublisherSku.
        :type rates: list[oci.marketplace_publisher.models.AdminSkuPricingRate]

        """
        self.swagger_types = {
            'product_code': 'str',
            'description': 'str',
            'meter': 'str',
            'rates': 'list[AdminSkuPricingRate]'
        }
        self.attribute_map = {
            'product_code': 'productCode',
            'description': 'description',
            'meter': 'meter',
            'rates': 'rates'
        }
        self._product_code = None
        self._description = None
        self._meter = None
        self._rates = None

    @property
    def product_code(self):
        """
        **[Required]** Gets the product_code of this AdminPublisherSku.
        Sku name


        :return: The product_code of this AdminPublisherSku.
        :rtype: str
        """
        return self._product_code

    @product_code.setter
    def product_code(self, product_code):
        """
        Sets the product_code of this AdminPublisherSku.
        Sku name


        :param product_code: The product_code of this AdminPublisherSku.
        :type: str
        """
        self._product_code = product_code

    @property
    def description(self):
        """
        **[Required]** Gets the description of this AdminPublisherSku.
        Sku description


        :return: The description of this AdminPublisherSku.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this AdminPublisherSku.
        Sku description


        :param description: The description of this AdminPublisherSku.
        :type: str
        """
        self._description = description

    @property
    def meter(self):
        """
        Gets the meter of this AdminPublisherSku.
        The meter of the SKU.


        :return: The meter of this AdminPublisherSku.
        :rtype: str
        """
        return self._meter

    @meter.setter
    def meter(self, meter):
        """
        Sets the meter of this AdminPublisherSku.
        The meter of the SKU.


        :param meter: The meter of this AdminPublisherSku.
        :type: str
        """
        self._meter = meter

    @property
    def rates(self):
        """
        **[Required]** Gets the rates of this AdminPublisherSku.
        List of pricing rates for listing


        :return: The rates of this AdminPublisherSku.
        :rtype: list[oci.marketplace_publisher.models.AdminSkuPricingRate]
        """
        return self._rates

    @rates.setter
    def rates(self, rates):
        """
        Sets the rates of this AdminPublisherSku.
        List of pricing rates for listing


        :param rates: The rates of this AdminPublisherSku.
        :type: list[oci.marketplace_publisher.models.AdminSkuPricingRate]
        """
        self._rates = rates

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
