# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20241201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class AdminListing(object):
    """
    The model for the Admin Marketplace Publisher listing.
    """

    #: A constant which can be used with the listing_type property of a AdminListing.
    #: This constant has a value of "OCI_APPLICATION"
    LISTING_TYPE_OCI_APPLICATION = "OCI_APPLICATION"

    #: A constant which can be used with the listing_type property of a AdminListing.
    #: This constant has a value of "LEAD_GENERATION"
    LISTING_TYPE_LEAD_GENERATION = "LEAD_GENERATION"

    #: A constant which can be used with the listing_type property of a AdminListing.
    #: This constant has a value of "SERVICE"
    LISTING_TYPE_SERVICE = "SERVICE"

    #: A constant which can be used with the package_type property of a AdminListing.
    #: This constant has a value of "CONTAINER_IMAGE"
    PACKAGE_TYPE_CONTAINER_IMAGE = "CONTAINER_IMAGE"

    #: A constant which can be used with the package_type property of a AdminListing.
    #: This constant has a value of "HELM_CHART"
    PACKAGE_TYPE_HELM_CHART = "HELM_CHART"

    #: A constant which can be used with the package_type property of a AdminListing.
    #: This constant has a value of "MACHINE_IMAGE"
    PACKAGE_TYPE_MACHINE_IMAGE = "MACHINE_IMAGE"

    #: A constant which can be used with the package_type property of a AdminListing.
    #: This constant has a value of "STACK"
    PACKAGE_TYPE_STACK = "STACK"

    #: A constant which can be used with the package_type property of a AdminListing.
    #: This constant has a value of "NONE"
    PACKAGE_TYPE_NONE = "NONE"

    def __init__(self, **kwargs):
        """
        Initializes a new AdminListing object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param id:
            The value to assign to the id property of this AdminListing.
        :type id: str

        :param legacy_id:
            The value to assign to the legacy_id property of this AdminListing.
        :type legacy_id: str

        :param compartment_id:
            The value to assign to the compartment_id property of this AdminListing.
        :type compartment_id: str

        :param publisher_id:
            The value to assign to the publisher_id property of this AdminListing.
        :type publisher_id: str

        :param listing_type:
            The value to assign to the listing_type property of this AdminListing.
            Allowed values for this property are: "OCI_APPLICATION", "LEAD_GENERATION", "SERVICE", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type listing_type: str

        :param name:
            The value to assign to the name property of this AdminListing.
        :type name: str

        :param package_type:
            The value to assign to the package_type property of this AdminListing.
            Allowed values for this property are: "CONTAINER_IMAGE", "HELM_CHART", "MACHINE_IMAGE", "STACK", "NONE", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type package_type: str

        :param extended_metadata:
            The value to assign to the extended_metadata property of this AdminListing.
        :type extended_metadata: dict(str, str)

        :param lifecycle_state:
            The value to assign to the lifecycle_state property of this AdminListing.
        :type lifecycle_state: str

        :param parts:
            The value to assign to the parts property of this AdminListing.
        :type parts: list[oci.marketplace_publisher.models.ListingPart]

        :param time_created:
            The value to assign to the time_created property of this AdminListing.
        :type time_created: datetime

        :param time_updated:
            The value to assign to the time_updated property of this AdminListing.
        :type time_updated: datetime

        :param is_featured:
            The value to assign to the is_featured property of this AdminListing.
        :type is_featured: bool

        :param freeform_tags:
            The value to assign to the freeform_tags property of this AdminListing.
        :type freeform_tags: dict(str, str)

        :param defined_tags:
            The value to assign to the defined_tags property of this AdminListing.
        :type defined_tags: dict(str, dict(str, object))

        :param system_tags:
            The value to assign to the system_tags property of this AdminListing.
        :type system_tags: dict(str, dict(str, object))

        """
        self.swagger_types = {
            'id': 'str',
            'legacy_id': 'str',
            'compartment_id': 'str',
            'publisher_id': 'str',
            'listing_type': 'str',
            'name': 'str',
            'package_type': 'str',
            'extended_metadata': 'dict(str, str)',
            'lifecycle_state': 'str',
            'parts': 'list[ListingPart]',
            'time_created': 'datetime',
            'time_updated': 'datetime',
            'is_featured': 'bool',
            'freeform_tags': 'dict(str, str)',
            'defined_tags': 'dict(str, dict(str, object))',
            'system_tags': 'dict(str, dict(str, object))'
        }
        self.attribute_map = {
            'id': 'id',
            'legacy_id': 'legacyId',
            'compartment_id': 'compartmentId',
            'publisher_id': 'publisherId',
            'listing_type': 'listingType',
            'name': 'name',
            'package_type': 'packageType',
            'extended_metadata': 'extendedMetadata',
            'lifecycle_state': 'lifecycleState',
            'parts': 'parts',
            'time_created': 'timeCreated',
            'time_updated': 'timeUpdated',
            'is_featured': 'isFeatured',
            'freeform_tags': 'freeformTags',
            'defined_tags': 'definedTags',
            'system_tags': 'systemTags'
        }
        self._id = None
        self._legacy_id = None
        self._compartment_id = None
        self._publisher_id = None
        self._listing_type = None
        self._name = None
        self._package_type = None
        self._extended_metadata = None
        self._lifecycle_state = None
        self._parts = None
        self._time_created = None
        self._time_updated = None
        self._is_featured = None
        self._freeform_tags = None
        self._defined_tags = None
        self._system_tags = None

    @property
    def id(self):
        """
        **[Required]** Gets the id of this AdminListing.
        Unique OCID identifier for the listing.


        :return: The id of this AdminListing.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this AdminListing.
        Unique OCID identifier for the listing.


        :param id: The id of this AdminListing.
        :type: str
        """
        self._id = id

    @property
    def legacy_id(self):
        """
        Gets the legacy_id of this AdminListing.
        The unique legacy identifier for the listing.


        :return: The legacy_id of this AdminListing.
        :rtype: str
        """
        return self._legacy_id

    @legacy_id.setter
    def legacy_id(self, legacy_id):
        """
        Sets the legacy_id of this AdminListing.
        The unique legacy identifier for the listing.


        :param legacy_id: The legacy_id of this AdminListing.
        :type: str
        """
        self._legacy_id = legacy_id

    @property
    def compartment_id(self):
        """
        **[Required]** Gets the compartment_id of this AdminListing.
        The unique identifier for the compartment.


        :return: The compartment_id of this AdminListing.
        :rtype: str
        """
        return self._compartment_id

    @compartment_id.setter
    def compartment_id(self, compartment_id):
        """
        Sets the compartment_id of this AdminListing.
        The unique identifier for the compartment.


        :param compartment_id: The compartment_id of this AdminListing.
        :type: str
        """
        self._compartment_id = compartment_id

    @property
    def publisher_id(self):
        """
        **[Required]** Gets the publisher_id of this AdminListing.
        The unique identifier for the publisher.


        :return: The publisher_id of this AdminListing.
        :rtype: str
        """
        return self._publisher_id

    @publisher_id.setter
    def publisher_id(self, publisher_id):
        """
        Sets the publisher_id of this AdminListing.
        The unique identifier for the publisher.


        :param publisher_id: The publisher_id of this AdminListing.
        :type: str
        """
        self._publisher_id = publisher_id

    @property
    def listing_type(self):
        """
        **[Required]** Gets the listing_type of this AdminListing.
        The listing type for the listing.

        Allowed values for this property are: "OCI_APPLICATION", "LEAD_GENERATION", "SERVICE", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The listing_type of this AdminListing.
        :rtype: str
        """
        return self._listing_type

    @listing_type.setter
    def listing_type(self, listing_type):
        """
        Sets the listing_type of this AdminListing.
        The listing type for the listing.


        :param listing_type: The listing_type of this AdminListing.
        :type: str
        """
        allowed_values = ["OCI_APPLICATION", "LEAD_GENERATION", "SERVICE"]
        if not value_allowed_none_or_none_sentinel(listing_type, allowed_values):
            listing_type = 'UNKNOWN_ENUM_VALUE'
        self._listing_type = listing_type

    @property
    def name(self):
        """
        **[Required]** Gets the name of this AdminListing.
        Name for the listing.


        :return: The name of this AdminListing.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this AdminListing.
        Name for the listing.


        :param name: The name of this AdminListing.
        :type: str
        """
        self._name = name

    @property
    def package_type(self):
        """
        **[Required]** Gets the package_type of this AdminListing.
        The package type for the listing.

        Allowed values for this property are: "CONTAINER_IMAGE", "HELM_CHART", "MACHINE_IMAGE", "STACK", "NONE", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The package_type of this AdminListing.
        :rtype: str
        """
        return self._package_type

    @package_type.setter
    def package_type(self, package_type):
        """
        Sets the package_type of this AdminListing.
        The package type for the listing.


        :param package_type: The package_type of this AdminListing.
        :type: str
        """
        allowed_values = ["CONTAINER_IMAGE", "HELM_CHART", "MACHINE_IMAGE", "STACK", "NONE"]
        if not value_allowed_none_or_none_sentinel(package_type, allowed_values):
            package_type = 'UNKNOWN_ENUM_VALUE'
        self._package_type = package_type

    @property
    def extended_metadata(self):
        """
        Gets the extended_metadata of this AdminListing.
        Additional metadata key/value pairs for the listing summary.

        For example:

        `{\"listingRevisionStatus\": \"Published\",\"listingRevision\": \"1\" }`


        :return: The extended_metadata of this AdminListing.
        :rtype: dict(str, str)
        """
        return self._extended_metadata

    @extended_metadata.setter
    def extended_metadata(self, extended_metadata):
        """
        Sets the extended_metadata of this AdminListing.
        Additional metadata key/value pairs for the listing summary.

        For example:

        `{\"listingRevisionStatus\": \"Published\",\"listingRevision\": \"1\" }`


        :param extended_metadata: The extended_metadata of this AdminListing.
        :type: dict(str, str)
        """
        self._extended_metadata = extended_metadata

    @property
    def lifecycle_state(self):
        """
        **[Required]** Gets the lifecycle_state of this AdminListing.
        The current state of the listing revision.


        :return: The lifecycle_state of this AdminListing.
        :rtype: str
        """
        return self._lifecycle_state

    @lifecycle_state.setter
    def lifecycle_state(self, lifecycle_state):
        """
        Sets the lifecycle_state of this AdminListing.
        The current state of the listing revision.


        :param lifecycle_state: The lifecycle_state of this AdminListing.
        :type: str
        """
        self._lifecycle_state = lifecycle_state

    @property
    def parts(self):
        """
        Gets the parts of this AdminListing.
        List of parts provider by marketplace admin.


        :return: The parts of this AdminListing.
        :rtype: list[oci.marketplace_publisher.models.ListingPart]
        """
        return self._parts

    @parts.setter
    def parts(self, parts):
        """
        Sets the parts of this AdminListing.
        List of parts provider by marketplace admin.


        :param parts: The parts of this AdminListing.
        :type: list[oci.marketplace_publisher.models.ListingPart]
        """
        self._parts = parts

    @property
    def time_created(self):
        """
        **[Required]** Gets the time_created of this AdminListing.
        The date and time the listing was created, in the format defined by `RFC3339`__.

        Example: `2023-03-27T21:10:29.600Z`

        __ https://tools.ietf.org/html/rfc3339


        :return: The time_created of this AdminListing.
        :rtype: datetime
        """
        return self._time_created

    @time_created.setter
    def time_created(self, time_created):
        """
        Sets the time_created of this AdminListing.
        The date and time the listing was created, in the format defined by `RFC3339`__.

        Example: `2023-03-27T21:10:29.600Z`

        __ https://tools.ietf.org/html/rfc3339


        :param time_created: The time_created of this AdminListing.
        :type: datetime
        """
        self._time_created = time_created

    @property
    def time_updated(self):
        """
        **[Required]** Gets the time_updated of this AdminListing.
        The date and time the listing was updated, in the format defined by `RFC3339`__.

        Example: `2023-03-27T21:10:29.600Z`

        __ https://tools.ietf.org/html/rfc3339


        :return: The time_updated of this AdminListing.
        :rtype: datetime
        """
        return self._time_updated

    @time_updated.setter
    def time_updated(self, time_updated):
        """
        Sets the time_updated of this AdminListing.
        The date and time the listing was updated, in the format defined by `RFC3339`__.

        Example: `2023-03-27T21:10:29.600Z`

        __ https://tools.ietf.org/html/rfc3339


        :param time_updated: The time_updated of this AdminListing.
        :type: datetime
        """
        self._time_updated = time_updated

    @property
    def is_featured(self):
        """
        Gets the is_featured of this AdminListing.
        Indicates whether the listing is featured.


        :return: The is_featured of this AdminListing.
        :rtype: bool
        """
        return self._is_featured

    @is_featured.setter
    def is_featured(self, is_featured):
        """
        Sets the is_featured of this AdminListing.
        Indicates whether the listing is featured.


        :param is_featured: The is_featured of this AdminListing.
        :type: bool
        """
        self._is_featured = is_featured

    @property
    def freeform_tags(self):
        """
        Gets the freeform_tags of this AdminListing.
        Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
        Example: `{\"bar-key\": \"value\"}`


        :return: The freeform_tags of this AdminListing.
        :rtype: dict(str, str)
        """
        return self._freeform_tags

    @freeform_tags.setter
    def freeform_tags(self, freeform_tags):
        """
        Sets the freeform_tags of this AdminListing.
        Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
        Example: `{\"bar-key\": \"value\"}`


        :param freeform_tags: The freeform_tags of this AdminListing.
        :type: dict(str, str)
        """
        self._freeform_tags = freeform_tags

    @property
    def defined_tags(self):
        """
        Gets the defined_tags of this AdminListing.
        Defined tags for this resource. Each key is predefined and scoped to a namespace.
        Example: `{\"foo-namespace\": {\"bar-key\": \"value\"}}`


        :return: The defined_tags of this AdminListing.
        :rtype: dict(str, dict(str, object))
        """
        return self._defined_tags

    @defined_tags.setter
    def defined_tags(self, defined_tags):
        """
        Sets the defined_tags of this AdminListing.
        Defined tags for this resource. Each key is predefined and scoped to a namespace.
        Example: `{\"foo-namespace\": {\"bar-key\": \"value\"}}`


        :param defined_tags: The defined_tags of this AdminListing.
        :type: dict(str, dict(str, object))
        """
        self._defined_tags = defined_tags

    @property
    def system_tags(self):
        """
        Gets the system_tags of this AdminListing.
        System tags for this resource. Each key is predefined and scoped to a namespace.
        Example: `{\"orcl-cloud\": {\"free-tier-retained\": \"true\"}}`


        :return: The system_tags of this AdminListing.
        :rtype: dict(str, dict(str, object))
        """
        return self._system_tags

    @system_tags.setter
    def system_tags(self, system_tags):
        """
        Sets the system_tags of this AdminListing.
        System tags for this resource. Each key is predefined and scoped to a namespace.
        Example: `{\"orcl-cloud\": {\"free-tier-retained\": \"true\"}}`


        :param system_tags: The system_tags of this AdminListing.
        :type: dict(str, dict(str, object))
        """
        self._system_tags = system_tags

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
