# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20241201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class AdminListingProduct(object):
    """
    Products associated with listing.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new AdminListingProduct object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param code:
            The value to assign to the code property of this AdminListingProduct.
        :type code: str

        :param categories:
            The value to assign to the categories property of this AdminListingProduct.
        :type categories: list[str]

        :param product_group:
            The value to assign to the product_group property of this AdminListingProduct.
        :type product_group: str

        :param product_name:
            The value to assign to the product_name property of this AdminListingProduct.
        :type product_name: str

        :param additional_filters:
            The value to assign to the additional_filters property of this AdminListingProduct.
        :type additional_filters: list[oci.marketplace_publisher.models.ListingProductAdditionalFilter]

        """
        self.swagger_types = {
            'code': 'str',
            'categories': 'list[str]',
            'product_group': 'str',
            'product_name': 'str',
            'additional_filters': 'list[ListingProductAdditionalFilter]'
        }
        self.attribute_map = {
            'code': 'code',
            'categories': 'categories',
            'product_group': 'productGroup',
            'product_name': 'productName',
            'additional_filters': 'additionalFilters'
        }
        self._code = None
        self._categories = None
        self._product_group = None
        self._product_name = None
        self._additional_filters = None

    @property
    def code(self):
        """
        Gets the code of this AdminListingProduct.
        Product Code


        :return: The code of this AdminListingProduct.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this AdminListingProduct.
        Product Code


        :param code: The code of this AdminListingProduct.
        :type: str
        """
        self._code = code

    @property
    def categories(self):
        """
        Gets the categories of this AdminListingProduct.
        List of category codes within a Product which are applicable to the listing revision.


        :return: The categories of this AdminListingProduct.
        :rtype: list[str]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """
        Sets the categories of this AdminListingProduct.
        List of category codes within a Product which are applicable to the listing revision.


        :param categories: The categories of this AdminListingProduct.
        :type: list[str]
        """
        self._categories = categories

    @property
    def product_group(self):
        """
        Gets the product_group of this AdminListingProduct.
        The product group for the product.


        :return: The product_group of this AdminListingProduct.
        :rtype: str
        """
        return self._product_group

    @product_group.setter
    def product_group(self, product_group):
        """
        Sets the product_group of this AdminListingProduct.
        The product group for the product.


        :param product_group: The product_group of this AdminListingProduct.
        :type: str
        """
        self._product_group = product_group

    @property
    def product_name(self):
        """
        Gets the product_name of this AdminListingProduct.
        The product name for the product.


        :return: The product_name of this AdminListingProduct.
        :rtype: str
        """
        return self._product_name

    @product_name.setter
    def product_name(self, product_name):
        """
        Sets the product_name of this AdminListingProduct.
        The product name for the product.


        :param product_name: The product_name of this AdminListingProduct.
        :type: str
        """
        self._product_name = product_name

    @property
    def additional_filters(self):
        """
        Gets the additional_filters of this AdminListingProduct.
        Custom filter for the product


        :return: The additional_filters of this AdminListingProduct.
        :rtype: list[oci.marketplace_publisher.models.ListingProductAdditionalFilter]
        """
        return self._additional_filters

    @additional_filters.setter
    def additional_filters(self, additional_filters):
        """
        Sets the additional_filters of this AdminListingProduct.
        Custom filter for the product


        :param additional_filters: The additional_filters of this AdminListingProduct.
        :type: list[oci.marketplace_publisher.models.ListingProductAdditionalFilter]
        """
        self._additional_filters = additional_filters

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
