# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20241201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class AdminSkuPricingRate(object):
    """
    A pricing plan rate for listing sku.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new AdminSkuPricingRate object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param currency_code:
            The value to assign to the currency_code property of this AdminSkuPricingRate.
        :type currency_code: str

        :param unit_price:
            The value to assign to the unit_price property of this AdminSkuPricingRate.
        :type unit_price: float

        """
        self.swagger_types = {
            'currency_code': 'str',
            'unit_price': 'float'
        }
        self.attribute_map = {
            'currency_code': 'currencyCode',
            'unit_price': 'unitPrice'
        }
        self._currency_code = None
        self._unit_price = None

    @property
    def currency_code(self):
        """
        **[Required]** Gets the currency_code of this AdminSkuPricingRate.
        The currency supported, in the format specified by ISO-4217


        :return: The currency_code of this AdminSkuPricingRate.
        :rtype: str
        """
        return self._currency_code

    @currency_code.setter
    def currency_code(self, currency_code):
        """
        Sets the currency_code of this AdminSkuPricingRate.
        The currency supported, in the format specified by ISO-4217


        :param currency_code: The currency_code of this AdminSkuPricingRate.
        :type: str
        """
        self._currency_code = currency_code

    @property
    def unit_price(self):
        """
        **[Required]** Gets the unit_price of this AdminSkuPricingRate.
        The amount for the currency type.


        :return: The unit_price of this AdminSkuPricingRate.
        :rtype: float
        """
        return self._unit_price

    @unit_price.setter
    def unit_price(self, unit_price):
        """
        Sets the unit_price of this AdminSkuPricingRate.
        The amount for the currency type.


        :param unit_price: The unit_price of this AdminSkuPricingRate.
        :type: float
        """
        self._unit_price = unit_price

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
