# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20241201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class AdminOpnPartnerSummary(object):
    """
    OPN partner summary.
    """

    #: A constant which can be used with the membership_status property of a AdminOpnPartnerSummary.
    #: This constant has a value of "ACTIVE"
    MEMBERSHIP_STATUS_ACTIVE = "ACTIVE"

    #: A constant which can be used with the membership_status property of a AdminOpnPartnerSummary.
    #: This constant has a value of "INACTIVE"
    MEMBERSHIP_STATUS_INACTIVE = "INACTIVE"

    #: A constant which can be used with the membership_status property of a AdminOpnPartnerSummary.
    #: This constant has a value of "RENEWAL_IN_PROGRESS"
    MEMBERSHIP_STATUS_RENEWAL_IN_PROGRESS = "RENEWAL_IN_PROGRESS"

    def __init__(self, **kwargs):
        """
        Initializes a new AdminOpnPartnerSummary object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param company_id:
            The value to assign to the company_id property of this AdminOpnPartnerSummary.
        :type company_id: str

        :param partner_name:
            The value to assign to the partner_name property of this AdminOpnPartnerSummary.
        :type partner_name: str

        :param level_program_name:
            The value to assign to the level_program_name property of this AdminOpnPartnerSummary.
        :type level_program_name: str

        :param start_date:
            The value to assign to the start_date property of this AdminOpnPartnerSummary.
        :type start_date: str

        :param end_date:
            The value to assign to the end_date property of this AdminOpnPartnerSummary.
        :type end_date: str

        :param membership_status:
            The value to assign to the membership_status property of this AdminOpnPartnerSummary.
            Allowed values for this property are: "ACTIVE", "INACTIVE", "RENEWAL_IN_PROGRESS", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type membership_status: str

        :param membership_type:
            The value to assign to the membership_type property of this AdminOpnPartnerSummary.
        :type membership_type: str

        :param street_address1:
            The value to assign to the street_address1 property of this AdminOpnPartnerSummary.
        :type street_address1: str

        :param street_address2:
            The value to assign to the street_address2 property of this AdminOpnPartnerSummary.
        :type street_address2: str

        :param city:
            The value to assign to the city property of this AdminOpnPartnerSummary.
        :type city: str

        :param state:
            The value to assign to the state property of this AdminOpnPartnerSummary.
        :type state: str

        :param zipcode:
            The value to assign to the zipcode property of this AdminOpnPartnerSummary.
        :type zipcode: str

        :param country:
            The value to assign to the country property of this AdminOpnPartnerSummary.
        :type country: str

        :param phone_number:
            The value to assign to the phone_number property of this AdminOpnPartnerSummary.
        :type phone_number: str

        :param partner_url:
            The value to assign to the partner_url property of this AdminOpnPartnerSummary.
        :type partner_url: str

        :param number_of_employees:
            The value to assign to the number_of_employees property of this AdminOpnPartnerSummary.
        :type number_of_employees: str

        :param last_updated:
            The value to assign to the last_updated property of this AdminOpnPartnerSummary.
        :type last_updated: str

        :param freeform_tags:
            The value to assign to the freeform_tags property of this AdminOpnPartnerSummary.
        :type freeform_tags: dict(str, str)

        :param defined_tags:
            The value to assign to the defined_tags property of this AdminOpnPartnerSummary.
        :type defined_tags: dict(str, dict(str, object))

        :param system_tags:
            The value to assign to the system_tags property of this AdminOpnPartnerSummary.
        :type system_tags: dict(str, dict(str, object))

        """
        self.swagger_types = {
            'company_id': 'str',
            'partner_name': 'str',
            'level_program_name': 'str',
            'start_date': 'str',
            'end_date': 'str',
            'membership_status': 'str',
            'membership_type': 'str',
            'street_address1': 'str',
            'street_address2': 'str',
            'city': 'str',
            'state': 'str',
            'zipcode': 'str',
            'country': 'str',
            'phone_number': 'str',
            'partner_url': 'str',
            'number_of_employees': 'str',
            'last_updated': 'str',
            'freeform_tags': 'dict(str, str)',
            'defined_tags': 'dict(str, dict(str, object))',
            'system_tags': 'dict(str, dict(str, object))'
        }
        self.attribute_map = {
            'company_id': 'companyId',
            'partner_name': 'partnerName',
            'level_program_name': 'levelProgramName',
            'start_date': 'startDate',
            'end_date': 'endDate',
            'membership_status': 'membershipStatus',
            'membership_type': 'membershipType',
            'street_address1': 'streetAddress1',
            'street_address2': 'streetAddress2',
            'city': 'city',
            'state': 'state',
            'zipcode': 'zipcode',
            'country': 'country',
            'phone_number': 'phoneNumber',
            'partner_url': 'partnerUrl',
            'number_of_employees': 'numberOfEmployees',
            'last_updated': 'lastUpdated',
            'freeform_tags': 'freeformTags',
            'defined_tags': 'definedTags',
            'system_tags': 'systemTags'
        }
        self._company_id = None
        self._partner_name = None
        self._level_program_name = None
        self._start_date = None
        self._end_date = None
        self._membership_status = None
        self._membership_type = None
        self._street_address1 = None
        self._street_address2 = None
        self._city = None
        self._state = None
        self._zipcode = None
        self._country = None
        self._phone_number = None
        self._partner_url = None
        self._number_of_employees = None
        self._last_updated = None
        self._freeform_tags = None
        self._defined_tags = None
        self._system_tags = None

    @property
    def company_id(self):
        """
        **[Required]** Gets the company_id of this AdminOpnPartnerSummary.
        The id for company.


        :return: The company_id of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """
        Sets the company_id of this AdminOpnPartnerSummary.
        The id for company.


        :param company_id: The company_id of this AdminOpnPartnerSummary.
        :type: str
        """
        self._company_id = company_id

    @property
    def partner_name(self):
        """
        **[Required]** Gets the partner_name of this AdminOpnPartnerSummary.
        Partner Name.


        :return: The partner_name of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._partner_name

    @partner_name.setter
    def partner_name(self, partner_name):
        """
        Sets the partner_name of this AdminOpnPartnerSummary.
        Partner Name.


        :param partner_name: The partner_name of this AdminOpnPartnerSummary.
        :type: str
        """
        self._partner_name = partner_name

    @property
    def level_program_name(self):
        """
        **[Required]** Gets the level_program_name of this AdminOpnPartnerSummary.
        Partner Name.


        :return: The level_program_name of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._level_program_name

    @level_program_name.setter
    def level_program_name(self, level_program_name):
        """
        Sets the level_program_name of this AdminOpnPartnerSummary.
        Partner Name.


        :param level_program_name: The level_program_name of this AdminOpnPartnerSummary.
        :type: str
        """
        self._level_program_name = level_program_name

    @property
    def start_date(self):
        """
        Gets the start_date of this AdminOpnPartnerSummary.
        The start date.


        :return: The start_date of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """
        Sets the start_date of this AdminOpnPartnerSummary.
        The start date.


        :param start_date: The start_date of this AdminOpnPartnerSummary.
        :type: str
        """
        self._start_date = start_date

    @property
    def end_date(self):
        """
        Gets the end_date of this AdminOpnPartnerSummary.
        The end date.


        :return: The end_date of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """
        Sets the end_date of this AdminOpnPartnerSummary.
        The end date.


        :param end_date: The end_date of this AdminOpnPartnerSummary.
        :type: str
        """
        self._end_date = end_date

    @property
    def membership_status(self):
        """
        **[Required]** Gets the membership_status of this AdminOpnPartnerSummary.
        The OPN membership status.

        Allowed values for this property are: "ACTIVE", "INACTIVE", "RENEWAL_IN_PROGRESS", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The membership_status of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._membership_status

    @membership_status.setter
    def membership_status(self, membership_status):
        """
        Sets the membership_status of this AdminOpnPartnerSummary.
        The OPN membership status.


        :param membership_status: The membership_status of this AdminOpnPartnerSummary.
        :type: str
        """
        allowed_values = ["ACTIVE", "INACTIVE", "RENEWAL_IN_PROGRESS"]
        if not value_allowed_none_or_none_sentinel(membership_status, allowed_values):
            membership_status = 'UNKNOWN_ENUM_VALUE'
        self._membership_status = membership_status

    @property
    def membership_type(self):
        """
        **[Required]** Gets the membership_type of this AdminOpnPartnerSummary.
        OPN membership type


        :return: The membership_type of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._membership_type

    @membership_type.setter
    def membership_type(self, membership_type):
        """
        Sets the membership_type of this AdminOpnPartnerSummary.
        OPN membership type


        :param membership_type: The membership_type of this AdminOpnPartnerSummary.
        :type: str
        """
        self._membership_type = membership_type

    @property
    def street_address1(self):
        """
        Gets the street_address1 of this AdminOpnPartnerSummary.
        The address of the partner.


        :return: The street_address1 of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._street_address1

    @street_address1.setter
    def street_address1(self, street_address1):
        """
        Sets the street_address1 of this AdminOpnPartnerSummary.
        The address of the partner.


        :param street_address1: The street_address1 of this AdminOpnPartnerSummary.
        :type: str
        """
        self._street_address1 = street_address1

    @property
    def street_address2(self):
        """
        Gets the street_address2 of this AdminOpnPartnerSummary.
        The address of the partner.


        :return: The street_address2 of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._street_address2

    @street_address2.setter
    def street_address2(self, street_address2):
        """
        Sets the street_address2 of this AdminOpnPartnerSummary.
        The address of the partner.


        :param street_address2: The street_address2 of this AdminOpnPartnerSummary.
        :type: str
        """
        self._street_address2 = street_address2

    @property
    def city(self):
        """
        Gets the city of this AdminOpnPartnerSummary.
        City


        :return: The city of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """
        Sets the city of this AdminOpnPartnerSummary.
        City


        :param city: The city of this AdminOpnPartnerSummary.
        :type: str
        """
        self._city = city

    @property
    def state(self):
        """
        Gets the state of this AdminOpnPartnerSummary.
        State


        :return: The state of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this AdminOpnPartnerSummary.
        State


        :param state: The state of this AdminOpnPartnerSummary.
        :type: str
        """
        self._state = state

    @property
    def zipcode(self):
        """
        Gets the zipcode of this AdminOpnPartnerSummary.
        Zip


        :return: The zipcode of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._zipcode

    @zipcode.setter
    def zipcode(self, zipcode):
        """
        Sets the zipcode of this AdminOpnPartnerSummary.
        Zip


        :param zipcode: The zipcode of this AdminOpnPartnerSummary.
        :type: str
        """
        self._zipcode = zipcode

    @property
    def country(self):
        """
        Gets the country of this AdminOpnPartnerSummary.
        Country


        :return: The country of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """
        Sets the country of this AdminOpnPartnerSummary.
        Country


        :param country: The country of this AdminOpnPartnerSummary.
        :type: str
        """
        self._country = country

    @property
    def phone_number(self):
        """
        Gets the phone_number of this AdminOpnPartnerSummary.
        The phone number of the contact.


        :return: The phone_number of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """
        Sets the phone_number of this AdminOpnPartnerSummary.
        The phone number of the contact.


        :param phone_number: The phone_number of this AdminOpnPartnerSummary.
        :type: str
        """
        self._phone_number = phone_number

    @property
    def partner_url(self):
        """
        Gets the partner_url of this AdminOpnPartnerSummary.
        The URL for partner's service.


        :return: The partner_url of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._partner_url

    @partner_url.setter
    def partner_url(self, partner_url):
        """
        Sets the partner_url of this AdminOpnPartnerSummary.
        The URL for partner's service.


        :param partner_url: The partner_url of this AdminOpnPartnerSummary.
        :type: str
        """
        self._partner_url = partner_url

    @property
    def number_of_employees(self):
        """
        Gets the number_of_employees of this AdminOpnPartnerSummary.
        The total number of employees.


        :return: The number_of_employees of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._number_of_employees

    @number_of_employees.setter
    def number_of_employees(self, number_of_employees):
        """
        Sets the number_of_employees of this AdminOpnPartnerSummary.
        The total number of employees.


        :param number_of_employees: The number_of_employees of this AdminOpnPartnerSummary.
        :type: str
        """
        self._number_of_employees = number_of_employees

    @property
    def last_updated(self):
        """
        Gets the last_updated of this AdminOpnPartnerSummary.
        The last updated timestamp in format \"yyyy-MM-dd HH:mm:ss.S\".


        :return: The last_updated of this AdminOpnPartnerSummary.
        :rtype: str
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated):
        """
        Sets the last_updated of this AdminOpnPartnerSummary.
        The last updated timestamp in format \"yyyy-MM-dd HH:mm:ss.S\".


        :param last_updated: The last_updated of this AdminOpnPartnerSummary.
        :type: str
        """
        self._last_updated = last_updated

    @property
    def freeform_tags(self):
        """
        Gets the freeform_tags of this AdminOpnPartnerSummary.
        Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
        Example: `{\"bar-key\": \"value\"}`


        :return: The freeform_tags of this AdminOpnPartnerSummary.
        :rtype: dict(str, str)
        """
        return self._freeform_tags

    @freeform_tags.setter
    def freeform_tags(self, freeform_tags):
        """
        Sets the freeform_tags of this AdminOpnPartnerSummary.
        Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
        Example: `{\"bar-key\": \"value\"}`


        :param freeform_tags: The freeform_tags of this AdminOpnPartnerSummary.
        :type: dict(str, str)
        """
        self._freeform_tags = freeform_tags

    @property
    def defined_tags(self):
        """
        Gets the defined_tags of this AdminOpnPartnerSummary.
        Defined tags for this resource. Each key is predefined and scoped to a namespace.
        Example: `{\"foo-namespace\": {\"bar-key\": \"value\"}}`


        :return: The defined_tags of this AdminOpnPartnerSummary.
        :rtype: dict(str, dict(str, object))
        """
        return self._defined_tags

    @defined_tags.setter
    def defined_tags(self, defined_tags):
        """
        Sets the defined_tags of this AdminOpnPartnerSummary.
        Defined tags for this resource. Each key is predefined and scoped to a namespace.
        Example: `{\"foo-namespace\": {\"bar-key\": \"value\"}}`


        :param defined_tags: The defined_tags of this AdminOpnPartnerSummary.
        :type: dict(str, dict(str, object))
        """
        self._defined_tags = defined_tags

    @property
    def system_tags(self):
        """
        Gets the system_tags of this AdminOpnPartnerSummary.
        System tags for this resource. Each key is predefined and scoped to a namespace.
        Example: `{\"orcl-cloud\": {\"free-tier-retained\": \"true\"}}`


        :return: The system_tags of this AdminOpnPartnerSummary.
        :rtype: dict(str, dict(str, object))
        """
        return self._system_tags

    @system_tags.setter
    def system_tags(self, system_tags):
        """
        Sets the system_tags of this AdminOpnPartnerSummary.
        System tags for this resource. Each key is predefined and scoped to a namespace.
        Example: `{\"orcl-cloud\": {\"free-tier-retained\": \"true\"}}`


        :param system_tags: The system_tags of this AdminOpnPartnerSummary.
        :type: dict(str, dict(str, object))
        """
        self._system_tags = system_tags

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
