# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20241201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class AdminListingRevision(object):
    """
    The model for an Oracle Cloud Infrastructure Marketplace Publisher listing revision.
    """

    #: A constant which can be used with the listing_type property of a AdminListingRevision.
    #: This constant has a value of "OCI_APPLICATION"
    LISTING_TYPE_OCI_APPLICATION = "OCI_APPLICATION"

    #: A constant which can be used with the listing_type property of a AdminListingRevision.
    #: This constant has a value of "LEAD_GENERATION"
    LISTING_TYPE_LEAD_GENERATION = "LEAD_GENERATION"

    #: A constant which can be used with the listing_type property of a AdminListingRevision.
    #: This constant has a value of "SERVICE"
    LISTING_TYPE_SERVICE = "SERVICE"

    #: A constant which can be used with the package_type property of a AdminListingRevision.
    #: This constant has a value of "CONTAINER_IMAGE"
    PACKAGE_TYPE_CONTAINER_IMAGE = "CONTAINER_IMAGE"

    #: A constant which can be used with the package_type property of a AdminListingRevision.
    #: This constant has a value of "HELM_CHART"
    PACKAGE_TYPE_HELM_CHART = "HELM_CHART"

    #: A constant which can be used with the package_type property of a AdminListingRevision.
    #: This constant has a value of "MACHINE_IMAGE"
    PACKAGE_TYPE_MACHINE_IMAGE = "MACHINE_IMAGE"

    #: A constant which can be used with the package_type property of a AdminListingRevision.
    #: This constant has a value of "STACK"
    PACKAGE_TYPE_STACK = "STACK"

    #: A constant which can be used with the package_type property of a AdminListingRevision.
    #: This constant has a value of "NONE"
    PACKAGE_TYPE_NONE = "NONE"

    def __init__(self, **kwargs):
        """
        Initializes a new AdminListingRevision object with values from keyword arguments. This class has the following subclasses and if you are using this class as input
        to a service operations then you should favor using a subclass over the base class:

        * :class:`~oci.marketplace_publisher.models.AdminServiceListingRevision`
        * :class:`~oci.marketplace_publisher.models.AdminAiAgentListingRevision`
        * :class:`~oci.marketplace_publisher.models.AdminOciListingRevision`
        * :class:`~oci.marketplace_publisher.models.AdminLeadGenListingRevision`

        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param id:
            The value to assign to the id property of this AdminListingRevision.
        :type id: str

        :param legacy_id:
            The value to assign to the legacy_id property of this AdminListingRevision.
        :type legacy_id: str

        :param listing_id:
            The value to assign to the listing_id property of this AdminListingRevision.
        :type listing_id: str

        :param compartment_id:
            The value to assign to the compartment_id property of this AdminListingRevision.
        :type compartment_id: str

        :param publisher_id:
            The value to assign to the publisher_id property of this AdminListingRevision.
        :type publisher_id: str

        :param approver_id:
            The value to assign to the approver_id property of this AdminListingRevision.
        :type approver_id: str

        :param approver_email:
            The value to assign to the approver_email property of this AdminListingRevision.
        :type approver_email: str

        :param display_name:
            The value to assign to the display_name property of this AdminListingRevision.
        :type display_name: str

        :param listing_type:
            The value to assign to the listing_type property of this AdminListingRevision.
            Allowed values for this property are: "OCI_APPLICATION", "LEAD_GENERATION", "SERVICE", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type listing_type: str

        :param revision_number:
            The value to assign to the revision_number property of this AdminListingRevision.
        :type revision_number: str

        :param headline:
            The value to assign to the headline property of this AdminListingRevision.
        :type headline: str

        :param tagline:
            The value to assign to the tagline property of this AdminListingRevision.
        :type tagline: str

        :param keywords:
            The value to assign to the keywords property of this AdminListingRevision.
        :type keywords: str

        :param short_description:
            The value to assign to the short_description property of this AdminListingRevision.
        :type short_description: str

        :param usage_information:
            The value to assign to the usage_information property of this AdminListingRevision.
        :type usage_information: str

        :param long_description:
            The value to assign to the long_description property of this AdminListingRevision.
        :type long_description: str

        :param time_created:
            The value to assign to the time_created property of this AdminListingRevision.
        :type time_created: datetime

        :param time_updated:
            The value to assign to the time_updated property of this AdminListingRevision.
        :type time_updated: datetime

        :param content_language:
            The value to assign to the content_language property of this AdminListingRevision.
        :type content_language: oci.marketplace_publisher.models.LanguageItem

        :param supportedlanguages:
            The value to assign to the supportedlanguages property of this AdminListingRevision.
        :type supportedlanguages: list[oci.marketplace_publisher.models.LanguageItem]

        :param support_contacts:
            The value to assign to the support_contacts property of this AdminListingRevision.
        :type support_contacts: list[oci.marketplace_publisher.models.SupportContact]

        :param support_links:
            The value to assign to the support_links property of this AdminListingRevision.
        :type support_links: list[oci.marketplace_publisher.models.NamedLink]

        :param icon:
            The value to assign to the icon property of this AdminListingRevision.
        :type icon: oci.marketplace_publisher.models.ListingRevisionIconAttachment

        :param banner:
            The value to assign to the banner property of this AdminListingRevision.
        :type banner: oci.marketplace_publisher.models.ListingRevisionBannerAttachment

        :param status:
            The value to assign to the status property of this AdminListingRevision.
        :type status: str

        :param status_notes:
            The value to assign to the status_notes property of this AdminListingRevision.
        :type status_notes: str

        :param lifecycle_state:
            The value to assign to the lifecycle_state property of this AdminListingRevision.
        :type lifecycle_state: str

        :param package_type:
            The value to assign to the package_type property of this AdminListingRevision.
            Allowed values for this property are: "CONTAINER_IMAGE", "HELM_CHART", "MACHINE_IMAGE", "STACK", "NONE", 'UNKNOWN_ENUM_VALUE'.
            Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
        :type package_type: str

        :param extended_metadata:
            The value to assign to the extended_metadata property of this AdminListingRevision.
        :type extended_metadata: dict(str, str)

        :param freeform_tags:
            The value to assign to the freeform_tags property of this AdminListingRevision.
        :type freeform_tags: dict(str, str)

        :param defined_tags:
            The value to assign to the defined_tags property of this AdminListingRevision.
        :type defined_tags: dict(str, dict(str, object))

        :param system_tags:
            The value to assign to the system_tags property of this AdminListingRevision.
        :type system_tags: dict(str, dict(str, object))

        """
        self.swagger_types = {
            'id': 'str',
            'legacy_id': 'str',
            'listing_id': 'str',
            'compartment_id': 'str',
            'publisher_id': 'str',
            'approver_id': 'str',
            'approver_email': 'str',
            'display_name': 'str',
            'listing_type': 'str',
            'revision_number': 'str',
            'headline': 'str',
            'tagline': 'str',
            'keywords': 'str',
            'short_description': 'str',
            'usage_information': 'str',
            'long_description': 'str',
            'time_created': 'datetime',
            'time_updated': 'datetime',
            'content_language': 'LanguageItem',
            'supportedlanguages': 'list[LanguageItem]',
            'support_contacts': 'list[SupportContact]',
            'support_links': 'list[NamedLink]',
            'icon': 'ListingRevisionIconAttachment',
            'banner': 'ListingRevisionBannerAttachment',
            'status': 'str',
            'status_notes': 'str',
            'lifecycle_state': 'str',
            'package_type': 'str',
            'extended_metadata': 'dict(str, str)',
            'freeform_tags': 'dict(str, str)',
            'defined_tags': 'dict(str, dict(str, object))',
            'system_tags': 'dict(str, dict(str, object))'
        }
        self.attribute_map = {
            'id': 'id',
            'legacy_id': 'legacyId',
            'listing_id': 'listingId',
            'compartment_id': 'compartmentId',
            'publisher_id': 'publisherId',
            'approver_id': 'approverId',
            'approver_email': 'approverEmail',
            'display_name': 'displayName',
            'listing_type': 'listingType',
            'revision_number': 'revisionNumber',
            'headline': 'headline',
            'tagline': 'tagline',
            'keywords': 'keywords',
            'short_description': 'shortDescription',
            'usage_information': 'usageInformation',
            'long_description': 'longDescription',
            'time_created': 'timeCreated',
            'time_updated': 'timeUpdated',
            'content_language': 'contentLanguage',
            'supportedlanguages': 'supportedlanguages',
            'support_contacts': 'supportContacts',
            'support_links': 'supportLinks',
            'icon': 'icon',
            'banner': 'banner',
            'status': 'status',
            'status_notes': 'statusNotes',
            'lifecycle_state': 'lifecycleState',
            'package_type': 'packageType',
            'extended_metadata': 'extendedMetadata',
            'freeform_tags': 'freeformTags',
            'defined_tags': 'definedTags',
            'system_tags': 'systemTags'
        }
        self._id = None
        self._legacy_id = None
        self._listing_id = None
        self._compartment_id = None
        self._publisher_id = None
        self._approver_id = None
        self._approver_email = None
        self._display_name = None
        self._listing_type = None
        self._revision_number = None
        self._headline = None
        self._tagline = None
        self._keywords = None
        self._short_description = None
        self._usage_information = None
        self._long_description = None
        self._time_created = None
        self._time_updated = None
        self._content_language = None
        self._supportedlanguages = None
        self._support_contacts = None
        self._support_links = None
        self._icon = None
        self._banner = None
        self._status = None
        self._status_notes = None
        self._lifecycle_state = None
        self._package_type = None
        self._extended_metadata = None
        self._freeform_tags = None
        self._defined_tags = None
        self._system_tags = None

    @staticmethod
    def get_subtype(object_dictionary):
        """
        Given the hash representation of a subtype of this class,
        use the info in the hash to return the class of the subtype.
        """
        type = object_dictionary['listingType']

        if type == 'SERVICE':
            return 'AdminServiceListingRevision'

        if type == 'AI_AGENT':
            return 'AdminAiAgentListingRevision'

        if type == 'OCI_APPLICATION':
            return 'AdminOciListingRevision'

        if type == 'LEAD_GENERATION':
            return 'AdminLeadGenListingRevision'
        else:
            return 'AdminListingRevision'

    @property
    def id(self):
        """
        **[Required]** Gets the id of this AdminListingRevision.
        The OCID for the listing revision in Marketplace Publisher.


        :return: The id of this AdminListingRevision.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this AdminListingRevision.
        The OCID for the listing revision in Marketplace Publisher.


        :param id: The id of this AdminListingRevision.
        :type: str
        """
        self._id = id

    @property
    def legacy_id(self):
        """
        Gets the legacy_id of this AdminListingRevision.
        The unique legacy identifier for the listing.


        :return: The legacy_id of this AdminListingRevision.
        :rtype: str
        """
        return self._legacy_id

    @legacy_id.setter
    def legacy_id(self, legacy_id):
        """
        Sets the legacy_id of this AdminListingRevision.
        The unique legacy identifier for the listing.


        :param legacy_id: The legacy_id of this AdminListingRevision.
        :type: str
        """
        self._legacy_id = legacy_id

    @property
    def listing_id(self):
        """
        **[Required]** Gets the listing_id of this AdminListingRevision.
        The unique identifier for the listing this revision belongs to.


        :return: The listing_id of this AdminListingRevision.
        :rtype: str
        """
        return self._listing_id

    @listing_id.setter
    def listing_id(self, listing_id):
        """
        Sets the listing_id of this AdminListingRevision.
        The unique identifier for the listing this revision belongs to.


        :param listing_id: The listing_id of this AdminListingRevision.
        :type: str
        """
        self._listing_id = listing_id

    @property
    def compartment_id(self):
        """
        Gets the compartment_id of this AdminListingRevision.
        The unique identifier for the compartment.


        :return: The compartment_id of this AdminListingRevision.
        :rtype: str
        """
        return self._compartment_id

    @compartment_id.setter
    def compartment_id(self, compartment_id):
        """
        Sets the compartment_id of this AdminListingRevision.
        The unique identifier for the compartment.


        :param compartment_id: The compartment_id of this AdminListingRevision.
        :type: str
        """
        self._compartment_id = compartment_id

    @property
    def publisher_id(self):
        """
        **[Required]** Gets the publisher_id of this AdminListingRevision.
        The OCID for the publisher in Marketplace Publisher.


        :return: The publisher_id of this AdminListingRevision.
        :rtype: str
        """
        return self._publisher_id

    @publisher_id.setter
    def publisher_id(self, publisher_id):
        """
        Sets the publisher_id of this AdminListingRevision.
        The OCID for the publisher in Marketplace Publisher.


        :param publisher_id: The publisher_id of this AdminListingRevision.
        :type: str
        """
        self._publisher_id = publisher_id

    @property
    def approver_id(self):
        """
        Gets the approver_id of this AdminListingRevision.
        The user OCID of the administrator who approved the listing revision.


        :return: The approver_id of this AdminListingRevision.
        :rtype: str
        """
        return self._approver_id

    @approver_id.setter
    def approver_id(self, approver_id):
        """
        Sets the approver_id of this AdminListingRevision.
        The user OCID of the administrator who approved the listing revision.


        :param approver_id: The approver_id of this AdminListingRevision.
        :type: str
        """
        self._approver_id = approver_id

    @property
    def approver_email(self):
        """
        Gets the approver_email of this AdminListingRevision.
        The email address of the administrator who approved the listing revision.


        :return: The approver_email of this AdminListingRevision.
        :rtype: str
        """
        return self._approver_email

    @approver_email.setter
    def approver_email(self, approver_email):
        """
        Sets the approver_email of this AdminListingRevision.
        The email address of the administrator who approved the listing revision.


        :param approver_email: The approver_email of this AdminListingRevision.
        :type: str
        """
        self._approver_email = approver_email

    @property
    def display_name(self):
        """
        **[Required]** Gets the display_name of this AdminListingRevision.
        The name for the listing revision.


        :return: The display_name of this AdminListingRevision.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """
        Sets the display_name of this AdminListingRevision.
        The name for the listing revision.


        :param display_name: The display_name of this AdminListingRevision.
        :type: str
        """
        self._display_name = display_name

    @property
    def listing_type(self):
        """
        **[Required]** Gets the listing_type of this AdminListingRevision.
        The listing's type. Populated from the listing.

        Allowed values for this property are: "OCI_APPLICATION", "LEAD_GENERATION", "SERVICE", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The listing_type of this AdminListingRevision.
        :rtype: str
        """
        return self._listing_type

    @listing_type.setter
    def listing_type(self, listing_type):
        """
        Sets the listing_type of this AdminListingRevision.
        The listing's type. Populated from the listing.


        :param listing_type: The listing_type of this AdminListingRevision.
        :type: str
        """
        allowed_values = ["OCI_APPLICATION", "LEAD_GENERATION", "SERVICE"]
        if not value_allowed_none_or_none_sentinel(listing_type, allowed_values):
            listing_type = 'UNKNOWN_ENUM_VALUE'
        self._listing_type = listing_type

    @property
    def revision_number(self):
        """
        Gets the revision_number of this AdminListingRevision.
        The revision number of the listing revision. This is an internal attribute


        :return: The revision_number of this AdminListingRevision.
        :rtype: str
        """
        return self._revision_number

    @revision_number.setter
    def revision_number(self, revision_number):
        """
        Sets the revision_number of this AdminListingRevision.
        The revision number of the listing revision. This is an internal attribute


        :param revision_number: The revision_number of this AdminListingRevision.
        :type: str
        """
        self._revision_number = revision_number

    @property
    def headline(self):
        """
        **[Required]** Gets the headline of this AdminListingRevision.
        Single line introduction for the listing revision.


        :return: The headline of this AdminListingRevision.
        :rtype: str
        """
        return self._headline

    @headline.setter
    def headline(self, headline):
        """
        Sets the headline of this AdminListingRevision.
        Single line introduction for the listing revision.


        :param headline: The headline of this AdminListingRevision.
        :type: str
        """
        self._headline = headline

    @property
    def tagline(self):
        """
        Gets the tagline of this AdminListingRevision.
        The tagline for the listing revision.


        :return: The tagline of this AdminListingRevision.
        :rtype: str
        """
        return self._tagline

    @tagline.setter
    def tagline(self, tagline):
        """
        Sets the tagline of this AdminListingRevision.
        The tagline for the listing revision.


        :param tagline: The tagline of this AdminListingRevision.
        :type: str
        """
        self._tagline = tagline

    @property
    def keywords(self):
        """
        Gets the keywords of this AdminListingRevision.
        Keywords associated with the listing revision.


        :return: The keywords of this AdminListingRevision.
        :rtype: str
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords):
        """
        Sets the keywords of this AdminListingRevision.
        Keywords associated with the listing revision.


        :param keywords: The keywords of this AdminListingRevision.
        :type: str
        """
        self._keywords = keywords

    @property
    def short_description(self):
        """
        Gets the short_description of this AdminListingRevision.
        A short description of the listing revision.


        :return: The short_description of this AdminListingRevision.
        :rtype: str
        """
        return self._short_description

    @short_description.setter
    def short_description(self, short_description):
        """
        Sets the short_description of this AdminListingRevision.
        A short description of the listing revision.


        :param short_description: The short_description of this AdminListingRevision.
        :type: str
        """
        self._short_description = short_description

    @property
    def usage_information(self):
        """
        Gets the usage_information of this AdminListingRevision.
        Usage information for the listing revision.


        :return: The usage_information of this AdminListingRevision.
        :rtype: str
        """
        return self._usage_information

    @usage_information.setter
    def usage_information(self, usage_information):
        """
        Sets the usage_information of this AdminListingRevision.
        Usage information for the listing revision.


        :param usage_information: The usage_information of this AdminListingRevision.
        :type: str
        """
        self._usage_information = usage_information

    @property
    def long_description(self):
        """
        Gets the long_description of this AdminListingRevision.
        A long description for the listing revision.


        :return: The long_description of this AdminListingRevision.
        :rtype: str
        """
        return self._long_description

    @long_description.setter
    def long_description(self, long_description):
        """
        Sets the long_description of this AdminListingRevision.
        A long description for the listing revision.


        :param long_description: The long_description of this AdminListingRevision.
        :type: str
        """
        self._long_description = long_description

    @property
    def time_created(self):
        """
        **[Required]** Gets the time_created of this AdminListingRevision.
        The time the listing revision was created. An RFC3339 formatted datetime string.


        :return: The time_created of this AdminListingRevision.
        :rtype: datetime
        """
        return self._time_created

    @time_created.setter
    def time_created(self, time_created):
        """
        Sets the time_created of this AdminListingRevision.
        The time the listing revision was created. An RFC3339 formatted datetime string.


        :param time_created: The time_created of this AdminListingRevision.
        :type: datetime
        """
        self._time_created = time_created

    @property
    def time_updated(self):
        """
        **[Required]** Gets the time_updated of this AdminListingRevision.
        The time the listing revision was updated. An RFC3339 formatted datetime string.


        :return: The time_updated of this AdminListingRevision.
        :rtype: datetime
        """
        return self._time_updated

    @time_updated.setter
    def time_updated(self, time_updated):
        """
        Sets the time_updated of this AdminListingRevision.
        The time the listing revision was updated. An RFC3339 formatted datetime string.


        :param time_updated: The time_updated of this AdminListingRevision.
        :type: datetime
        """
        self._time_updated = time_updated

    @property
    def content_language(self):
        """
        Gets the content_language of this AdminListingRevision.

        :return: The content_language of this AdminListingRevision.
        :rtype: oci.marketplace_publisher.models.LanguageItem
        """
        return self._content_language

    @content_language.setter
    def content_language(self, content_language):
        """
        Sets the content_language of this AdminListingRevision.

        :param content_language: The content_language of this AdminListingRevision.
        :type: oci.marketplace_publisher.models.LanguageItem
        """
        self._content_language = content_language

    @property
    def supportedlanguages(self):
        """
        Gets the supportedlanguages of this AdminListingRevision.
        Languages supported by the publisher for the listing revision.


        :return: The supportedlanguages of this AdminListingRevision.
        :rtype: list[oci.marketplace_publisher.models.LanguageItem]
        """
        return self._supportedlanguages

    @supportedlanguages.setter
    def supportedlanguages(self, supportedlanguages):
        """
        Sets the supportedlanguages of this AdminListingRevision.
        Languages supported by the publisher for the listing revision.


        :param supportedlanguages: The supportedlanguages of this AdminListingRevision.
        :type: list[oci.marketplace_publisher.models.LanguageItem]
        """
        self._supportedlanguages = supportedlanguages

    @property
    def support_contacts(self):
        """
        Gets the support_contacts of this AdminListingRevision.
        Contact information to use to get support from the publisher for the listing revision.


        :return: The support_contacts of this AdminListingRevision.
        :rtype: list[oci.marketplace_publisher.models.SupportContact]
        """
        return self._support_contacts

    @support_contacts.setter
    def support_contacts(self, support_contacts):
        """
        Sets the support_contacts of this AdminListingRevision.
        Contact information to use to get support from the publisher for the listing revision.


        :param support_contacts: The support_contacts of this AdminListingRevision.
        :type: list[oci.marketplace_publisher.models.SupportContact]
        """
        self._support_contacts = support_contacts

    @property
    def support_links(self):
        """
        Gets the support_links of this AdminListingRevision.
        Links to support resources for the listing revision.


        :return: The support_links of this AdminListingRevision.
        :rtype: list[oci.marketplace_publisher.models.NamedLink]
        """
        return self._support_links

    @support_links.setter
    def support_links(self, support_links):
        """
        Sets the support_links of this AdminListingRevision.
        Links to support resources for the listing revision.


        :param support_links: The support_links of this AdminListingRevision.
        :type: list[oci.marketplace_publisher.models.NamedLink]
        """
        self._support_links = support_links

    @property
    def icon(self):
        """
        Gets the icon of this AdminListingRevision.

        :return: The icon of this AdminListingRevision.
        :rtype: oci.marketplace_publisher.models.ListingRevisionIconAttachment
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """
        Sets the icon of this AdminListingRevision.

        :param icon: The icon of this AdminListingRevision.
        :type: oci.marketplace_publisher.models.ListingRevisionIconAttachment
        """
        self._icon = icon

    @property
    def banner(self):
        """
        Gets the banner of this AdminListingRevision.

        :return: The banner of this AdminListingRevision.
        :rtype: oci.marketplace_publisher.models.ListingRevisionBannerAttachment
        """
        return self._banner

    @banner.setter
    def banner(self, banner):
        """
        Sets the banner of this AdminListingRevision.

        :param banner: The banner of this AdminListingRevision.
        :type: oci.marketplace_publisher.models.ListingRevisionBannerAttachment
        """
        self._banner = banner

    @property
    def status(self):
        """
        **[Required]** Gets the status of this AdminListingRevision.
        The current status for the listing revision.


        :return: The status of this AdminListingRevision.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this AdminListingRevision.
        The current status for the listing revision.


        :param status: The status of this AdminListingRevision.
        :type: str
        """
        self._status = status

    @property
    def status_notes(self):
        """
        Gets the status_notes of this AdminListingRevision.
        Status notes for the listing revision.


        :return: The status_notes of this AdminListingRevision.
        :rtype: str
        """
        return self._status_notes

    @status_notes.setter
    def status_notes(self, status_notes):
        """
        Sets the status_notes of this AdminListingRevision.
        Status notes for the listing revision.


        :param status_notes: The status_notes of this AdminListingRevision.
        :type: str
        """
        self._status_notes = status_notes

    @property
    def lifecycle_state(self):
        """
        **[Required]** Gets the lifecycle_state of this AdminListingRevision.
        The current state of the listing revision.


        :return: The lifecycle_state of this AdminListingRevision.
        :rtype: str
        """
        return self._lifecycle_state

    @lifecycle_state.setter
    def lifecycle_state(self, lifecycle_state):
        """
        Sets the lifecycle_state of this AdminListingRevision.
        The current state of the listing revision.


        :param lifecycle_state: The lifecycle_state of this AdminListingRevision.
        :type: str
        """
        self._lifecycle_state = lifecycle_state

    @property
    def package_type(self):
        """
        **[Required]** Gets the package_type of this AdminListingRevision.
        The listing's package type. Populated from the listing.

        Allowed values for this property are: "CONTAINER_IMAGE", "HELM_CHART", "MACHINE_IMAGE", "STACK", "NONE", 'UNKNOWN_ENUM_VALUE'.
        Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.


        :return: The package_type of this AdminListingRevision.
        :rtype: str
        """
        return self._package_type

    @package_type.setter
    def package_type(self, package_type):
        """
        Sets the package_type of this AdminListingRevision.
        The listing's package type. Populated from the listing.


        :param package_type: The package_type of this AdminListingRevision.
        :type: str
        """
        allowed_values = ["CONTAINER_IMAGE", "HELM_CHART", "MACHINE_IMAGE", "STACK", "NONE"]
        if not value_allowed_none_or_none_sentinel(package_type, allowed_values):
            package_type = 'UNKNOWN_ENUM_VALUE'
        self._package_type = package_type

    @property
    def extended_metadata(self):
        """
        Gets the extended_metadata of this AdminListingRevision.
        Additional metadata key/value pairs for the listing revision.

        For example:

        `{\"oracleStandardTermVersionId\": \"1234\"}`


        :return: The extended_metadata of this AdminListingRevision.
        :rtype: dict(str, str)
        """
        return self._extended_metadata

    @extended_metadata.setter
    def extended_metadata(self, extended_metadata):
        """
        Sets the extended_metadata of this AdminListingRevision.
        Additional metadata key/value pairs for the listing revision.

        For example:

        `{\"oracleStandardTermVersionId\": \"1234\"}`


        :param extended_metadata: The extended_metadata of this AdminListingRevision.
        :type: dict(str, str)
        """
        self._extended_metadata = extended_metadata

    @property
    def freeform_tags(self):
        """
        Gets the freeform_tags of this AdminListingRevision.
        Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
        Example: `{\"bar-key\": \"value\"}`


        :return: The freeform_tags of this AdminListingRevision.
        :rtype: dict(str, str)
        """
        return self._freeform_tags

    @freeform_tags.setter
    def freeform_tags(self, freeform_tags):
        """
        Sets the freeform_tags of this AdminListingRevision.
        Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
        Example: `{\"bar-key\": \"value\"}`


        :param freeform_tags: The freeform_tags of this AdminListingRevision.
        :type: dict(str, str)
        """
        self._freeform_tags = freeform_tags

    @property
    def defined_tags(self):
        """
        Gets the defined_tags of this AdminListingRevision.
        Defined tags for this resource. Each key is predefined and scoped to a namespace.
        Example: `{\"foo-namespace\": {\"bar-key\": \"value\"}}`


        :return: The defined_tags of this AdminListingRevision.
        :rtype: dict(str, dict(str, object))
        """
        return self._defined_tags

    @defined_tags.setter
    def defined_tags(self, defined_tags):
        """
        Sets the defined_tags of this AdminListingRevision.
        Defined tags for this resource. Each key is predefined and scoped to a namespace.
        Example: `{\"foo-namespace\": {\"bar-key\": \"value\"}}`


        :param defined_tags: The defined_tags of this AdminListingRevision.
        :type: dict(str, dict(str, object))
        """
        self._defined_tags = defined_tags

    @property
    def system_tags(self):
        """
        Gets the system_tags of this AdminListingRevision.
        System tags for this resource. Each key is predefined and scoped to a namespace.
        Example: `{\"orcl-cloud\": {\"free-tier-retained\": \"true\"}}`


        :return: The system_tags of this AdminListingRevision.
        :rtype: dict(str, dict(str, object))
        """
        return self._system_tags

    @system_tags.setter
    def system_tags(self, system_tags):
        """
        Sets the system_tags of this AdminListingRevision.
        System tags for this resource. Each key is predefined and scoped to a namespace.
        Example: `{\"orcl-cloud\": {\"free-tier-retained\": \"true\"}}`


        :param system_tags: The system_tags of this AdminListingRevision.
        :type: dict(str, dict(str, object))
        """
        self._system_tags = system_tags

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
