# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20241201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CreateAdminListingRevisionNoteDetails(object):
    """
    The model for an Oracle Cloud Infrastructure Marketplace Publisher listing revision note.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new CreateAdminListingRevisionNoteDetails object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param listing_revision_id:
            The value to assign to the listing_revision_id property of this CreateAdminListingRevisionNoteDetails.
        :type listing_revision_id: str

        :param note_details:
            The value to assign to the note_details property of this CreateAdminListingRevisionNoteDetails.
        :type note_details: str

        """
        self.swagger_types = {
            'listing_revision_id': 'str',
            'note_details': 'str'
        }
        self.attribute_map = {
            'listing_revision_id': 'listingRevisionId',
            'note_details': 'noteDetails'
        }
        self._listing_revision_id = None
        self._note_details = None

    @property
    def listing_revision_id(self):
        """
        **[Required]** Gets the listing_revision_id of this CreateAdminListingRevisionNoteDetails.
        The unique identifier of the listing revision that the specified note belongs to.


        :return: The listing_revision_id of this CreateAdminListingRevisionNoteDetails.
        :rtype: str
        """
        return self._listing_revision_id

    @listing_revision_id.setter
    def listing_revision_id(self, listing_revision_id):
        """
        Sets the listing_revision_id of this CreateAdminListingRevisionNoteDetails.
        The unique identifier of the listing revision that the specified note belongs to.


        :param listing_revision_id: The listing_revision_id of this CreateAdminListingRevisionNoteDetails.
        :type: str
        """
        self._listing_revision_id = listing_revision_id

    @property
    def note_details(self):
        """
        **[Required]** Gets the note_details of this CreateAdminListingRevisionNoteDetails.
        Notes provided for the listing revision.


        :return: The note_details of this CreateAdminListingRevisionNoteDetails.
        :rtype: str
        """
        return self._note_details

    @note_details.setter
    def note_details(self, note_details):
        """
        Sets the note_details of this CreateAdminListingRevisionNoteDetails.
        Notes provided for the listing revision.


        :param note_details: The note_details of this CreateAdminListingRevisionNoteDetails.
        :type: str
        """
        self._note_details = note_details

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
