# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20241201


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CreateMarketDetails(object):
    """
    Details to create a Market.
    """

    def __init__(self, **kwargs):
        """
        Initializes a new CreateMarketDetails object with values from keyword arguments.
        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param name:
            The value to assign to the name property of this CreateMarketDetails.
        :type name: str

        :param code:
            The value to assign to the code property of this CreateMarketDetails.
        :type code: str

        :param category_code:
            The value to assign to the category_code property of this CreateMarketDetails.
        :type category_code: str

        :param bill_to_countries:
            The value to assign to the bill_to_countries property of this CreateMarketDetails.
        :type bill_to_countries: list[oci.marketplace_publisher.models.BillToCountry]

        """
        self.swagger_types = {
            'name': 'str',
            'code': 'str',
            'category_code': 'str',
            'bill_to_countries': 'list[BillToCountry]'
        }
        self.attribute_map = {
            'name': 'name',
            'code': 'code',
            'category_code': 'categoryCode',
            'bill_to_countries': 'billToCountries'
        }
        self._name = None
        self._code = None
        self._category_code = None
        self._bill_to_countries = None

    @property
    def name(self):
        """
        **[Required]** Gets the name of this CreateMarketDetails.
        The name of the market.


        :return: The name of this CreateMarketDetails.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CreateMarketDetails.
        The name of the market.


        :param name: The name of this CreateMarketDetails.
        :type: str
        """
        self._name = name

    @property
    def code(self):
        """
        **[Required]** Gets the code of this CreateMarketDetails.
        The code of the market.


        :return: The code of this CreateMarketDetails.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this CreateMarketDetails.
        The code of the market.


        :param code: The code of this CreateMarketDetails.
        :type: str
        """
        self._code = code

    @property
    def category_code(self):
        """
        **[Required]** Gets the category_code of this CreateMarketDetails.
        The category code of the market.


        :return: The category_code of this CreateMarketDetails.
        :rtype: str
        """
        return self._category_code

    @category_code.setter
    def category_code(self, category_code):
        """
        Sets the category_code of this CreateMarketDetails.
        The category code of the market.


        :param category_code: The category_code of this CreateMarketDetails.
        :type: str
        """
        self._category_code = category_code

    @property
    def bill_to_countries(self):
        """
        Gets the bill_to_countries of this CreateMarketDetails.
        bill to countries for the market.


        :return: The bill_to_countries of this CreateMarketDetails.
        :rtype: list[oci.marketplace_publisher.models.BillToCountry]
        """
        return self._bill_to_countries

    @bill_to_countries.setter
    def bill_to_countries(self, bill_to_countries):
        """
        Sets the bill_to_countries of this CreateMarketDetails.
        bill to countries for the market.


        :param bill_to_countries: The bill_to_countries of this CreateMarketDetails.
        :type: list[oci.marketplace_publisher.models.BillToCountry]
        """
        self._bill_to_countries = bill_to_countries

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
